### PR TITLE
 Vitis-970 Move mature APIs to include/xrt folder

### PR DESCRIPTION
**Pull request by stsoe**
Update #include according in any exported content.

### CODE REVIEW

**Comment by salindac** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please - rpc_message.h missing ?

**Comment by stsoe** [comment]
@chvamshi-xilinx please check the changes to the emulation makefiles to add dependency on generated rpc_messages.pb.h
See also: CR-1083985 compilation fail due to XRT rpc_messages.pb.h

**Comment by chvamshi-xilinx** [comment]
> @chvamshi-xilinx please check the changes to the emulation makefiles to add dependency on generated rpc_messages.pb.h
> See also: CR-1083985 compilation fail due to XRT rpc_messages.pb.h

Looks good Soren. I am wondering why this issue is not caught locally/pipeline/customer-end from last couple of years.

**Pull request merged**
