### PR TITLE
Add deprecation for the QDMA streaming APIs

### PR DESCRIPTION
**Pull request by sonals**

### CODE REVIEW

**Review by houlz0507 — APPROVED** [review]

**Review by haeseunglee — APPROVED** [review]
Approved the pull request

**Review by uday610 — APPROVED** [review]

**Review by stsoe — CHANGES_REQUESTED** [review]
@sonal.  The point of deprecation is to not only move to deprecated/xrt.h as is done, but also remove all comments.   Let's make it as hard as possible to use these deprecated APIs.

**Comment by sonals** [comment]
Removed the documentation of deprecated streaming APIs

**Comment by sonals** [comment]
> 
> 
> @sonal. The point of deprecation is to not only move to deprecated/xrt.h as is done, but also remove all comments. Let's make it as hard as possible to use these deprecated APIs.

Updated PR

**Comment by syed-ahmed** [comment]
Thanks for this! In our [course](https://www.seas.upenn.edu/~ese532/), we struggled on understanding why the stream APIs used qdma and what was meant by h2k not available in the embedded platforms in the vitas docs. Could you elaborate a little on the slave bridge comment? Streaming from host to device is now just done through enqueMigrateMemObjects?

**Pull request merged**
