### PR TITLE
CR-1156772 Update AIE Profile, Trace flags as per request

### PR DESCRIPTION
**Pull request by hackwa**
#### Problem solved by the commit
Rename the following:
AIE_profile_settings.graph_based_mem_tile_metrics -> AIE_profile_settings.graph_based_memory_tile_metrics
AIE_profile_settings.tile_based_mem_tile_metrics -> AIE_profile_settings.tile_based_memory_tile_metrics
AIE_trace_settings.graph_based_mem_tile_metrics -> AIE_trace_settings.graph_based_memory_tile_metrics
AIE_trace_settings.tile_based_mem_tile_metrics -> AIE_trace_settings.tile_based_memory_tile_metrics
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A
#### How problem was solved, alternative solutions (if any) and why they were rejected
N/A
#### Risks (if any) associated the changes in the commit
Med
#### What has been tested and how, request additional testing if necessary
Did basic switch testing on a board. This PR requires a thorough review.

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by jvillarre — APPROVED** [review]

**Pull request merged**
