### PR TITLE
enable accelerator monitors in xbutil

### PR DESCRIPTION
**Pull request by hackwa**

### CODE REVIEW

**Comment by hackwa** [comment]
Example Output:
image

**Comment by hackwa** [comment]
Hey @maxzhen nope debug didn't follow it. Some of out outputs are super long.

**Comment by maxzhen** [comment]
> 
> 
> Hey @maxzhen nope debug didn't follow it. Some of our outputs are super long.

fair enough then.

**Comment by hackwa** [comment]
Thanks @maxzhen it is a good point. We'll see if all the debug output can be restructured sometime in future.

**Pull request merged**
