### PR TITLE
driver: libqdma: read QDMA_REG_GLBL_STRM_CHANNEL to check DMA mode

### PR DESCRIPTION
**Pull request by mclayton1000**
The QDMA_REG_GLBL_MDMA_CHANNEL (0x118) register should not be used
to check if DMA engine is in ST/MM mode.
As reported in QDMA documentation (pg302), the right register to read
is QDMA_REG_GLBL_STRM_CHANNEL (0x11C).

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
@karenx-xilinx to confirm if this change is still required. Marking it as do-not-merge for now. The change also crash one of the test machines...

**Comment by mclayton1000** [comment]
Hi @maxzhen , hi @karenx-xilinx ,

the XRT build with this patch applied is successful on my machine.
This patch is needed because reading QDMA_GLBL2_CHANNEL_MDMA (0x118) register on QDMA 3.0
to check the DMA mode is wrong. The right register to check is QDMA_GLBL2_CHANNEL_STRM (0x11C).

From pg302 (3.0), **QDMA_GLBL2_CHANNEL_MDMA** is documented as:
1) **bit 17 (c2h_st): A one indicates the C2H ST engine is QDMA;**
2) **bit 16 (h2c_st): A one indicates the H2C ST engine is QDMA;**
3) **bit 8 (c2h_eng[0]): A one indicates the C2H ST engine is QDMA;**
4) **bit 9 (h2c_eng[0]): A one indicates the H2C ST engine is QDMA.**

From pg302 (3.0), **QDMA_GLBL2_CHANNEL_STRM** is documented as:
1) **bit 17 (c2h_st): A one indicates it is a Stream mode dma engine;**
2) **bit 16 (h2c_st): A one indicates it is a Stream mode dma engine;**
3) **bit 8 (c2h_eng[0]): A one indicates it is a Memory-Mapped mode dma engine;**
4) **bit 9 (h2c_eng[0]): A one indicates it is a Memory-Mapped mode DMA engine.**

I tested a similar patch applied to https://github.com/Xilinx/dma_ip_drivers/tree/master/QDMA
(the same bug there), on a **system in which QDMA uses DMA in stream mode only**.
Here is the registers status read via debugfs:
**[  0x118] GLBL2_CHNL_QDMA_0                               0x30f0f    200463
[  0x11c] GLBL2_CHNL_STRM_0                               0x30000    196608**

@maxzhen , you reported that a test machine crashed.
Please, can you share the QDMA-shell version are you using?
In QDMA shell longue I can access only the following one: xilinx-u250-qdma-201920.1-2736445.

Thank you, best regards.

**Comment by mclayton1000** [comment]
Hi @maxzhen , hi @karenx-xilinx ,

for the record, I'm reporting libqdma bugs here because it seems that **no one is taking care of pull requests
on the official XDMA/QDMA driver repository (https://github.com/Xilinx/dma_ip_drivers/pulls)**.

Thank you, best regards.

**Comment by maxzhen** [comment]
@mclayton1000 , I'll work with @dayeh-xilinx to get the test log.

**Comment by maxzhen** [comment]
@mclayton1000 , the shell name is xilinx_u200_qdma_201910_1, the uuid is 0xc7d91a4a782860f3

**Comment by maxzhen** [comment]
Just a quick note: this pr crashed xcosda82. before we tested next time when the change is updated, we want to try it on the same system first before test it on all others.

**Comment by mclayton1000** [comment]
Hi @maxzhen ,

sorry but I can't access build-pipeline log (http://xcoengvm229019:8080/job/XBB/job/XRT/job/XRT_PR_Builds/7394/).
Please, can you tell me where build is failing?

Should I resubmit this patch?

@karenx-xilinx , please can you confirm that this patch is semantically correct?

Thank you, best regards.

**Comment by karenx-xilinx** [comment]
@mclayton1000, please hold off re-submitting the patch. I believe there are some update being worked on the PG. And the patch actually break the MM only platform. Thanks.

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx ,

ok, I'll wait for updates from you.

Just to know, will you report the QDMA bugfixes from XRT to https://github.com/Xilinx/dma_ip_drivers repository?

Thank you, best regards.

**Comment by mclayton1000** [comment]
Hi @maxzhen , Hi @karenx-xilinx ,

any news on this?

Thank you, best regards.

**Comment by karenx-xilinx** [comment]
@mclayton1000 there are multiple version of PG302 (and QDMA IP) which one are you using?

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx ,

thank you for the reply.

I'm using Xilinx IP **QDMA 3.0 with latest patch AR73653** applied (technically this should be **the so called "QDMA 3.1"**). The documentation I'm using as reference is the only publicly available: PG302 (v3.0) (https://www.xilinx.com/support/documentation/ip_documentation/qdma/v3_0/pg302-qdma.pdf).

Regards.

**Comment by mclayton1000** [comment]
About XRT, the only QDMA shells I can access are from the longues "**QDMA shell/Alveo platform early access**":
1) **xilinx-u250-qdma-201920.1-2736445**;
2) **xilinx-u250-gen3x16-qdma-2.1-202010-1-dev_1-2957202**

**Comment by karenx-xilinx** [comment]
@mclayton1000 Using QDMA_REG_GLBL_MDMA_CHANNEL (0x118) to check ST & MM mode is correct. 
Earlier in the thread you mentioned using ST only, the 2 xrt shells support both MM & ST, though you don't need to use both.

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx , Hi @maxzhen ,

thank you for the reply. I tried 3 bitstreams with QDMA configured as MM-only, ST-only and MM-ST.

Here is what I got:

1) MM-only:
    CONFIG.dma_intf_sel_qdma {AXI_MM}
    CONFIG.en_axi_st_qdma {false} 
    CONFIG.testname {mm}
    [0x118] QDMA_GLBL2_CHANNEL_MDMA: 0xF0F
    [0x11C] QDMA_GLBL2_CHANNEL_STRM: 0x000

2) ST-MM:
    CONFIG.dma_intf_sel_qdma {AXI_MM_and_AXI_Stream_with_Completion}
    CONFIG.en_axi_mm_qdma {true}
    CONFIG.en_axi_st_qdma {true}
    CONFIG.testname {mm_st}
    [0x118] QDMA_GLBL2_CHANNEL_MDMA: 0x30F0F
    [0x11C] QDMA_GLBL2_CHANNEL_STRM: 0x30000

3) ST-only:
    CONFIG.dma_intf_sel_qdma {AXI_Stream_with_Completion}
    CONFIG.en_axi_mm_qdma {false}
    CONFIG.testname {st}
    [0x118] QDMA_GLBL2_CHANNEL_MDMA: 0x30F0F
    [0x11C] QDMA_GLBL2_CHANNEL_STRM: 0x30000

**From this registers status I can conclude is that it is not possible to distinguish the ST-only case from the ST-MM one.**
Furthermore, the documentation is broken, because the register 0x118 should give information only about ST and not MM.

Screenshot_2021-01-22_19-59-42

The information about MM should come from 0x11C if the documentation is correct.

Regards.

**Comment by karenx-xilinx** [comment]
@mclayton1000 Thanks for the detail. I have passed the info to our h/w engineers. Will keep you updated on their findings.

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx ,

any news about the issues reported and PGs update?

Thank you, best regards.

**Comment by karenx-xilinx** [comment]
@mclayton1000 Yes, there is an issue differentiating between ST-only and ST-MM mode. Thanks for reporting it. 
The plan is to release the fix/workaround in the next IP release. However, this fix will only be on qdma 4.0.  So once the fix is in for qdma 4 IP,  the qdma driver at dma_ip_drivers will be updated. 
And since XRT qdma does not support ST-only mode, this bug does not affect XRT. I would suggest to close this pull request.

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx ,

thank you for the reply and support.

Why the fix will only be available for QDMA 4.0? Is there any chance that a patch will be released also for 3.0/1 case?

**Comment by maxzhen** [comment]
Closing per @karenx-xilinx 's comments. @karenx-xilinx , pls let @mclayton1000 know what you think w.r.t. the last pending question.

**Comment by karenx-xilinx** [comment]
@mclayton1000 Yes, the plan right now is to make the fix for QDMA 4 only (i.e., the latest revision).   I can put a request in for backporting the workaround, but cannot guarantee it. What is your use case? If you can give me more details that could help the case. Thanks!

**Comment by mclayton1000** [comment]
Hi @karenx-xilinx ,

thank you for the support. 

No particular use-case.
We are currently basing a long-term project on QDMA 3.1 so it would be great to have as many bug as possible fixed.

Thank you, best regards.

**Pull request closed without merging**
