### PR TITLE
Changed all names from XDP_MINIMAL_BUILD to XDP_CLIENT_BUILD

### PR DESCRIPTION
**Pull request by nishraptor**
#### Problem solved by the commit
Renamed XDP_MINIMAL_BUILD to XDP_CLIENT_BUILD
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Naming update for XDP plugins

#### What has been tested and how, request additional testing if necessary
Tested when building for client to verify dll's were generated correctly

### CODE REVIEW

**Review by stsoe — APPROVED** [review]
This is a breaking change for XRT-MCDM and XRT-IPU.  I suggest that immediately after this PR is merged, you create a PR to update XRT on both XRT-MCDM and XRT-IPU.  Thanks!

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by nishraptor** [comment]
@stsoe There were two XDP_MINIMAL_BUILD variables. The first is a CMake Variable, set by XRT-IPU, and the second is a compile-time variable only set if the CMake variable is on. I've only changed the  compile-time variable to XDP_CLIENT_BUILD, so the CMake variable should be still called XDP_MINIMAL_BUILD. I don't believe anything should break in the IPU branches from this change.

**Comment by nishraptor** [comment]
@stsoe After conversation with @jvillarre, we have decided to rename the CMake Variable as well. I will create pull requests in XRT-IPU and XRT-MCDM as well to change the CMake variable name and update the xrt commit. This will have to be done after this PR is merged.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by jvillarre — APPROVED** [review]

**Pull request merged**
