### PR TITLE
CR-1058575 SC upgrading failed on IBM redhat 7.6

### PR DESCRIPTION
**Pull request by houlz0507**

### CODE REVIEW

**Comment by houlz0507** [comment]
> please clean up pci_device::shutdown interface and call them in sc upgrade case and hotplug case. then, you don't need to duplicate the code here.

move out shutdown from pci_device class. And calling shutdown from cmd_flash.c

**Comment by houlz0507** [comment]
retest this please

**Comment by houlz0507** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
