### PR TITLE
Partial removal of AIE compilation flags in XRT

### PR DESCRIPTION
**Pull request by SravanKumarAllu-xilinx**
#### Problem solved by the commit

Removing unnecessary AIE flags partially in XRT

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected

Cleaning up XRT code to remove / minimize unnecessary compilation flags

#### Risks (if any) associated the changes in the commit

N/A

#### What has been tested and how, request additional testing if necessary

Builds of versal and non-versal (zynq) are successful.

#### Documentation impact (if any)

N/A

### CODE REVIEW

**Review by stsoe — APPROVED** [review]
LGTM.  Thanks much for this cleanup.

Little bit concerned that down stream repos will require changes, but that's okay.  We just need to watch out next XRT submodule is updated in other repos.

**Comment by chvamshi-xilinx** [comment]
> LGTM. Thanks much for this cleanup.
> 
> Little bit concerned that down stream repos will require changes, but that's okay. We just need to watch out next XRT submodule is updated in other repos.

Do we need any changes in down stream repos? as all of these functions are now have "not supported" body. I thought, we dont need any changes in downstream repos. Am i missing anything?

**Review by chvamshi-xilinx — APPROVED** [review]
We cannot remove these flags under edge folder as zynqmp doesnt have required libraries in petalinux. We need help from Petalinux to remove this flags from edge folder.

**Comment by stsoe** [comment]
> Do we need any changes in down stream repos?

Don't worry about.    Just something to look out for, probably no changes are needed.

**Pull request merged**
