### PR TITLE
XRT-871 XRT trace support

### PR DESCRIPTION
**Pull request by houlz0507**

### CODE REVIEW

**Review by maxzhen — APPROVED** [review]
looks great! do you have a simple cheat sheet about how to change the trace level and how to obtain the log?

**Comment by houlz0507** [comment]
> looks great! do you have a simple cheat sheet about how to change the trace level and how to obtain the log?

Yes, I do. :) https://confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug

**Comment by maxzhen** [comment]
> 
> 
> > looks great! do you have a simple cheat sheet about how to change the trace level and how to obtain the log?
> 
> Yes, I do. :) https://confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug

OK, we need to document this for everybody to know, including customer support team...

**Comment by keryell** [comment]
> > > looks great! do you have a simple cheat sheet about how to change the trace level and how to obtain the log?
> > 
> > 
> > Yes, I do. :) [confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug](https://confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug)
> 
> OK, we need to document this for everybody to know, including customer support team...

For example by having some documentation in this repository? :-)

**Comment by houlz0507** [comment]
> > > > looks great! do you have a simple cheat sheet about how to change the trace level and how to obtain the log?
> > > 
> > > 
> > > Yes, I do. :) [confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug](https://confluence.xilinx.com/display/~lizhih/XRT+Driver+Debug)
> > 
> > 
> > OK, we need to document this for everybody to know, including customer support team...
> 
> For example by having some documentation in this repository? :-)

Yes. We probably can add something to .rst.

**Pull request merged**
