### PR TITLE
sed apt -> apt-get for docker build purposes

### PR DESCRIPTION
**Pull request by mahdiaminik**
"apt" is not suitable for docker build

### CODE REVIEW

**Comment by keryell** [comment]
Curious. Why is it not suitable for Docker? On which OS?
On my Ubuntu 22.04 laptop I can see:
```
rkeryell@rk-xsj:~ (master)$ dpkg -S /usr/bin/apt
apt: /usr/bin/apt
rkeryell@rk-xsj:~ (master)$ dpkg -S /usr/bin/apt-get 
apt: /usr/bin/apt-get
```
so both `apt` and `apt-get` come from the same package. In my case I cannot see why I would use the older and longer `apt-get`.

**Comment by mahdiaminik** [comment]
When you use `FROM baseimage \n RUN cmd` in Dockerfile and build process instead of running `docker run -ti baseimage cmd` docker daemon creates something called "**intermediate container**" to create layers.
Intermediate containers are not created in "**tty**" sandbox.
So when you run `apt update` instead of `apt-get update` you will face the message :
- "apt does not have a stable CLI interface. Use with caution in scripts."

[https://docs.docker.com/develop/develop-images/dockerfile_best-practices/](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

**Comment by mahdiaminik** [comment]
also in line 535 :
`apt install clang-tidy`
the parameter `-y` is missing.

**Comment by keryell** [comment]
> also in line 535 : `apt install clang-tidy` the parameter `-y` is missing.

Good point. Can you indent the line while adding it?
It is unclear to me why Ubuntu 20.x requires `clang-tidy` at the first place. I use 22.04 currently. But this is another story...

**Comment by mahdiaminik** [comment]
> > also in line 535 : `apt install clang-tidy` the parameter `-y` is missing.
> 
> Good point. Can you indent the line while adding it? It is unclear to me why Ubuntu 20.x requires `clang-tidy` at the first place. I use 22.04 currently. But this is another story...

In git graph it can be checked that why this line is added, but for answering these build issues I suggest add a `Dockerfile` in the repository (something like [https://github.com/Xilinx/XRT/issues/6942](https://github.com/Xilinx/XRT/issues/6942) , without `sed` command of course) and add `docker build` in the CI pipeline (in this case `.travis.yml` file)

**Comment by stsoe** [comment]
ok to test

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
