### PR TITLE
Add support for qspi_versal flash type

### PR DESCRIPTION
**Pull request by rbramand-xilinx**
> Added qspi flash support for versal devices, it uses ospi versal concept
> User can give flash_type "qspi_versal" in xbmgmt flash command

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
@rbramand-xilinx , You need to make changes to new tool (xbmgmt2) as well.

**Comment by rbramand-xilinx** [comment]
> @rbramand-xilinx , You need to make changes to new tool (xbmgmt2) as well.

@chvamshi-xilinx, I have added changes to new tools as well. Please review

**Review by chvamshi-xilinx — APPROVED** [review]

**Review by maxzhen — CHANGES_REQUESTED** [review]
Do we still need to support OSPI versal type? I see that we removed it from driver but kept in tools, so wondering why?

**Comment by chvamshi-xilinx** [comment]
> Do we still need to support OSPI versal type? I see that we removed it from driver but kept in tools, so wondering why?

vck5000 uses OSPI type. vck190 uses QSPI. Underlying code is same for both types.

**Comment by maxzhen** [comment]
> 
> 
> > Do we still need to support OSPI versal type? I see that we removed it from driver but kept in tools, so wondering why?
> 
> vck5000 uses OSPI type. vck190 uses QSPI. Underlying code is same for both types.

but we have removed OSPI versal type from driver? is this ok?

**Comment by chvamshi-xilinx** [comment]
> > > Do we still need to support OSPI versal type? I see that we removed it from driver but kept in tools, so wondering why?
> > 
> > 
> > vck5000 uses OSPI type. vck190 uses QSPI. Underlying code is same for both types.
> 
> but we have removed OSPI versal type from driver? is this ok?

No Max. Its not removed. OSPI is replaced with QSPI only for VCK190 device structure.

**Comment by AShivangi** [comment]
Oh I was confused about the same. In that case, can we add a comment in flasher.cpp explaining this

**Comment by chvamshi-xilinx** [comment]
> Oh I was confused about the same. In that case, can we add a comment in flasher.cpp explaining this

Sure Shivangi. Are you suggesting to add a comment something like "Underlying code to support qspi & ospi types is same.  Two different CLI's are provided for better user experience. VCK190 has qspi flash and VCK5000 has ospi flash"
or anything more?

**Comment by AShivangi** [comment]
> > Oh I was confused about the same. In that case, can we add a comment in flasher.cpp explaining this
> 
> Sure Shivangi. Are you suggesting to add a comment something like "Underlying code to support qspi & ospi types is same. Two different CLI's are provided for better user experience. VCK190 has qspi flash and VCK5000 has ospi flash"
> or anything more?

This looks pretty good! Thanks

**Comment by maxzhen** [comment]
> 
> 
> > > > Do we still need to support OSPI versal type? I see that we removed it from driver but kept in tools, so wondering why?
> > > 
> > > 
> > > vck5000 uses OSPI type. vck190 uses QSPI. Underlying code is same for both types.
> > 
> > 
> > but we have removed OSPI versal type from driver? is this ok?
> 
> No Max. Its not removed. OSPI is replaced with QSPI only for VCK190 device structure.

OK, I see. Thanks for clarifying.

**Review by maxzhen — APPROVED** [review]

**Comment by AShivangi** [comment]
Approved. Please add sample output for the new xbmgmt flash before merging.

**Review by AShivangi — APPROVED** [review]

**Comment by maxzhen** [comment]
@rbramand-xilinx please still provide what @AShivangi is asking for. I missed @AShivangi 's ask before merge.

**Comment by rbramand-xilinx** [comment]
Hi all,

The following is the sample output that is displayed when flashing using new tool xbmgmt2 :

**xbmgmt program -d 0000:18:00.0 --base --image /lib/firmware/xilinx/fedcba987654321fedcba987654321fe/BOOT_FLASH.BIN --flash-type qspi_versal**   
                                                                  
Are you sure you wish to proceed? [Y/n]: y
XRT build version: 2.12.0
Build hash: dd2bbb635ea2e7a251d594a7592f9d6ed5174231
Build date: 2021-07-28 04:08:53
Git branch: master
PID: 97762
UID: 0
[Tue Jul 27 22:41:50 2021 GMT]
HOST: xhdamitkasat-lab.xilinx.com
EXE: /opt/xilinx/xrt/bin/unwrapped/xbmgmt2
[XRT] WARNING: Overriding flash mode is not recommended.
You may damage your device with this option.
INFO: ***PDI has 133696048 bytes
INFO     : Base flash image has been programmed successfully. 
****************************************************
Cold reboot machine to load the new image on device.
****************************************************


-> Also if we don't explicitly specify flash-type also it will pick up the type as qspi_versal as a sysfs node flash_type is already being generated in driver.

**Pull request merged**
