### PR TITLE
CR-1049198 U50 3x16x 201920_2 - xbulti changes to revert to using hello_world and kernel_bw

### PR DESCRIPTION
**Pull request by AShivangi**

### CODE REVIEW

**Comment by AShivangi** [comment]
will cherrypick into master later

**Comment by salindac** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by stsoe** [comment]
Please close this PR and cherry pick instead

**Comment by salindac** [comment]
retest this please

**Pull request merged**
