### PR TITLE
Enabled the support for Questa, Xcelium and VCS simulator for alveo platforms

### PR DESCRIPTION
**Pull request by venkatp-xilinx**
Enabled the support for Questa, Xcelium and VCS simulator for alveo platforms

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
@venkatp-xilinx , Hopefully this is intermediate change. It would be better if we have simulator information added as part of xclbin.

**Comment by venkatp-xilinx** [comment]
> @venkatp-xilinx , Hopefully this is intermediate change. It would be better if we have simulator information added as part of xclbin.

Yes Vamsi, we are working to have tag in XCLBIN, and once that is in, we will make use of it.

**Comment by chvamshi-xilinx** [comment]
> 
> 
> > @venkatp-xilinx , Hopefully this is intermediate change. It would be better if we have simulator information added as part of xclbin.
> 
> Yes Vamsi, we are working to have tag in XCLBIN, and once that is in, we will make use of it.

Thanks Prasad for confirming.

**Pull request merged**
