### PR TITLE
Decouple Live messaging from XDP 

### PR DESCRIPTION
**Pull request by hemantk-xilinx**

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
ok to test

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by pgschuey** [comment]
This pull request was tested with corresponding linker changes, and was verified to work correctly.

**Comment by pgschuey** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Pull request merged**
