### PR TITLE
CR-1107607 search vsec info both in pcie extended config space and ba…

### PR DESCRIPTION
**Pull request by xuhz**
…sic config space (#5617)

(cherry picked from commit 2cbaa91e5639a863947e88f252de16180be3ea4f)

### CODE REVIEW

**Review by houlz0507 — APPROVED** [review]

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Review by houlz0507 — APPROVED** [review]

**Pull request merged**
