### PR TITLE
Fix for CR-1150767 clock throttling documentation.

### PR DESCRIPTION
**Pull request by rchane**
#### Problem solved by the commit
Updated clock throttling documentation 
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://github.com/Xilinx/XRT/pull/7436, verifier asked for further clarification/changes
#### How problem was solved, alternative solutions (if any) and why they were rejected
A section dedicated to clock throttling was added to xbmgmt configure. 
#### Risks (if any) associated the changes in the commit
This is a fix for 2023.1 CR and needs to be backported.
#### What has been tested and how, request additional testing if [necessary]
Documentation has been reviewed with Vamshi and the verifier. Attached is a PDF version of the changes (before the hyperlink for UG1120 was added, check the raw code for the hyperlinks).
[Xbmgmt Documentation.pdf](https://github.com/Xilinx/XRT/files/11235245/Xbmgmt.Documentation.pdf)
#### Documentation impact (if any)
This is a documentation change.

### CODE REVIEW

**Review by uday610 — APPROVED** [review]

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by rchane** [comment]
Hello @stsoe @sonals , this PR is ready for merging when you are available. Thank you!

**Comment by stsoe** [comment]
@rchane Please use `git cherry-pick -x <commit hash>` to cherry-pick to 2023.1

**Pull request merged**
