### PR TITLE
CR-1077276 enable cmc support on raptor2 1rp u2 shell

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
If clock throttling endpoint is present in partition metadata then clock throttling feature is supported on u2.
If ep_cmc_firmware_mem_00 missing in partition metadata, it implies that CMC is part of bitfile on u2.

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

### CODE REVIEW

**Review by xdavidz — APPROVED** [review]
Seems ok, please make sure it won't break any non-u.2 system. This resource is u.2 only, but we are data driven, so please make sure it is not u.2 specific but data-driven specific. The code is xmc.c seems complicate before and now it is cleaner. 👍

**Review by maxzhen — APPROVED** [review]
Could you listed what boards/shell you've tested it on other than u.2?

**Comment by rajkumar-xilinx** [comment]
> Could you listed what boards/shell you've tested it on other than u.2?

Hi @maxzhen , I validated this patch with below combinations
1. U2 legacy shell + this patch
2. U2 raptor2 1rp shell + this patch
3. U50 + this patch

I run xbutil tests like list | query | validate.

Please suggest any other tests or combination before merging this test. I will test and post my observations. Thanks.

**Comment by xdavidz** [comment]
> > Could you listed what boards/shell you've tested it on other than u.2?
> 
> Hi @maxzhen , I validated this patch with below combinations
> 
> 1. U2 legacy shell + this patch
> 2. U2 raptor2 1rp shell + this patch
> 3. U50 + this patch
> 
> I run xbutil tests like list | query | validate | reset.
> 
> Please suggest any other tests or combination before merging this patch. I will test and post my observations. Thanks.

If you want to test u55, u250 or u280, please let me know. I can set this up for you on Monday PST. I think it is ok if you have tested u50, because this res is u.2 only. As long as u50 doesn't have regression, other platforms should not have regression too.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by rajkumar-xilinx** [comment]
> > > Could you listed what boards/shell you've tested it on other than u.2?
> > 
> > 
> > Hi @maxzhen , I validated this patch with below combinations
> > 
> > 1. U2 legacy shell + this patch
> > 2. U2 raptor2 1rp shell + this patch
> > 3. U50 + this patch
> > 
> > I run xbutil tests like list | query | validate | reset.
> > Please suggest any other tests or combination before merging this patch. I will test and post my observations. Thanks.
> 
> If you want to test u55, u250 or u280, please let me know. I can set this up for you on Monday PST. I think it is ok if you have tested u50, because this res is u.2 only. As long as u50 doesn't have regression, other platforms should not have regression too.

Hi @xdavidz , I validated this patch on U250 setup also. Performed the xbutil tests like list | query | validate | reset

**Review by houlz0507 — APPROVED** [review]

**Pull request merged**
