### PR TITLE
Fix XMA Legacy multi-process resource mgmt issues in 2019.2

### PR DESCRIPTION
**Pull request by jmouroux**
This pull request includes two commits that address issues in multi-process kernel resource management within the xma_legacy codebase.

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by maxzhen** [comment]
I don't think 2019.2 pipeline test is still functioning. Shouldn't this fix to go into master first and run through pipeline? @jmouroux @sarab96

**Comment by stsoe** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Pull request merged**
