### PR TITLE
Update testcases with memory bank error message

### PR DESCRIPTION
**Pull request by haeseung81**
Updated all the utils.h files and host codes.
But, 100_ert is not updated because it's using utils.hpp, which has a different structure.
100_ert and utils.hpp will be handled separately.

### CODE REVIEW

**Comment by hcneema** [comment]
please retest. I will file new issues for the following
1. Makefile is not working currently
2. every test has a copy of utils.h. We should pick up from host_src area for for nightly and for 1) above.

**Comment by hcneema** [comment]
please retest

**Comment by haeseung81** [comment]
I was able to compile/build the xrt on the local machine and my change does not include the XRT portion.
I also checked the build log, and it looks like something went wrong during driver installation, which is not related to my change.

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
