### PR TITLE
Fix for 2kernelglobal bandwidth checking

### PR DESCRIPTION
**Pull request by haeseung81**
2kernelglobal has incorrect bandwidth threshold.
So, I fixed the bandwidth threshold.

### CODE REVIEW

**Comment by sonals** [comment]
Should we merge this into 2018.3?

**Comment by haeseung81** [comment]
If it's possible, yes.
The current bandwidth threshold is 40GB, which is not correct value.
So, without this fix, this test will always say fail.

**Comment by sonals** [comment]
Can you close this PR and recreate another PR for 2018.3?
2018.3 -> master merging is automatically handled by XRT team.

**Comment by haeseung81** [comment]
Ok. I'll do that.

**Pull request closed without merging**
