### PR TITLE
Restructure runtime_src/driver

### PR DESCRIPTION
**Pull request by stsoe**
Reorganize runtime_src/driver content under runtime_src/core for core XRT.
Minor code #include changes to fit new organization.
Major CMake changes.

### CODE REVIEW

**Comment by stsoe** [comment]
Reviewers added as FYI.

**Comment by mamin506** [comment]
In src/runtime_src/core/edge/user/shim.h, line 23 and 24.
\#include "core/edge/include/xclhal2_mpsoc.h"
\#include "core/edge/include/zynq_ioctl.h"

**Comment by stsoe** [comment]
Min, please check again.  I had missed a few files.
The problem is I am not building edge, so it's possible there is more missing; I hope you don't mind revisiting once PR is merged.

**Comment by mamin506** [comment]
> Min, please check again. I had missed a few files.
> The problem is I am not building edge, so it's possible there is more missing; I hope you don't mind revisiting once PR is merged.

No problem Soren. I would build edge on my side.

**Pull request merged**
