### PR TITLE
cherry-pick 3 PRs with manual conflict resolve

### PR DESCRIPTION
**Pull request by xuhz**
cherry-pick VITIS-2944 XRT kernel driver memory footprint reduction 
cherry-pick CR-1105830 vfree to a kmalloc address
cherry-pick CR-1108703 enable XCL_MAILBOX_REQ opcode for u30

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. Failed with an infra error.

**Review by houlz0507 — APPROVED** [review]

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
