### PR TITLE
CR-1117201 Backport SUSE SLES 15 SP2 fixes

### PR DESCRIPTION
**Pull request by rbramand-xilinx**
> Backported changes from master branch to 2021.2
> Fix driver compilation issues on SUSE SLES 15 SP2
> Remove fpga-mgr dependency from xclmgmt driver

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please. After the obsolete  BMC/CMC firmware is removed.

**Pull request merged**
