### PR TITLE
CR-1110437 - did not rename slavebridge.exe in xbutil validate

### PR DESCRIPTION
**Pull request by vishnuchebrolu**
https://jira.xilinx.com/browse/CR-1110437

**_Issue_**
xbutil validate test `host_mem_23_bandwidth.py` is using the incorrect host executable.  It should be using `hostmemory.exe` instead of `slavebridge.exe`.

**_Resolution_**
The code has been updated to use the `hostmemory.exe` host executable.

**_Side Note_**
Being that the hostmemory.exe already exist there are no impacts with this host code naming change.   There is an issue with the xclbin image name change that is being addressed by Vishnu.

### CODE REVIEW

**Review by AShivangi — APPROVED** [review]

**Review by rozumx — CHANGES_REQUESTED** [review]
Could you help me understand why these changes were required.  Basically, I am looking for.

1. A reference CR
2. The side effect of these change (e.g., are there any existing validation packages that already contain the `slavebridge.exe` executable).

**Comment by AShivangi** [comment]
@rozumx, the details are in the CR-1110437

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Review by rozumx — APPROVED** [review]

**Review by AShivangi — COMMENTED** [review]
backward compatibility to be added

**Pull request merged**
