### PR TITLE
XRT-858 new KDS needs to support soft kernel statistics

### PR DESCRIPTION
**Pull request by mamin506**
Backport PS kernel statistics (part of #4767) to 2020.2_PU1.

### CODE REVIEW

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Pull request merged**
