### PR TITLE
CR-1126348 display Config Mode & Max Power when these are non zero values and fix mechanical error info in xbmgmt/xbutil examine reports (#6493)

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
* CR-1126348 display Config Mode only when it is a non zero value

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>
(cherry picked from commit 7f7cab2ae0692648eeae80b704ed9f68795950e8)

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
Integrated from master (https://github.com/Xilinx/XRT/pull/6493) to 2022.1 branch

**Comment by chvamshi-xilinx** [comment]
Hi @rajkumar-xilinx ,
As Soren mentioned in xrt_all channel
" Please use git cherry-pick -x <commit>  where commit is the hash from master. Don't bother with PR description above and beyond what Git puts in by default from the cherry pick"
Dont send a seperate commit

**Review by AShivangi — APPROVED** [review]

**Review by rozumx — APPROVED** [review]

**Comment by rajkumar-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Review by stsoe — APPROVED** [review]

**Review by anupcs-xlnx — APPROVED** [review]

**Pull request merged**
