### PR TITLE
CR 1098713 : Fix for GMIO trace offload 

### PR DESCRIPTION
**Pull request by IshitaGhosh**
Till 2020.2, zynqaie::Aie class used to contain a ShimDMA object which contained the SHIM Descriptor object. But with new infrastructure in 2021.1 (FAL and other common layer changes), the ShimDMA object is made redundant. This broke GMIO trace offload support in XDP as it used zynqaie::Aie::ShimDMA object to get the SHIM Descriptor object for initializin SHIM DMA for GMIO stream.
To fix this, new adf::trace_gmio_config and adf::trace_gmio_api data structures are introduced which contain the Trace GMIO metadata from the aie_metadata and corresponding XAie_DmaDesc instance and XAie_LocType object.
With this change, GMIO trace offload started working again.

### CODE REVIEW

**Review by jerryhsu-xilinx — CHANGES_REQUESTED** [review]
Why do you add trace_gmio_api to common_layer?
This directory is specific for cardano to share common graph API to XRT, i.e., the source of origin is from cardano perforce.

**Comment by IshitaGhosh** [comment]
Hi @jerryhsu-xilinx , Larry pointed me to the gmio section in the common layer which corresponds to "GMIO" metadata in "aie_metadata" section in xclbin. This "aie_metadata" is generated by AIE during AIE compilation. "aie_metadata" section also contains "TraceGMIO" section which gives info on Trace GMIO streams. This "TraceGMIO" section is used by XDP to configure AIE Event Trace offload using GMIO streams. But, unlike GMIO or PLIO aie_metadata sections, TraceGMIO was missing in the common layer. So, I added "trace_gmio_config" and "trace_gmio_api" corresponsing to "TraceGMIO" AIE metadata in the common layer.
I can move these structures into XDP but they do correspond to "aie_metadata" section.

**Comment by jerryhsu-xilinx** [comment]
Hi @IshitaGhosh , based on your comment, the code should move to XDP.
The aie metadata parser still parse traceGMIO section.

**Review by larry9523 — APPROVED** [review]

**Review by jvillarre — APPROVED** [review]
Changes look good

**Comment by IshitaGhosh** [comment]
Hi @jerryhsu-xilinx , I have added the changes you suggested. Can you please review again and approve, if good?

**Comment by jerryhsu-xilinx** [comment]
there is no change in common_layer. looks good.

**Pull request merged**
