### PR TITLE
Revert "NSPR-1387 : Xrt hbm support"

### PR DESCRIPTION
**Pull request by stsoe**
Reverts Xilinx/XRT#3567

### CODE REVIEW

**Comment by stsoe** [comment]
Running cached u200 board tests exposed problems with some tests.  I will email details.

**Comment by stsoe** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Pull request merged**
