### PR TITLE
CR-1082322: kernel argument fix in cpp api

### PR DESCRIPTION
**Pull request by sarab96**
kernel argument check added
This fix addresses below problem.

If extra argument was passed to kernel:
    - No error was given
    - Kernel output was incorrect

### CODE REVIEW

**Comment by stsoe** [comment]
I am not comfortable with this fix without a corresponding CR.  While the fix may be exactly what is needed, please associate it with a CR.

**Comment by sarab96** [comment]
Added CR #: CR-1082322. With this fix extra kernel argument throws out of range exception. Like argument 1 is out of range from range size of one.

**Comment by stsoe** [comment]
Thanks @sarab96.  I will need the non-indexed args stored in the args array for supporting OpenCL through the native APIs.
Lets change this PR to simply throw out-of-range in kernel::get_arg(size_t argidx) when argidx is different from the arguments index.  Either that or ignore the trailing arguments that are out-of-range (as the c-style va_list does).

**Comment by sarab96** [comment]
Updated.  It will throws runtime error of bad argument index

**Review by stsoe — APPROVED** [review]

**Comment by stsoe** [comment]
retest this please

**Pull request merged**
