### PR TITLE
 Raptor 2.0: Partition Metadata Support

### PR DESCRIPTION
**Pull request by rozumx**
Work Done
    --------
    1) Rename SectionDTC to SectionPartitionMetadata.
    2) Refactored TRACE_PrintTree to use JSON writer to produce pretty JSON output.
    3) Added support in defining property types and sizes to JSON properties.
    4) Added support to transform the partition metadata schema to the DTC schema.
    5) Added support to transform the DTC schema to the partition metadata.
    6) Added new DTC format types: String Arrays, uint32_t arrays, and uint64_t
    7) Refactored the FDTProperty class to be data driven
    8) Added more documention in the SectionParitionMetadata class.

Note
------
This work is only associated with Partition Metadata section (currently in development)

### CODE REVIEW

**Comment by rozumx** [comment]
OK to test

**Comment by rozumx** [comment]
OK to test

**Comment by sonals** [comment]
retest this please

**Comment by rozumx** [comment]
retest this please

**Comment by rozumx** [comment]
retest this please

**Pull request merged**
