### PR TITLE
VITIS-10487 Add throughput and latency no-op test

### PR DESCRIPTION
**Pull request by AShivangi**
#### Problem solved by the commit
 Add throughput and latency to verify test

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary

```
> xbutil.exe validate -d 00c3:00:01.1 -r verify
------------------------------------------------------------
                        EARLY ACCESS
        This release of xbutil contains early access
         experimental features which may have bugs.
------------------------------------------------------------
Validate Device           : [00c3:00:01.1]
    Platform              : RyzenAI-Phoenix
-------------------------------------------------------------------------------
Verbose: Enabling Verbosity
Test 1 [00c3:00:01.1]     : verify
    Description           : Run 'Hello World' kernel test
    Xclbin                : C:\Windows\System32\DriverStore\FileRepository\ipustack.inf_amd64_cabd6000fc08d7ce\validate_phx.xclbin
    Details               : Kernel name is 'DPU_PDI_0'
                            Average throughput: '6265.9' ops/s
                            Average latency: '159.5' us
   Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed
```

#### Documentation impact (if any)
None

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by maxzhen** [comment]
Merging per request by @AShivangi

**Pull request merged**
