### PR TITLE
p2p force reassign iomem, driver remove, close protection

### PR DESCRIPTION
**Pull request by houlz0507**

### CODE REVIEW

**Comment by sonals** [comment]
ok to test

**Comment by houlz0507** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by houlz0507** [comment]
Hi Max,
I thought about that. It seems not working. the ioctl for example can happen concurrently with remove. so considering this scenario
remove()
     -> cv wait passed
    -> remove success
ioctl comes in

And yes, we can discuss better way to handle this.

**Comment by maxzhen** [comment]
Had a lengthy discussion with Lizhi about this PR. We concluded that the current implementation for protecting driver from crashing during removal is not efficient and does not cover all race cases. We have found a better solution and Lizhi will implement it in a separate PR. I'm merging this one so that the resizing BAR functionality is complete in master.

**Pull request merged**
