### PR TITLE
Profiling bandwidth calculation fixes for AWS in 2021.2 branch

### PR DESCRIPTION
**Pull request by jvillarre**
#### Problem solved by the commit
This pull request back-ports some fixes implemented in 2022.1 to the 2021.2 branch to address incorrect profiling numbers seen on AWS.

In particular, this back-ports the splitting of "max bandwidth" calculations to the max bandwidth between the host and the device, and the max bandwidth between the kernel and the memory.  Each shim returns a different max bandwidth based on the device capabilities so that the numbers calculated by profiling reflect the correct percentage of bandwidth.

Since these are shim functions, stubs are added for the emulation shims.

#### What has been tested and how, request additional testing if necessary
This has been tested on designs on an AWS instance and the numbers reported are now as expected.

#### Documentation impact (if any)
When merged, the commit hash ID will be added to an Action Record for AWS users to grab the correct version of 2021.2 with the fixes.

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by pgschuey — APPROVED** [review]
looks good

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
