### PR TITLE
kds dataflow support

### PR DESCRIPTION
**Pull request by stsoe**
Dataflow is supported in KDS only, no ERT support yet.

### CODE REVIEW

**Comment by stsoe** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by nbalagopal** [comment]
retest this please

**Comment by nbalagopal** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by stsoe** [comment]
Giving up on this one.  Will try again with new PR with debug enabled.

**Pull request closed without merging**
