### PR TITLE
Enabling CDMA in hw_emu

### PR DESCRIPTION
**Pull request by chvamshi-xilinx**
Hi All,

This PR contains all changes to support CDMA in hw_emu. 

Thanks
Vamshi Krishna

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
