### PR TITLE
libqdma: Sync QDMA drivers to latest (#7122)

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
This update has following XRT fix

>> Integrate PR (https://github.com/Xilinx/dma_ip_drivers/pull/180) to enable
XRT stack to get the user interrupt index from qdma driver

Signed-off-by: Rajkumar Rampelli <rampelli@amd.com>

Signed-off-by: Rajkumar Rampelli <rampelli@amd.com>
Co-authored-by: Rajkumar Rampelli <rampelli@amd.com>
(cherry picked from commit 1e3b0573ab01bc44079d18ab4cd10889ec7a3dd8)

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Pull request merged**
