### PR TITLE
Generating sdk.sh (sysroot) and keeping it in apu_package

### PR DESCRIPTION
**Pull request by chvamshi-xilinx**
#### Problem solved by the commit
Generating sdk.sh (sysroot) and keeping it in apu package so that application can use this to compile PS apps/PS Kernels

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
NA

#### How problem was solved, alternative solutions (if any) and why they were rejected
Added sdk.sh in apu package

#### Risks (if any) associated the changes in the commit
**APU package size is increased by 534 MB**

#### What has been tested and how, request additional testing if necessary
VCK5000

#### Documentation impact (if any)
NA

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by stsoe — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by rozumx — APPROVED** [review]

**Pull request merged**
