### PR TITLE
CR-1132928 Xbutil validate fails DMA test (#6805)

### PR DESCRIPTION
**Pull request by houlz0507**
Co-authored-by: Lizhi Hou <lizhi.hou@xilinx.com>
(cherry picked from commit 42a09031a4ca172a791bb0274c16e95db14c42b3)
Please see detail: https://github.com/Xilinx/XRT/pull/6805

### CODE REVIEW

**Review by anupcs-xlnx — APPROVED** [review]
Already discussed and I approve this backport.

**Review by keryell — CHANGES_REQUESTED** [review]
Explain with some comments what is happening here.

**Comment by houlz0507** [comment]
The detail comment is provide in the original PR: https://github.com/Xilinx/XRT/pull/6805

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by maxzhen — APPROVED** [review]

**Review by sonals — APPROVED** [review]

**Comment by keryell** [comment]
> The detail comment is provide in the original PR: #6805

There is no comment in the code either in https://github.com/Xilinx/XRT/pull/6805 which is bad practice :-(

**Comment by keryell** [comment]
You need to understand that the description of a PR or a commit is useful but mostly lost forever when not in comments in the real source code.

**Pull request merged**
