### PR TITLE
CR-1091190: Fixing incorrect warnings

### PR DESCRIPTION
**Pull request by jvillarre**
This pull request:
- Fixes the text in a warning as it no longer applies
- Removes errors and warnings that no longer apply
- Slightly refactors the namespaces and names of functions in the HAL plugin loading
- Changes a few files from DOS style endlines to Linux style endlines

### CODE REVIEW

**Review by pgschuey — APPROVED** [review]
namespace and other changes look good

**Review by hackwa — APPROVED** [review]
looks good!

**Comment by dayeh-xilinx** [comment]
retest this please. Cancelled earlier to give priority to u30 branch.

**Review by IshitaGhosh — APPROVED** [review]
The changes make XDP source more organized and readable.

**Pull request merged**
