### PR TITLE
CR-1062037 CR-1061292 CR-1060360 Added new INI switches xtlm_aximm_log and xtlm_axis_log to enable or disable the SystemC transaction logging. 

### PR DESCRIPTION
**Pull request by venkatp-xilinx**
CR-1062037: Added the new INI switches xtlm_aximm_log and xtlm_axis_log to enable or disable the SystemC XTLM transaction logging. Generalized the logic to have user_pre_sim_script and user_post_sim_script 
Reviewer: @ramyam-xilinx 
Verification: All the tests are passing, now user has the log control at runtime which is very useful and saves memory

CR-1061292: Added the proper log when user requested thru xrt.ini file
Verification: All the tests are passing
Reviewer: @ramyam-xilinx 

CR-1060360 Added the new DRC for Versal platforms to ensure EMULATION_DATA section is available in XCLBIN.
Verification: All the tests are passing
Reviewer: @ramyam-xilinx

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by venkatp-xilinx** [comment]
I have pool of changes to be submitted after this. Can you please merge this change?

**Comment by xilinxgitops** [comment]
retest this please

**Pull request merged**
