### PR TITLE
skd: Change process name to match soft kernel name

### PR DESCRIPTION
**Pull request by Rohit-Athavale**
The commit tries to change the process name to match the soft kernel name.
This proves to be useful when trying to debug the performance of specific
soft kernels, unique names aids in tracking in these details.

top shows the process names by their kernel names, ps still shows skd.

Signed-off-by: Rohit Athavale <rathaval@xilinx.com>

### CODE REVIEW

**Comment by Rohit-Athavale** [comment]
@larry9523 @mamin506 

Hi Team,

This PR lets us view the kernel names via top, so we can notice abnormal behaviours. 
prctl() seemed more standard than pthread_setname_np(). Please take a look.

**Comment by maxzhen** [comment]
ok to test

**Comment by larry9523** [comment]
This looks good.  Thanks for making this change. 

A nit, can we move the process name setting prctl() right after we fork this new process (at line 306 in the new code)?

Just curious, I know top will show the new process name, what does ps -ef show? I did a simple test on x86, where ps -ef still showing the old process name unless I modify argv[0].

**Comment by rathaval** [comment]
> 
> 
> This looks good. Thanks for making this change.
> 
> A nit, can we move the process name setting prctl() right after we fork this new process (at line 306 in the new code)?
> 
> Just curious, I know top will show the new process name, what does ps -ef show? I did a simple test on x86, where ps -ef still showing the old process name unless I modify argv[0].

Hi Larry, not sure if I should go change the argv[0] value, I believe its not portable, and I've also read online the the name can be only over-written, as in, if the original name is 4 characters long, then changing it to something longer than that is questionable.

prctl changes the names to "kernel_source0", "kernel_source1", ..., "kernel_sink0" etc in top which match the kernel names provided when downloading the soft kernels from x86. However, ps still shows skd as the process name.

Please comment on whats the best way to proceed ? Proceed with argv[0] change or just stick with prctl after fork() system call ? @larry9523

**Comment by larry9523** [comment]
> > This looks good. Thanks for making this change.
> > A nit, can we move the process name setting prctl() right after we fork this new process (at line 306 in the new code)?
> > Just curious, I know top will show the new process name, what does ps -ef show? I did a simple test on x86, where ps -ef still showing the old process name unless I modify argv[0].
> 
> Hi Larry, not sure if I should go change the argv[0] value, I believe its not portable, and I've also read online the the name can be only over-written, as in, if the original name is 4 characters long, then changing it to something longer than that is questionable.
> 
> prctl changes the names to "kernel_source0", "kernel_source1", ..., "kernel_sink0" etc in top which match the kernel names provided when downloading the soft kernels from x86. However, ps still shows skd as the process name.
> 
> Please comment on whats the best way to proceed ? Proceed with argv[0] change or just stick with prctl after fork() system call ? @larry9523

@Rohit-Athavale , I am fine with the current change (just think move the prctl right after fork is better). At least we have top works better and can give us map between ps name and pid which can be used in other tools like ps.

**Comment by rathaval** [comment]
@larry9523 Updated the PR with the suggested changes. Please take a look.

Unrelated question : Why is the build failing ? I'm able to build on petalinux side with 2018.3. 
Does the build trigger a petalinux compilation of the bitbake recipes ?

**Comment by larry9523** [comment]
> @larry9523 Updated the PR with the suggested changes. Please take a look.
> 
> Unrelated question : Why is the build failing ? I'm able to build on petalinux side with 2018.3.
> Does the build trigger a petalinux compilation of the bitbake recipes ?

Don't worry about the Build failure. It is the pipeline issue and is being worked on.

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
