### PR TITLE
Updates support Yocto

### PR DESCRIPTION
**Pull request by mamin506**
This the initial update for support Yocto.
Currently, this items has been done.
1. Use CMAKE_SYSTEM_PROCESSOR determine target arch.
2. Remove kernel2/ folder.
3. Add CMakeLists.txt for zynq xrt_core.so
4. Disabled compilation for xclbin tools, ert, xclng and emulation stuff.
5. Update Makefile in zocl driver

### CODE REVIEW

**Comment by hcneema** [comment]
please retest

**Comment by mamin506** [comment]
Rebased to commit "eedba4bfe4cfddff4709f26a98205399e11627b9"

**Comment by hcneema** [comment]
showing changes to 31 files, please check ...

**Comment by mamin506** [comment]
> showing changes to 31 files, please check ...

I remove src/runtime_src/driver/zynq/kernel2 directory and move all sub directories to src/runtime_src/driver/zynq/. That is why it has 30+ files change.

**Comment by sonals** [comment]
@mamin506, can you rebase with latest XRT CMake changes?

**Comment by mamin506** [comment]
@sonals  Done. Test:
1. build.sh -- passed
2. Yocto recipe -- passed

**Comment by mamin506** [comment]
retest this please.

**Pull request merged**
