### PR TITLE
CR-1144576 progress bar for xbmgmt program -b shell

### PR DESCRIPTION
**Pull request by rchane**
#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1144576 `xbmgmt program -b shell` should have a progress bar
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
`xbmgmt program -b shell` did not have a progress bar/indication of progress on some flash types (e.g. XGQ_VMR_Flasher and XOSPIVER_Flasher), leaving developers to wait in the dark while the associated card was flashed.
#### How problem was solved, alternative solutions (if any) and why they were rejected
A busy bar with time elapsed was added to such flash types to fix the issue.
#### Risks (if any) associated the changes in the commit
N/A
#### What has been tested and how, request additional testing if necessary
I tested on vck5000 with xilinx_vck5000_gen4x8_qdma_base_2. The shell was successfully programmed, and the busy bar appeared during flashing.

Output while Flashing:
```
root@xsjsagarw50:~# xbmgmt program -b shell -d 65:00 --image xilinx_vck5000_gen4x8_qdma_base_2
***********************************************************
*        WARNING          WARNING          WARNING        *
*  SC version data missing. Expected: N/A Current: 4.4.35 *
***********************************************************
INFO: ***xsabin has 6963555 bytes
[           <->      ]: Working...... < 8s >
```
Output after Flashing:
```
root@xsjsagarw50:~# xbmgmt program -b shell -d 65:00 --image xilinx_vck5000_gen4x8_qdma_base_2
***********************************************************
*        WARNING          WARNING          WARNING        *
*  SC version data missing. Expected: N/A Current: 4.4.35 *
***********************************************************
INFO: ***xsabin has 6963555 bytes
INFO: ***Write 6963555 bytes
INFO     : Base flash image has been programmed successfully. 
****************************************************
Cold reboot machine to load the new image on device.
****************************************************
```
#### Documentation impact (if any)
N/A

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — CHANGES_REQUESTED** [review]
You should add this functionality in the OO_UpdateShell file. We shouldnt be adding this functionality at low level functions.
look at update_versal_SC in OO_UpdateBase file.

**Comment by rchane** [comment]
> You should add this functionality in the OO_UpdateShell file. We shouldnt be adding this functionality at low level functions. look at update_versal_SC in OO_UpdateBase file.

Hi Vamshi, if I understood correctly, David wanted the bar to show up for xbmgmt program -b shell, which funnels through OO_UpdateBase.cpp (e.g. `xbmgmt program -b shell -d 65:00 --image xilinx_vck5000_gen4x8_qdma_base_2`). I agree; I initially tried to put the bar in [OO_UpdateBase Line 70](https://github.com/Xilinx/XRT/blob/master/src/runtime_src/core/tools/xbmgmt2/OO_UpdateBase.cpp#L70) instead of the low-level flasher, but since there is extra output flushed to cout within the flashers, the bar will not clean up output properly. This resulted in some previous output being deleted instead of the bar itself once flashing was complete. In addition, the ProgressBar for update_versal_SC required a timeout, so BusyBar was chosen to provide similar information. Please let me know  your thoughts!

**Comment by chvamshi-xilinx** [comment]
> > You should add this functionality in the OO_UpdateShell file. We shouldnt be adding this functionality at low level functions. look at update_versal_SC in OO_UpdateBase file.
> 
> Hi Vamshi, if I understood correctly, David wanted the bar to show up for xbmgmt program -b shell, which funnels through OO_UpdateBase.cpp (e.g. `xbmgmt program -b shell -d 65:00 --image xilinx_vck5000_gen4x8_qdma_base_2`). I agree; I initially tried to put the bar in [OO_UpdateBase Line 70](https://github.com/Xilinx/XRT/blob/master/src/runtime_src/core/tools/xbmgmt2/OO_UpdateBase.cpp#L70) instead of the low-level flasher, but since there is extra output flushed to cout within the flashers, the bar will not clean up output properly. This resulted in some previous output being deleted instead of the bar itself once flashing was complete. In addition, the ProgressBar for update_versal_SC required a timeout, so BusyBar was chosen instead to provide similar information without a timeout. Please let me know your thoughts!

Hi Ryan,
BusyBar is a good choice, My main concern is about putting this code at low level, Cant we clean up the flashers code not to flush any output?

**Comment by rchane** [comment]
> Hi Ryan, BusyBar is a good choice, My main concern is about putting this code at low level, Cant we clean up the flashers code not to flush any output?

If the developer doesn't need the output from the flashers (they are "Info" lines), then I think cleaning up the two flashers' code to not flush any output works great! I would then edit flasher.cpp (one level up) to have the busybar for these two flashers. If I were to edit OO_UpdateBase as I originally intended, however, the other flashers have much more output flushed to cout (including error messages), and it might be too much overhead to account for them. Would this be alright?

**Comment by chvamshi-xilinx** [comment]
> > Hi Ryan, BusyBar is a good choice, My main concern is about putting this code at low level, Cant we clean up the flashers code not to flush any output?
> 
> If the developer doesn't need the output from the flashers (they are "Info" lines), then I think cleaning up the two flashers' code to not flush any output works great! I would then edit flasher.cpp (one level up) to have the busybar for these two flashers. If I were to edit OO_UpdateBase as I originally intended, however, the other flashers have much more output flushed to cout (including error messages), and it might be too much overhead to account for them. Would this be alright?

I get your point. I think, whatever you have is good then. Let me review. Can you please share the output in the description

**Comment by rchane** [comment]
Certainly, I'll put the output in the description shortly! Thank you, and my apologies for any unclear wording I had previously.

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
