### PR TITLE
Fixed the issue for Ubuntu OS

### PR DESCRIPTION
**Pull request by saifuddin-xilinx**
This is cherry picked from https://github.com/Xilinx/XRT/pull/5772

### CODE REVIEW

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please. Install test agent was down.

**Comment by dayeh-xilinx** [comment]
retest this please. Copied u30 test files.

**Pull request merged**
