### PR TITLE
CR-1120376 adding final writes of AIE status reports

### PR DESCRIPTION
**Pull request by pgschuey**
To ensure we capture every event that occurs on AIE tiles, we need to write the status reports as late as possible.

### CODE REVIEW

**Review by jvillarre — APPROVED** [review]

**Comment by pgschuey** [comment]
please retest

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by github.com fetch.

**Comment by kbhardwa-xilinx** [comment]
Please Retest

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error windows failed to mkdirs.

**Comment by pgschuey** [comment]
Please re-test. It looks it fails in Windows build, but the console log is empty.

**Comment by maxzhen** [comment]
retest this please - failed with windows build

**Comment by dayeh-xilinx** [comment]
retest this please - failed with centos repo error.

**Pull request merged**
