### PR TITLE
CR-1079673 XRT build failure with cmake 3.17 and boost 1.65.1

### PR DESCRIPTION
**Pull request by stsoe**
Fix code to work-around boost::process rdbuf() conversion error.
Add proper Boost version check to test if boost::process is available.

### CODE REVIEW

**Review by AShivangi — COMMENTED** [review]
Thanks for making these changes :)

**Review by rozumx — COMMENTED** [review]
Approve changes.

**Comment by keryell** [comment]
Curious to use a Boost from 2017 and a CMake from 2020 at the same time...
Why not just using modern software? :-)

**Comment by stsoe** [comment]
Hi @keryell   Unfortunately we have to support Ubuntu 16.04, 18.04, 20.04, ... Centos 7.x, Centos 8.x .  System libraries, including Boost and cmake, are what is default installed on these platforms.

**Comment by keryell** [comment]
Sure... But usually you have everything new or everything old... Here this is a strange cocktail...

**Pull request merged**
