### PR TITLE
Core tools support for RTEMS

### PR DESCRIPTION
**Pull request by kiwichris**
RTEMS is a single address space RTOS and does not support processes.

### CODE REVIEW

**Comment by keryell** [comment]
Just curious: how far do you plan to go with RTEMS?
Do you plan to interact with real FPGA hardware?

**Comment by kiwichris** [comment]
Fully functional port. This means AIE, PS and RTL all together.

I have `xbutil2` up to here:
```
RTEMS Shell on /dev/console. Use 'help' to list commands.
xrt [/] # xbutil2 examine
System Configuration
  OS Name              : RTEMS
  Release              : unreleased
  Version              : rtems-6.0.0 (AArch64/AArch64-LP64/xilinx_versal_lp64_vck190)
  Machine              : xilinx_versal_lp64_vck190
  CPU Cores            : 1
  Memory               : 759 MB
  Distribution         : Contemporary Software
  Model                : Versal

XRT
  Version              : 2.14
  Branch               : n/a
  Hash                 : n/a
  Hash Date            : n/a

Devices present
BDF             :  Shell  Platform UUID  Device ID  Device Ready*  
[0000:00:00.0]  :  edge   0x0            n/a        Yes            

* Devices that are not ready will have reduced functionality when using XRT tools
```
I am now working on the edge support for RTEMS. The `zocl` is OK but `sysfs` will require I update `zync_dev` to do those operations but via the driver's `ioctl` interface. There are a lot of blanks I am having to fill in to do this.

**Comment by stsoe** [comment]
@kiwichris Is this also a duplicate of #6676.  Looks like same code changes.  Can you please close the ones are dups and leave the one you want reviewed and merged?  Thanks!

**Comment by stsoe** [comment]
Close as duplicate of #6676

**Comment by keryell** [comment]
Ah, I see, this targets an SoC platform. Interesting!

**Pull request closed without merging**
