### PR TITLE
xbutil2: Add support for scan|query|dmatest sub commands

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Added changes in windowsXRT to work with scan, query and
dmatest sub commands of xbutil tool.

Resolve review comments for PR# 2499

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
This PR depends on XoclUser driver PR Xilinx/MS_XOCLUSER#13

**Comment by rajkumar-xilinx** [comment]
xbutil scan output on windows:

C:\Rajkumar\repos\27nov_raj_xrt\XRT\build>xbutil --override scan

System Configuration
OS Name       : Windows Server 2016 Datacenter Evaluation
Release       : 14393.rs1_release.161220-1747
Version       : 6.3
Machine       : x86_64
Glibc         : N/A
Distribution  : N/A
Now           : Mon Dec  2 17:16:23 2019

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version       : 2.4.0
Git Hash      : 2f8d1faf3de55dbde4f9ac1bad29a133c6d4673d
Git Branch    : 2dec_pr
Build Date    : 2019-12-02 16:49:03
XOCL          : N/A
XCLMGMT       : N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]: xilinx_u250_xdma_201830_2(ts=1560443408)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: Found total 1 card(s), 1 are usable.

**Comment by rajkumar-xilinx** [comment]
C:\Rajkumar\repos\27nov_raj_xrt\XRT\build>xbutil --override query
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS Name       : Windows Server 2016 Datacenter Evaluation
Release       : 14393.rs1_release.161220-1747
Version       : 6.3
Machine       : x86_64
Glibc         : N/A
Distribution  : N/A
Now           : Mon Dec  2 17:16:26 2019

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version       : 2.4.0
Git Hash      : 2f8d1faf3de55dbde4f9ac1bad29a133c6d4673d
Git Branch    : 2dec_pr
Build Date    : 2019-12-02 16:49:03
XOCL          : N/A
XCLMGMT       : N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compute Unit Status:
[0]: bandwidth1:kernel_1 @0x1800000     (state:TBD)
[1]: bandwidth2:kernel_2 @0x1810000     (state:TBD)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Memory Status:
Tag            Type         Temp(C)       Size (GB)       Mem Usage        BO count
bank0        MEM_DDR4             N/A              16               0 (MB)               0
bank1        MEM_DDR4             N/A              16               0 (MB)               0
bank2        MEM_DDR4             N/A              16               0 (MB)               0
bank3        MEM_DDR4             N/A              16               0 (MB)               0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shell                           FPGA                            IDCode
xilinx_u250_xdma_201830_2       xcu250-figd2104-2L-e            N/A
Vendor          Device          SubDevice       SubVendor       SerNum
4334            20485           14              4334            N/A
DDR size (MB)   DDR count       Clock0          Clock1          Clock2
16384           4               -1              -1              -1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rajkumar-xilinx** [comment]
xbutil dmatest output:

C:\Rajkumar\repos\27nov_raj_xrt\XRT\build>xbutil --override dmatest -b 1024
Total DDR size: 65536 MB
Reporting from mem_topology:
Memory regions:4
Data Validity & DMA Test on bank0:
Buffer Size: 1 MB
Host -> PCIe -> FPGA write bandwidth = 9168.66 MB/s
Host <- PCIe <- FPGA read bandwidth = 9976.45 MB/s
Data Validity & DMA Test on bank1:
Buffer Size: 1 MB
Host -> PCIe -> FPGA write bandwidth = 9248.78 MB/s
Host <- PCIe <- FPGA read bandwidth = 9972.95 MB/s
Data Validity & DMA Test on bank2:
Buffer Size: 1 MB
Host -> PCIe -> FPGA write bandwidth = 9322.16 MB/s
Host <- PCIe <- FPGA read bandwidth = 9977.13 MB/s
Data Validity & DMA Test on bank3:
Buffer Size: 1 MB
Host -> PCIe -> FPGA write bandwidth = 8927.38 MB/s
Host <- PCIe <- FPGA read bandwidth = 10027.8 MB/s

**Comment by rajkumar-xilinx** [comment]
>>>[Soren]A shim level function should work on an already open device handle. Who ever calls this function should make sure the device is open and pass the handle. If you are calling this function through a xrt_core::device object, then the device object has already opened the device so all you need is to pass the handle down.

Taken care of this now.

**Comment by rajkumar-xilinx** [comment]
Build pipeline error:

[zcu102_base]          except OSError:
[zcu102_base] PermissionError: [Errno 13] Permission denied: '/proj/petalinux/2020.1/petalinux-v2020.1_1030_1'
[zcu102_base] 
[zcu102_base] ERROR: Command execution failed: Traceback (most recent call last):
[zcu102_base]   File "/proj/petalinux/2020.1/petalinux-v2020.1_1201_1/tool/petalinux-v2020.1-final/components/yocto/source/aarch64/layers/core/bitbake/lib/bb/command.py", line 116, in runAsyncCommand
[zcu102_base]     commandmethod(self.cmds_async, self, options)

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by rajkumar-xilinx** [comment]
Fixed merge conflicts in PR# https://github.com/Xilinx/XRT/pull/2513 . So, closing this PR.

**Pull request closed without merging**
