### PR TITLE
Add concurrency feature to Mini Pipeline

### PR DESCRIPTION
**Pull request by eshwar-xilinx**
#### Problem solved by the commit
  Triggers build for only last commit in a PR
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
  A simple feature for Mini pipeline to prevent delay in runs
#### How problem was solved, alternative solutions (if any) and why they were rejected
 Concurrency tag was added to yml file
#### Risks (if any) associated the changes in the commit
  Low risk
#### Documentation impact (if any)
 No impact on documentation

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
Hi @eshwar-xilinx ,
Is your verification done on this change? shall we merge it into master?

**Comment by eshwar-xilinx** [comment]
Hi @chvamshi-xilinx
I wanted to check how priority is assigned when multiple PRs (each PR multiple commits) are present,
This scenario is yet to verify
we can merge it on monday

**Comment by eshwar-xilinx** [comment]
Hi @chvamshi-xilinx ,
I have verified the scenarios, this feature should work fine.
In each PR, it skips the extra commits and runs for the latest commit.
But the only downside is , github actions sends "run is cancelled" mail for each extra commit it skips.
As of now, github actions doesn't support suppressing only specific kind of mails. Either all notifications should be cancelled or all notifications will be enabled

**Comment by chvamshi-xilinx** [comment]
> Hi @chvamshi-xilinx , I have verified the scenarios, this feature should work fine. In each PR, it skips the extra commits and runs for the latest commit. But the only downside is , github actions sends "run is cancelled" mail for each extra commit it skips. As of now, github actions doesn't support suppressing only specific kind of mails. Either all notifications should be cancelled or all notifications will be enabled

Thanks @eshwar-xilinx for the trials and verification.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
Am closing this as things are working well without this support also. We can add this change if we see any issues with mini pipeline

**Pull request closed without merging**
