### PR TITLE
Various Cleanup of xbutil with xrt-smi, Help Menu Fix

### PR DESCRIPTION
**Pull request by rchane**
#### Problem solved by the commit
There were some mentions of xbutil in xrt-smi still, including in the help menu program description. In addition, `xrt-smi` and `xrt-smi --help` were throwing errors after printing the help menu.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Discovered while testing
#### How problem was solved, alternative solutions (if any) and why they were rejected
The aforementioned commands now only print the help menu without the error. Mentions of xbutil in output and some comments/scripts were replaced with xrt-smi, including xball script and nagios_plugin.sh.
#### Risks (if any) associated the changes in the commit
N/A
#### What has been tested and how, request additional testing if necessary
Tested on STX\MCDM.
```
C:\Users\rchane\Desktop\xrt>xrt-smi

DESCRIPTION: The Xilinx (R) Run Time - System Management Interface (xrt-smi) is a standalone
             command line utility that is included with the Xilinx Run Time (XRT) installation
             package. It includes multiple commands to identify and validate the installed card(s).

              This information can be used for both card administration and application debugging.

USAGE: xrt-smi[--help] [--version] [--verbose] [--batch] [--force] [command [commandArgs]]

AVAILABLE COMMANDS:
  configure  - Device and host configuration
  examine    - Status of the system and device
  validate   - Validates the basic shell acceleration functionality

OPTIONS:
  --help             - Help to use this application
  --version          - Report the version of XRT and its drivers
  --verbose          - Turn on verbosity
  --batch            - Enable batch mode (disables escape characters)
  --force            - When possible, force an operation

C:\Users\rchane\Desktop\xrt>xrt-smi --help

DESCRIPTION: The Xilinx (R) Run Time - System Management Interface (xrt-smi) is a standalone
             command line utility that is included with the Xilinx Run Time (XRT) installation
             package. It includes multiple commands to identify and validate the installed card(s).

              This information can be used for both card administration and application debugging.

USAGE: xrt-smi[--help] [--version] [--verbose] [--batch] [--force] [command [commandArgs]]

AVAILABLE COMMANDS:
  configure  - Device and host configuration
  examine    - Status of the system and device
  validate   - Validates the basic shell acceleration functionality

OPTIONS:
  --help             - Help to use this application
  --version          - Report the version of XRT and its drivers
  --verbose          - Turn on verbosity
  --batch            - Enable batch mode (disables escape characters)
  --force            - When possible, force an operation

C:\Users\rchane\Desktop\xrt>xrt-smi blah
ERROR: Unknown command: 'blah'

DESCRIPTION: The Xilinx (R) Run Time - System Management Interface (xrt-smi) is a standalone
             command line utility that is included with the Xilinx Run Time (XRT) installation
             package. It includes multiple commands to identify and validate the installed card(s).

              This information can be used for both card administration and application debugging.

USAGE: xrt-smi[--help] [--version] [--verbose] [--batch] [--force] [command [commandArgs]]

AVAILABLE COMMANDS:
  configure  - Device and host configuration
  examine    - Status of the system and device
  validate   - Validates the basic shell acceleration functionality

OPTIONS:
  --help             - Help to use this application
  --version          - Report the version of XRT and its drivers
  --verbose          - Turn on verbosity
  --batch            - Enable batch mode (disables escape characters)
  --force            - When possible, force an operation
ERROR: operation canceled
```
#### Documentation impact (if any)
N/A

### CODE REVIEW

**Review by AShivangi — APPROVED** [review]
This looks good! Did we already fix xbtop?

**Comment by rchane** [comment]
> This looks good! Did we already fix xbtop?

xbtop hasn't been edited yet.

**Comment by AShivangi** [comment]
> > This looks good! Did we already fix xbtop?
> 
> xbtop hasn't been edited yet.

I'll create a ticket for it!

**Review by stsoe — APPROVED** [review]

**Review by jvillarre — APPROVED** [review]
Change to message in profiling code base is good

**Review by chvamshi-xilinx — CHANGES_REQUESTED** [review]
Can you please make this data driven. 
If users are calling xbutil , we should print messages with "xbutil" string. 
If users are calling xrt-smi , we should print messages with "xrt-smi" string. 
After this change, Even if use calls "xbutil" we print messages with "xrt-smi" string.

**Comment by chvamshi-xilinx** [comment]
Merging for now as we have feature freeze tomorrow..

**Pull request merged**
