### PR TITLE
CR-1102321 system reboot with latest 2021.1 xrt (build from source 20…

### PR DESCRIPTION
**Pull request by xdavidz**
We should not put a mutex inside a interrupt context. Centos can check this issue better. 🔢

### CODE REVIEW

**Review by larry9523 — APPROVED** [review]
What was the mutex try to protect before? If we were protecting something (does not seem to be the case here), we may think of spink lock.

**Comment by xdavidz** [comment]
> What was the mutex try to protect before? If we were protecting something (does not seem to be the case here), we may think of spink lock.

I think we original thought these APIs (get/set) could be called from multiple routines. That's why we want to protect the mbr_status. But current situation is that only ert_user.c will call it inside irq_handle.

I will add a spinlock later.

**Review by mamin506 — CHANGES_REQUESTED** [review]
If the solution is to remove mbv_lock, this change haven't delete all of them. Like, "mutex_init(&mbv->mbv_lock);" in mailbox_versal_probe and "struct mutex mbv_lock;" in struct mailbox_versal.

Could we replace the lock by spinlock?

**Comment by xdavidz** [comment]
> If the solution is to remove mbv_lock, this change haven't delete all of them. Like, "mutex_init(&mbv->mbv_lock);" in mailbox_versal_probe and "struct mutex mbv_lock;" in struct mailbox_versal.
> 
> Could we replace the lock by spinlock?

Switched to spinlock. The original design was not for irq handle, we should enforce and protect it by using spinlock.

**Review by mamin506 — APPROVED** [review]

**Comment by xdavidz** [comment]
We don't need lock as of now, remove the lock for cleaner version.

**Review by chienwei-lan — APPROVED** [review]

**Pull request merged**
