### PR TITLE
xbmgmt: Add support for clock_scaling feature configuration

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Added support for configuring the clock_scaling feature parameters using xbmgmt tool.
Added sysfs nodes in xmc for reading power & temperature threshold values.
Below is the output of xbmgmt tool and clock_scaling sub command options.

# xbmgmt
Supported sub-commands are:
        clock - Change various clock frequency on the device
        **clock_scaling - Clock scaling feature configuration**
        config - Parse or update mailbox configuration
        flash - Update SC firmware or shell on the device
        help - Print out help message for a sub-command
        nifd - Access the NIFD debug IP to readback frames and offsets
        program - Download xclbin onto the device
        reset - Perform various flavors of reset on the device
        scan - List all detected mgmt PCIE functions
Run xbmgmt help <subcommand> for detailed help of each subcommand

root@amar-PowerEdge-T640:/home/rajkumar/xrt_raj_clone# xbmgmt clock_scaling
'clock_scaling' sub-command usage:
[--status]
[--card bdf]
[--set_target_power numeric]
[--set_target_temp numeric]
[--set_governor power|temp]
[--scaling_force_en 1|0]

### CODE REVIEW

**Comment by abalasa** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
Hi @maxzhen ,
Could you please elaborate on HWMON on Linux. All these values are used by CMC to perform clock-throttling. 
@sonals suggested updating these values using xbmgmt.

**Comment by maxzhen** [comment]
> 
> 
> Hi @maxzhen ,
> Could you please elaborate on HWMON on Linux. All these values are used by CMC to perform clock-throttling.
> @sonals suggested updating these values using xbmgmt.

HWMON is a framework supporting sensors in Linux. Drivers need to expose sysfs node following the standard: https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface. The, all these sensor values can be handled by Linux's standard tools, such as lm-sensors. The HWMON sysfs node interface also defined nodes for temp and power limit. It seems better to integrate into Linux's native sensor framework to get sensor monitoring functionality for free.

**Comment by rajkumar-xilinx** [comment]
> > Hi @maxzhen ,
> > Could you please elaborate on HWMON on Linux. All these values are used by CMC to perform clock-throttling.
> > @sonals suggested updating these values using xbmgmt.
> 
> HWMON is a framework supporting sensors in Linux. Drivers need to expose sysfs node following the standard: https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface. After that, all these sensor values can be handled by Linux's standard tools, such as lm-sensors. The HWMON sysfs node interface also defined nodes for temp and power limit. It seems better to integrate into Linux's native sensor framework to get sensor monitoring functionality for free.

Hi Max,
As part of pull request https://github.com/Xilinx/XRT/pull/1292, we received suggestions to configure the target power/temperature values of clock scaling feature through xbmgmt tool. These values are not sensor values, they are just target values needed by CMC firmware in clock scaling feature. CMC firmware will measure board power and compare it with these target values. We don't monitor these target values unlike board power.

**Comment by maxzhen** [comment]
The CMC's integration with HWMON is done recently and I discovered more recently that the HWMON framework also support setting limits for power and temp via sysfs nodes. You're adding code in xbmgmt to set limits for power and temp through sysfs nodes as well. So, it sounds like we should be able to leverage HWMON framework to do this so that you'll have less (not more) work to do. I understand that you were suggested to set the limits using xbmgmt before. But based on the evolving of CMC code, we now have a better choice. Let's move the discussion to email or feel free to call a meeting.

**Comment by maxzhen** [comment]
per the discussion in email w/ @rajkumar-xilinx , this PR is not needed. I'm closing it now.

**Pull request closed without merging**
