### PR TITLE
Fix CodeQL warnings

### PR DESCRIPTION
**Pull request by stsoe**
#### Problem solved by the commit
Fix some user space warnings per https://github.com/Xilinx/XRT/security

#### What has been tested and how, request additional testing if necessary
Compile

### CODE REVIEW

**Review by AShivangi — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by xilinxgitops** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please - infra

**Comment by abalasa** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please - hudson error whatever that is?

**Comment by stsoe** [comment]
retest this please - hudson error ???

**Pull request merged**
