### PR TITLE
Edge issue fix

### PR DESCRIPTION
**Pull request by saifuddin-xilinx**
#### Problem solved by the commit
 -- Edge driver crash after hw context integration 

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
 -- HW context integration introduce this issue 

#### How problem was solved, alternative solutions (if any) and why they were rejected
 -- Currently edge doesn't support hw context but there are some common codebase kds_core which need hw context support. 
 -- Added a legacy hw context (always 0) for zocl context.

### CODE REVIEW

**Comment by saifuddin-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]
Hope you verified multiple cases.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by saifuddin-xilinx** [comment]
retest this please

**Review by mamin506 — APPROVED** [review]

**Pull request merged**
