### PR TITLE
CR-1045783 xbutil2 bdf host report enhancement

### PR DESCRIPTION
**Pull request by dbenusov-xilinx**
#### Problem solved by the commit
This is the same as https://github.com/Xilinx/XRT/pull/6118 with brackets added around the BDF printout to preserve the pipeline script functionality when detecting the number of cards.
https://jira.xilinx.com/browse/CR-1045783
Its not clear in the help that this is the case, xbutil list does not educate the user on bdf.

#### How problem was solved, alternative solutions (if any) and why they were rejected

Add identifier field to output. Parse the device properties and format the output in a nice looking table.

#### Risks (if any) associated the changes in the commit
There is some code duplication going on in XBUtilities and ReportPlatform::getPropertyTree20202. This could be combined to reduce the amount of code but it is a little involved. Mainly include issues from the DSAInfo class being in xbmgmt2 and XBUtitilies being in common. This could unify what properties are present for each device and it could be useful. Let me know if you would like to see this change.

It would also be prudent to move some of the string based keys used in the get function to a central location. Let me know if that is a reasonable idea.

#### What has been tested and how, request additional testing if necessary
Manual Testing
Single Card (1RP)
```
dbenusov@xsjpranjal01:/proj/xsjhdstaff6/dbenusov/XRT$ xbutil examine
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-92-generic
  Version              : #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15696 MB
  Distribution         : Ubuntu 20.04 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.13.0
  Branch               : CR-1045783
  Hash                 : a916854a68f735837c6cdb93a4195479c9496582
  Hash Date            : 2022-02-02 08:14:06
  XOCL                 : 2.13.0, 79d89e5c0c97b582c696453aae9ea7f414bca332
  XCLMGMT              : 2.13.0, 79d89e5c0c97b582c696453aae9ea7f414bca332

Devices present
BDF             :  Shell                      Platform UUID  Device ID
[0000:02:00.1]  :  xilinx_u280_xdma_201920_3  0x5e278820     user(inst=128)
```
Pipeline script snippet single board
```
dbenusov@xsjpranjal01:/proj/xsjhdstaff6/dbenusov/XRT$ xbutil examine | grep -E '\[.+\]' | wc -l
1
```
Multiple Cards (2RP)
```
dbenusov@xsjsagarw50:/proj/xsjhdstaff6/dbenusov$ xbutil examine
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-96-generic
  Version              : #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15671 MB
  Distribution         : Ubuntu 20.04.1 LTS
  GLIBC                : 2.31
  Model                : Super Server

XRT
  Version              : 2.13.0
  Branch               : CR-1045783
  Hash                 : a916854a68f735837c6cdb93a4195479c9496582
  Hash Date            : 2022-02-02 08:14:06
  XOCL                 : 2.13.0, a1dfb3b2a3efe42fb0c59fdb9afe692403787561
  XCLMGMT              : 2.13.0, a1dfb3b2a3efe42fb0c59fdb9afe692403787561

Devices present
BDF             :  Shell                            Platform UUID                         Device ID
[0000:b3:00.1]  :  xilinx_u200_gen3x16_xdma_base_1  A2D4F3CF-5B7A-0B7B-70F9-DA589CB5B3CD  user(inst=130)
[0000:18:00.1]  :  xilinx_u30_gen3x4_base_2         6E7C97F7-949F-5106-3075-A77784C30A4B  user(inst=129)
[0000:17:00.1]  :  xilinx_u30_gen3x4_base_2         6E7C97F7-949F-5106-3075-A77784C30A4B  user(inst=128)
```
Pipeline script snippet multiple boards
```
dbenusov@xsjsagarw50:/proj/xsjhdstaff6/dbenusov$ xbutil examine | grep -E '\[.+\]' | wc -l
3
```

### CODE REVIEW

**Comment by AShivangi** [comment]
Thanks for filing this PR again. 
I believe the pipeline issue is that the script is screen-scraping to get the bdf. As a reminder, we do not commit to text output, but we do commit to json schema. The correct way to get bdf, or any info for that matter, should be retrieved from `xbmgmt examine --format json`

**Review by AShivangi — APPROVED** [review]

**Comment by maxzhen** [comment]
> Thanks for filing this PR again. I believe the pipeline issue is that the script is screen-scraping to get the bdf. As a reminder, we do not commit to text output, but we do commit to json schema. The correct way to get bdf, or any info for that matter, should be retrieved from `xbmgmt examine --format json`

Could you/Daniel file an SR to fix the pipeline script?

**Comment by AShivangi** [comment]
Filed: SR-927804 XRT pipeline should collect data from json and not screen-scrape

**Review by rozumx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by branching work.

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by github.com fetch.

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by windows role account lockout.

**Comment by kbhardwa-xilinx** [comment]
Please retest

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error windows failed to mkdirs.

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error windows build server offline.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
