### PR TITLE
Created a unit-test infrastructure that encapsulates each test

### PR DESCRIPTION
**Pull request by rozumx**
Features
--------
  1. Unit tests can now be executed within their own unique unit-test directory.
  2. Bash (and soon batch) scripts wrap the unit tests.  For example, tests can be executed outside of CMake.
  3. Unit test suite directories supported.
  4. Test outputs are caputured in their own log file.
  5. Unit test sources and respository files are referred to their original directory.  No copying done.

Additional Work Done
--------------------
  1. Updated xclbinutil to use the new test environment.
  2. Enhanced xclbinutil to honor the "quiet" option for all section status commands.
  3. Enhanced xclbintest with options to add the repository and the quiet option.
  4. Update xclbintest to use the repository path

### CODE REVIEW

**Review by stsoe — APPROVED** [review]
Looks good to me.  I suggest no camelCase filenames, but it's just a suggestion

**Review by AShivangi — APPROVED** [review]

**Comment by rozumx** [comment]
Missing build failure information.  When I click the on the "Details" button the following message appears:

`HTTP ERROR 404

Problem accessing /job/XBB/job/XRT/job/XRT_PR_Builds/7386/. Reason:

    Not Found`

**Comment by rozumx** [comment]
retest this please

**Comment by maxzhen** [comment]
will merge after u30 lock down is lifted.

**Pull request merged**
