### PR TITLE
Fix XRT installation dependency errors in SUSE

### PR DESCRIPTION
**Pull request by Himanshu-xilinx**
CR-1056073: Added lsb-release and removed redhat-lsb-core as XRT dependency in SUSE
CR-1056161: Fixed dkms version

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Pull request merged**
