### PR TITLE
Use minimum gcc9 for std::filesystem (RHEL8)

### PR DESCRIPTION
**Pull request by ManojTakasi**
#### Problem solved by the commit
Recent migration from Boost to std filesystem is causing build failures in XRT on RHEL 8 machines with GCC version 8.5. This PR fixes that issue. 
Additionally, a few checks were removed to make the driver code more generalized.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
This issue was discovered when I tested it locally.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Ensure that proper devtoolset is used on platforms (RHEL8) where default compiler lacks support for std::filesystem.

#### Risks (if any) associated the changes in the commit
NA

#### What has been tested and how, request additional testing if necessary
Tested xrt package creation and installation on RHEL 8.8 ,8.9 and RHEL 9.3 VM

#### Documentation impact (if any)
NA

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]
Looks good. Thank you

**Review by maxzhen — APPROVED** [review]

**Comment by stsoe** [comment]
Are we officially supporting platforms with ancient compilers?  Our daily builds definitely do not use gcc < 9.1.  Is it unreasonable to request RHEL users to move to a newer compiler, e.g. use a more recent devtoolset ?

**Comment by chvamshi-xilinx** [comment]
> Are we officially supporting platforms with ancient compilers? Our daily builds definitely do not use gcc < 9.1. Is it unreasonable to request RHEL users to move to a newer compiler, e.g. use a more recent devtoolset ?

This comes even in RHEL 8.9 where we have decent compiler version ( gcc 8.* ) , We need to provide stdc++fs manually in compilation.

**Comment by stsoe** [comment]
> This comes even in RHEL 8.9 where we have decent compiler version ( gcc 8.* ) , We need to provide stdc++fs manually in compilation.

gcc 8 is not a decent compiler :-).   Can we not fix xrtdeps to update devtoolset ?

**Comment by chvamshi-xilinx** [comment]
> > This comes even in RHEL 8.9 where we have decent compiler version ( gcc 8.* ) , We need to provide stdc++fs manually in compilation.
> 
> gcc 8 is not a decent compiler :-). Can we not fix xrtdeps to update devtoolset ?

Sure Soren. @ManojTakasi , lets add a devtoolset dependency for RHEL 8.* also.

**Comment by keryell** [comment]
> Sure Soren. @ManojTakasi , lets add a devtoolset dependency for RHEL 8.* also.

`also` → `instead`.

**Comment by chvamshi-xilinx** [comment]
> > Sure Soren. @ManojTakasi , lets add a devtoolset dependency for RHEL 8.* also.
> 
> `also` → `instead`.

Updated the comment. What I mean was "this dependency is there for RHEL 7.*, lets add same dependency for RHEL 8.* also :-)"

**Comment by ManojTakasi** [comment]
Thank you Soren for your suggestion. Sure Vamshi, I will create another PR with the required changes.

**Review by stsoe — APPROVED** [review]

**Review by maxzhen — APPROVED** [review]

**Review by haghilin — APPROVED** [review]

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
