### PR TITLE
XRT support Multi-slot solution for edge platform

### PR DESCRIPTION
**Pull request by saifuddin-xilinx**
Story:
VITIS-4756 : Architecting XRT to support Multi-slot solution

Feature Specifications:
https://confluence.xilinx.com/display/SPEC/Feature+Specifications+for+Multi+Slot+Support

Problem Statement:
We want to be able to support multiple slots for Versal/zynqMP devices. Where more than one slot will be active concurrently.

Solution:
We have modified ZOCL driver to support the multiple slot. 
In the zocl Following modules are changed:
1. Memory Manager
2. XCLBIN Load 
3. CU scheduling 
4. KDS 
5. Client Context 

Test : 
As multi slot platform is not available we have tested this solution with single slot platform only. 
Test covered till now : 
- Versal Hw
- Versal hw_emul

### CODE REVIEW

**Review by stsoe — CHANGES_REQUESTED** [review]
Please spend some time providing a thorough description explaining what was done.

**Comment by saifuddin-xilinx** [comment]
> Please spend some time providing a thorough description explaining what was done.

Please do not review this PR. It's just to check the build validation. Sorry Soren for not sharing the information earlier.

**Comment by stsoe** [comment]
> > Please spend some time providing a thorough description explaining what was done.
> 
> Please do not review this PR. It's just to check the build validation. Sorry Soren for not sharing the information earlier.

Thanks for adding the tag :-)

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please. Cancelled from queue to give way to PR#6159

**Comment by saifuddin-xilinx** [comment]
Created a new PR after rebase with XGQ 
https://github.com/Xilinx/XRT/pull/6160

**Pull request closed without merging**
