### PR TITLE
Coverity fixes in xmc driver

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Fix coverities CID 213479, CID 213478, CID 213477, CID 213475, CID 213473, CID 213472

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
Hi @houlz0507 , Can you please review p2p related change?
Is it fine to use "p2p_enable" sysfs node to display p2p_enabled status as part of xbutil query output?

**Comment by houlz0507** [comment]
> Hi @houlz0507 , Can you please review p2p related change?
> Is it fine to use "p2p_enable" sysfs node to display p2p_enabled status as part of xbutil query output?

Sorry, p2p_enable is not sufficient to be used here. check_p2p_config() returns not just 0 and 1 but different status. Some driver changes need to be made to avoid pci config space read.
Could you help me to understand why xbutil query can not read pci config space?

**Comment by rajkumar-xilinx** [comment]
> > Hi @houlz0507 , Can you please review p2p related change?
> > Is it fine to use "p2p_enable" sysfs node to display p2p_enabled status as part of xbutil query output?
> 
> Sorry, p2p_enable is not sufficient to be used here. check_p2p_config() returns not just 0 and 1 but different status. Some driver changes need to be made to avoid pci config space read.
> Could you help me to understand why xbutil query can not read pci config space?

I will start a mail thread to discuss about p2p config reads during xbutil query related CR. So, removed p2p related changes from this PR. Let coverity fixes go in this PR as they are not dependent on p2p.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please

**Pull request merged**
