### PR TITLE
2018.2 xdf

### PR DESCRIPTION
**Pull request by stsoe**
Merging 2018.2_XDF to master

### CODE REVIEW

**Comment by stsoe** [comment]
Max, Ryan, Sonal, please review and make sure these 2018.2_XDF changes are supposed to go to master.

**Comment by stsoe** [comment]
Please check 28efc16.  Who is "cloud user"?

**Comment by stsoe** [comment]
Max.  The merge doesn't build.  Please check the pipeline build log and search for xbutil errors.
http://xcoengvm229019:8080/job/XBB/job/XRT/job/XRT_PR_Builds/15/consoleFull

**Comment by rradjabi** [comment]
> Please check [28efc16](https://github.com/Xilinx/XRT/commit/28efc16840785b55fd1efc9a71b627d0ba050659). Who is "cloud user"?

@stsoe Cloud User is my commit while developing from F1. I don't know why it does that.


> Max. The merge doesn't build. Please check the pipeline build log and search for xbutil errors.
http://xcoengvm229019:8080/job/XBB/job/XRT/job/XRT_PR_Builds/15/consoleFull

@maxzhen looks like this is the recent refactor of xcldev::pci_device_scanner to device::...., it looks like it's incomplete.

**Comment by maxzhen** [comment]
> 
> 
> > Please check [28efc16](https://github.com/Xilinx/XRT/commit/28efc16840785b55fd1efc9a71b627d0ba050659). Who is "cloud user"?
> 
> @stsoe Cloud User is my commit while developing from F1. I don't know why it does that.
> 
> > Max. The merge doesn't build. Please check the pipeline build log and search for xbutil errors.
> > http://xcoengvm229019:8080/job/XBB/job/XRT/job/XRT_PR_Builds/15/consoleFull
> 
> @maxzhen looks like this is the recent refactor of xcldev::pci_device_scanner to device::...., it looks like it's incomplete.

Soren's PR included xbutil top fix, which can't be merged into master due to the pcie scanner refactor change. We should exclude it from list of commits.

**Pull request closed without merging**
