### PR TITLE
Adds '-assumeyes' option to xrtdeps.sh

### LINKED ISSUE #529: Add option to force install in xrtdeps.sh
Non-interactive shells need the option to force install of packages in xrtdeps.sh. This is an issue for AWS F1 developer flow, since xrtdeps.sh will be called from sdaccel_setup.sh, and needs to confirm install for all packages by default.

### PR DESCRIPTION
**Pull request by rradjabi**
This is needed for AWS and should be a part of the next Release Candidate for 2018.2.

Fixes #529

### CODE REVIEW

**Comment by stsoe** [comment]
I prefered-force  :-)

**Comment by hcneema** [comment]
please retest

**Comment by abalasa** [comment]
retest this please

**Comment by sonals** [comment]
Please add support for apt for deb packages as well.

**Comment by rradjabi** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by stsoe** [comment]
Seems obsolete.  Can we close?

**Comment by rradjabi** [comment]
Closing.

**Pull request closed without merging**
