### PR TITLE
rename continuous_read_trace to continuous_trace

### PR DESCRIPTION
**Pull request by hackwa**
Also, turn off device trace when timeline file is off

### CODE REVIEW

**Comment by hackwa** [comment]
I have removed get_hal profile. Will make that change in another PR. All the sprite tests have been updated to use "continuous_trace" so please check this in @jvillarre

**Comment by hackwa** [comment]
retest this please

**Comment by hackwa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
