### PR TITLE
XRT OS Support for RHEl 8.8 and 9.2

### PR DESCRIPTION
**Pull request by ManojTakasi**
#### Problem solved by the commit
Providing XRT support for RHEl 8.8 and 9.2.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
NA
#### How problem was solved, alternative solutions (if any) and why they were rejected
By adding appropiate checks in the xocl_drv.h file and ulite.c file

#### Risks (if any) associated the changes in the commit
Low
#### What has been tested and how, request additional testing if necessary
Tested xrt package creation and installation on RHEL 8.8 and RHEL 9.2 VM

#### Documentation impact (if any)
NA

### CODE REVIEW

**Review by maxzhen — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
add to whitelist

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by manikandan-xilinx** [comment]
retest this please.

**Pull request merged**
