### PR TITLE
CR-1125036 CR-1125031 hwmon_sdm: support reading sensor unit_type & threshold values through sysfs nodes

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Added changes in hwmon_sdm driver to report sensor unit types, threshold values like upper_warning, upper_critical, upper_fatal, lower_warning, lower_critical and lower fatal readings through hwmon sysfs nodes. These new sysfs nodes will only be created if the threshold values are present for any sensor and registered them with hwmon driver.
Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

#### Problem solved by the commit
CR-1125036 & CR-1125031: report sensor unit type and threshold values also if they are available.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
CR-1125036 & CR-1125031
#### How problem was solved, alternative solutions (if any) and why they were rejected
Added changes in hwmon_sdm driver in XRT
#### Risks (if any) associated the changes in the commit
NA
#### What has been tested and how, request additional testing if necessary
reading newly added hwmon sysfs nodes
#### Documentation impact (if any)
NA

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
Verified it on vck5000 setup and here is the output.
image

**Review by chvamshi-xilinx — APPROVED** [review]
Tool changes would be submitted in next PR?

**Comment by rajkumar-xilinx** [comment]
> Tool changes would be submitted in next PR?

Hi Vamshi, thanks for the review, I will discuss with Stephen regd the tool level changes and then will add new PR based on the outcome.

**Comment by rajkumar-xilinx** [comment]
Hi @maxzhen , please review this PR and let me know, thank you.

**Review by chvamshi-xilinx — APPROVED** [review]
Hoping, You will use this units field in tools to show the units of each type.

**Comment by rajkumar-xilinx** [comment]
> Hoping, You will use this units field in tools to show the units of each type.

Yes Vamshi, that is the plan actually, hence added unit type change also into this PR. 
I will discuss with Stephen about tool level changes for the below 2 requests.
1. sensor unit types info - https://jira.xilinx.com/browse/CR-1125036 
2. sensor threshold info - https://jira.xilinx.com/browse/CR-1125031

**Comment by chvamshi-xilinx** [comment]
> > Hoping, You will use this units field in tools to show the units of each type.
> 
> Yes Vamshi, that is the plan actually, hence added unit type change also into this PR. I will discuss with Stephen about tool level changes for the below 2 requests.
> 
> 1. sensor unit types info - https://jira.xilinx.com/browse/CR-1125036
> 2. sensor threshold info - https://jira.xilinx.com/browse/CR-1125031

Thanks Raj

**Pull request merged**
