### PR TITLE
CR-1161216 - Always enable GCQ's interrupt to allow compatibility between GCQ v1 and v2

### PR DESCRIPTION
**Pull request by jeffli-xilinx**
Updated xgq_impl.h to always write 1 to GCQ's interrupt enable bit to address CR-1161216.
This is due to default GCQ v2 interrupt enable is set to 0.

#### Problem solved by the commit
V70 base3 platform switches to GCQ v2 which has interrupt disabled by default.
Therefore we need to write 1 to enable GCQ interrupts for the default operation with interrupts enabled for GCQ v1 and v2.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Change in behavior from GCQ v1 to GCQ v2

#### How problem was solved, alternative solutions (if any) and why they were rejected
Always write 1 to enable interrupt for XRT operations

#### What has been tested and how, request additional testing if necessary
v70 base3 platform

#### Documentation impact (if any)
None

### CODE REVIEW

**Review by mamin506 — APPROVED** [review]
Look good to me. We just want to enable interrupt on XGQ/GCQ. :)
Since this is change xgq_init() and xgq_fini(), add David and he needs to know this change for VMR.

**Review by xdavidz — APPROVED** [review]

**Review by maxzhen — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
