### PR TITLE
[OS] missing condition for RHEL 8.9

### PR DESCRIPTION
**Pull request by SihaoLiu**
#### Problem solved by the commit
Under the RHEL 8.9 version, using the official rpm package will lead to XOCL compilation problem because the package contains N/A condition for RHEL 8.9, which will lead to compilation error

This PR is simple, just add RHEL 8.9 case will solve the problem.

### CODE REVIEW

**Comment by SihaoLiu** [comment]
This PR is very similar to https://github.com/Xilinx/XRT/pull/7655, to reproduce it, just try to install the official package under any RHEL 8.9, it will lead to a XOCL compilation error.

**Review by maxzhen — APPROVED** [review]

**Comment by SihaoLiu** [comment]
Hi, just want to put a note here that anyone working under RHEL 8.9 that follow the official website as below will not install the XRT successfully, please back port this to public download rpm package
image

**Comment by maxzhen** [comment]
> Hi, just want to put a note here that anyone working under RHEL 8.9 that follow the official website as below will not install the XRT successfully, please back port this to public download rpm package image

Not sure if this is doable. @chvamshi-xilinx ?

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
ok to test

**Comment by chvamshi-xilinx** [comment]
retest this please
Emulation failures not related to this PR

**Pull request merged**
