### PR TITLE
CR-1125301 remove legacy xbutil/xbmgmt tools

### PR DESCRIPTION
**Pull request by AShivangi**
#### Problem solved by the commit
Remove legacy tool support from the wrapper script. 
Next PR will address removing the xbutil/xbmgmt directories

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Locally

#### Documentation impact (if any)
None

### CODE REVIEW

**Review by rozumx — APPROVED** [review]
Thank you for taking this first step to remove the legacy code.  

After the pull request has been in the system for a couple of days, we can then remove the legacy code.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
