### PR TITLE
CR-1145449_Freq Scaling Tolerance Check Implementation

### PR DESCRIPTION
**Pull request by prapulkrishnamurthy**
Signed-off-by: prapulkrishnamurthy <prapulk@xilinx.com>

#### Problem solved by the commit
Implementation to check the tolerance 
Min Max is not checked as Req Freq is chosen Max directly from topology.

#### How problem was solved, alternative solutions (if any) and why they were rejected
set_and_verify_freq API is implemented in reference to icap older code.

#### Risks (if any) associated the changes in the commit
Edge case is not handled which needs to be addressed.

#### What has been tested and how, request additional testing if necessary
It is not tested

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by xdavidz — CHANGES_REQUESTED** [review]
As we discussed yesterday, please follow the instruction in the CR and clean up this PR.

```
for check tolerance, please look at code from 2022.2 or master : "core/pcie/driver/linux/xocl/subdev/clock_wiz.c"

1. how do we change the clock
flow 1.1 
    user -> ioctl -> xocl_reclock (xocl:pf1) ->mailbox-> XCL_MAILBOX_REQ_RECLOCK (xclmgmt:pf0)
    -> clock_wiz_scaling_by_request -> set_and_verify_freqs
    1.1.1 set_freq
    1.1.2 check tolerance
flow 1.2 
     user -> download xclbin -> mailbox -> __icap_download_bitstream_mgmt(xclmgmt:pf0) -> __icap_xclbin_download -> icap_refresh_clock_freq -> axlf_set_freqscaling -> xocl_clock_freq_scaling_by_topo
     -> clock_wiz_scaling_by_request -> set_and_verify_freqs (operate on registers)
flow 1.3
     user -> .... -> xclbin download -> xocl_xgq_freq_scaling_by_topo -> 
     -> xgq_freq_scaling_by_topo -> -> set_and_verify_freqs is missing, we only call xgq_freq_scaling
     1.3.1 set_freq (xgq_freq_scaling) -> VMR -> VMR will call registers
     1.3.2 check tolerance
```

**Review by xdavidz — CHANGES_REQUESTED** [review]
Please update this PR and let me know when I can review it.

**Comment by xdavidz** [comment]
obsolated

**Pull request closed without merging**
