### PR TITLE
update to 2019.2 branch

### PR DESCRIPTION
**Pull request by sivarajeshjarugula**
updated the script to run for 2019.2
Signed-off-by: Siva Rajesh Jarugula <sivaraj@xilinx.com>

### CODE REVIEW

**Comment by sivarajeshjarugula** [comment]
updated the script to run for 2019.2

**Comment by maxzhen** [comment]
please resolve conflict.

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
