### PR TITLE
Add API to assign arguments from a void* + size_t

### PR DESCRIPTION
**Pull request by Ralender**
Expose a type-erased API to assign arguments.

### CODE REVIEW

**Review by stsoe — COMMENTED** [review]
@Ralender Why would we want this API to be exposed?
It is private on purpose, so as to force usage through compile time types.

**Comment by Ralender** [comment]
> @Ralender Why would we want this API to be exposed? It is private on purpose, so as to force usage through compile time types.

I need this because I am integrating XRT into a framework that already transforms a scalar argument into a void* + size because it is pretty generic.

**Comment by keryell** [comment]
@Ralender Perhaps you could add in the function comments that, when possible, the type-safe API taking normal types should be used instead of the `void*` one. This is to address some internal discussion with @stsoe.

**Comment by stsoe** [comment]
I understand the need.   Can we move these two functions under a public section immediately above the private section *and* not document this functions other than
`// Use at own risk, prefer documented type-safe arguments`
I really would prefer for these functions not to show up in the public generated documentation.

**Comment by stsoe** [comment]
ok to test

**Review by stsoe — APPROVED** [review]

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
