### PR TITLE
cl_ext.h should work on MPSoC, the same as on the PCIe case

### PR DESCRIPTION
**Pull request by mamin506**
On the XRT of a PCIe device flow, user include "CL/cl_ext.h" to get Xilinx OpenCL extensions. On the XRT for embedded platform, let's install XRT header files in /usr/include/xrt/ directory. This can meet Linux standard installation path and flexible for us to add Xilinx extensions.

This has impact to user's application:
When cross-compiling embedded host application, the **include path should be $SYSROOT/usr/include/xrt**.
In a makefile the compiler command would include "-I${SYSROOT}/usr/include/xrt/".

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by keryell** [comment]
Or since the CL program is Xilinx-specific anyway, the user could change the source program to:
```
#include "xrt/CL/cl_ext.h"
```
?

**Comment by mamin506** [comment]
> Or since the CL program is Xilinx-specific anyway, the user could change the source program to:
> 
> ```
> #include "xrt/CL/cl_ext.h"
> ```

@keryell We have "CL/cl_ext_xilinx.h" for Xilinx-specific APIs. We also has a Xilinx "CL/cl_ext.h". 
For PCIe case, user include CL/cl_ext.h.
This PR is to make the same X86 host application could seamless port to MPSoC.

**Comment by mamin506** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
