### PR TITLE
CR-1150767 Document how to enable platform clock throttling/shutdown via xrt

### PR DESCRIPTION
**Pull request by rchane**
#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1150767 Documentation is needed for CTS configuration using .ini in xbmgmt configure
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
CTS documentation needed to be updated. In addition, the cmc report was removed from xbutil docs as done in https://jira.xilinx.com/browse/CR-1135808.
#### How problem was solved, alternative solutions (if any) and why they were rejected
CTS configuration examples were added to the documentation.
#### Risks (if any) associated the changes in the commit
N/A
#### What has been tested and how, request additional testing if necessary
N/A
#### Documentation impact (if any)
This is a documentation change.

Xbmgmt Configure:
Xbmgmt Configure Docs
Updated Example for Xbmgmt Dump:
Xbmgmt Dump Docs Examples

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by rajkumar-xilinx** [comment]
Hi @rchane 
.ini input file will be used in configuring the clock throttling settings as well. Please check below pages for reference on .ini file content & command to update the clock throttling settings.
https://github.com/Xilinx/XRT/pull/7184
https://confluence.xilinx.com/display/~rajkumar/VCK5000+clock+throttling+feature+in+XRT#VCK5000clockthrottlingfeatureinXRT-ClockscalingverificationusingXRTtools
So, please review the commands and update the PR. Thank you.

**Comment by rchane** [comment]
Hello @rajkumar-xilinx, I have updated the PR with info on using the .ini file to edit clock throttling settings. Please let me know if what I have added is sufficient!

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by rajkumar-xilinx** [comment]
Hi @rchane 
Is it possible to use same names in .ini file and in configure command? For example enabling clock throttling:

xbmgmt configure --device <bdf> --clk_throttle true

.ini content with same name instead of throttling_enabled.

clk_throttle=true

**Comment by chvamshi-xilinx** [comment]
Hi @rchane / @rajkumar-xilinx ,
Dont document the direct options in xbmgmt configure --clk_throttle/--ct* etc ..
Document the options only thru ini. It is going to be confusing for users if we provide two ways.. Let the direct options in hidden options only for internal use.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Review by rajkumar-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
retest this please

**Review by uday610 — APPROVED** [review]

**Pull request merged**
