### PR TITLE
CR-1105379 enforce --legacy for "all" old generation xbutil/xbmgmt subcommands

### PR DESCRIPTION
**Pull request by AShivangi**

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. boardfarm test failed. try again.

**Comment by AShivangi** [comment]
It is ok for board farm tests to fail as of now. This PR enforces --legacy for all commands and it won't pass unless all the board farm scripts have incorporated the changes

**Review by rozumx — CHANGES_REQUESTED** [review]
The description states that this change is for both xbutil and xbmgmt.  The changes in this PR is for only xbutil.  By chance, is there a file missing?

As stated in the comments, this PR will not pass until the board farm completes updating their scripts.   This would be a great test case script for the board farm to validate that indeed correct operations.

**Review by rozumx — APPROVED** [review]
Looks good. 

It is always nice to remove code :^).

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by AShivangi** [comment]
retest this please

**Comment by AShivangi** [comment]
retest this please

**Comment by AShivangi** [comment]
retest this please

**Pull request merged**
