### PR TITLE
Fix XRT test 15_buffer_size, Remove XRT test 101_cdma , Update Makefile with removal of test 101_cdma

### PR DESCRIPTION
**Pull request by thuyp2018**
This PR is created with these commits
Fix XRT test 15_buffer_size
Remove XRT test 101_cdma per Soren's request
Update Makefile with removal of test 101_cdma

### CODE REVIEW

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by stsoe** [comment]
Thuy, please redo this PR for master.  We should remove 101_cdma, but not in 2018.2_XDF.

**Comment by stsoe** [comment]
Closing to be redone

**Pull request closed without merging**
