### PR TITLE
2022.2 pskernel backport and CR-1144274

### PR DESCRIPTION
**Pull request by jeffli-xilinx**
Update SCU subdevice name to SCU[n] instead of CU[n] (#7192)
    
    Fixes xclRegRW sysfs querry error
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    Co-authored-by: Jeff Lin <jeffylin@xilinx.com>
    (cherry picked from commit 69f3c07ac7dd58a794a5aa6849bdc75badbec37e)

    Disabled aied since its not needed for PS kernels (#7191)
    
    Fixes CR-1144274
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    Co-authored-by: Jeff Lin <jeffylin@xilinx.com>
    (cherry picked from commit 07f3b002f1b4c128123f01198a8264b628fa0776)

    Minor updates related to skd crash handling (#7154)
    
    * Added SKD crash handling between skd daemon and driver
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Removed debug printk from xocl_xgq.c
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Update related to PR comments
    Added kds_ert_table.h to translate between KDS command state and ERT command state.
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * More updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Updating data type for kds_ert_table and ert_kds_table
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Minor updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Updates according to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Updated status to enum kds_status types
    Minor updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Minor updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    Co-authored-by: Jeff Lin <jeffylin@xilinx.com>
    (cherry picked from commit 362d00c4b1d07c0df8ae64a4028d8d2608837e94)

    Skd crash handling (#7118)
    
    * Added SKD crash handling between skd daemon and driver
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Removed debug printk from xocl_xgq.c
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Update related to PR comments
    Added kds_ert_table.h to translate between KDS command state and ERT command state.
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * More updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Updating data type for kds_ert_table and ert_kds_table
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    * Minor updates related to PR comments
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    
    Signed-off-by: Jeff Lin <jeffylin@xilinx.com>
    Co-authored-by: Jeff Lin <jeffylin@xilinx.com>
    (cherry picked from commit d0b05e6035977948ffc8a595233bb80fedfec2bc)

### CODE REVIEW

**Review by stsoe — CHANGES_REQUESTED** [review]
Since this PR is not a cherry-pick, maybe add some details in the PR description.

**Comment by jeffli-xilinx** [comment]
@stsoe 
Actually these are all cherry-pick from master.
I had to resolve a conflict, so perhaps that's why its not showing up as cherry-pick?

**Review by stsoe — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
