### PR TITLE
CR-1111110 ASTeR TS21 - Validate result for a single test must always be explicitly reported

### PR DESCRIPTION
**Pull request by rchane**
#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1111110
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Test results for validate were unclear for users when running a single test in the event of a skipped test, as they would see "Validation Completed" with an exit code of 0 without any additional information about the test.
#### How problem was solved, alternative solutions (if any) and why they were rejected
The validate result for a single test will now always be reported, regardless if the test is skipped/failed/passed. A non-zero exit code will be returned and "Validation Failed" will be displayed for the skipped case now (in addition to the failed case), as requested. In addition, for consistency, if all tests of a multi-test run are skipped, a non-zero exit code will be returned and "Validation Failed" will be displayed (you would still need the `--verbose` flag to see the full details of why each test skipped). 
#### Risks (if any) associated the changes in the commit
This CR changes what the user can see when running `xbutil validate`.
#### What has been tested and how, request additional testing if necessary
Single test runs and multi-test runs were tested.
Example of skipped test.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r aie-pl -d 17:00
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : aie-pl 
    Description           : Run AIE PL test
    Details               : Verify xclbin not available or shell partition is not
                            programmed. Skipping validation.
    Test Status           : [SKIPPED]
-------------------------------------------------------------------------------
Validation failed
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ echo $?
1
```
Example of successful test.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r vcu -d 17:00
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : vcu 
    Description           : Run decoder test
    Xclbin                : /opt/xilinx/firmware/u30/gen3x4/base/test
    Testcase              : /opt/xilinx/xrt/test/xcl_vcu_test.exe
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ echo $?
0
```
Example of multi-test run with skipped test.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r vcu m2m -d 17:00
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : vcu 
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed. Please run the command '--verbose' option for more details
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ echo $?
0
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r vcu m2m -d 17:00 --verbose
Verbose: Enabling Verbosity
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : m2m 

    Description           : Run M2M test
    Details               : M2M is not available
    Test Status           : [SKIPPED]
-------------------------------------------------------------------------------
Test 2 [0000:17:00.1]     : vcu 
    Description           : Run decoder test
    Xclbin                : /opt/xilinx/firmware/u30/gen3x4/base/test
    Testcase              : /opt/xilinx/xrt/test/xcl_vcu_test.exe
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed
```
Example of multi-test run where all tests are skipped.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r p2p m2m -d 17:00
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Validation failed. Please run the command '--verbose' option for more details
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ echo $?
1
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil validate -r p2p m2m -d 17:00 --verbose
Verbose: Enabling Verbosity
Starting validation for 1 devices

Validate Device           : [0000:17:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 
    Platform ID           : 6E7C97F7-949F-5106-3075-A77784C30A4B
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : p2p 

    Description           : Run P2P test
    Details               : P2P config failed. P2P is not supported. Can't find P2P
                            BAR.
    Test Status           : [SKIPPED]
-------------------------------------------------------------------------------
Test 2 [0000:17:00.1]     : m2m 

    Description           : Run M2M test
    Details               : M2M is not available
    Test Status           : [SKIPPED]
-------------------------------------------------------------------------------
Validation failed
```
#### Documentation impact (if any)
None, I believe.

### CODE REVIEW

**Review by rozumx — CHANGES_REQUESTED** [review]
The underlying architecture is build around a data driven environment build around property trees.   In this case, the user will see a failure when they execute:
`xbutil validate -r aie-pl -d 17:00`
but if they look at the JSON file produced via the --output command,  it would not be obvious what is wrong.   

If I read this review correctly, I see the following:
- If 1 test was executed and skipped, a failure is produced.
- If 2 tests were executed and both were skipped, no failure is produced.

This looks inconsistent.    

For consistency, it might be better if we followed the following logic:
1. If NO tests were performed, then the command fails with a non-zero value.
2. If 1 or more tests were performed, then return false if any of the tests fail, else return true.

If you would like, I would be happy to discuss this with you in more detail.

**Comment by rchane** [comment]
Yes, that would be inconsistent; I agree! I'll go ahead and work on changing it to what you suggested. Thank you, Stephen!

**Comment by salindac** [comment]
retest this please

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
@rchane , this looks good now. Please rebase your branch which triggers a new pipeline build.

**Comment by rchane** [comment]
After discussion, the "singleton" variable should be renamed, but a more important issue is figuring out a cleaner/better solution (e.g. using metadata to know whether a test should be skipped or not and ONLY then returning an error/non-zero exit code if it is skipped). This current approach still works as desired on the surface level. Closing for now pending further deliberation.

**Pull request closed without merging**
