### PR TITLE
save mpd.conf for azure during pkg reinstall

### PR DESCRIPTION
**Pull request by xuhz**
azure pkg has a conf file saving the ip of the wireserver. User may edit this file saving its own IP address.

For pkg upgrade/downgrade/re-install, the content of the file need to be kept.

### CODE REVIEW

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by xuhz** [comment]
Since Azure production wireserver IP address will not change, we are not going to deliver the mpd.conf(which can specify wireserver IP) anymore in the xrt-azure pkg. Users debugging with standalone wireserver can edit /etc/mpd.conf to specify IP -- this file will not be touched during pkg install/reinstall/upgrade/downgrade etc

**Comment by sonals** [comment]
retest this please

**Pull request merged**
