### PR TITLE
platforms: Add zcu104_base and zc702_base to platfoms build

### PR DESCRIPTION
**Pull request by subhransu-xilinx**
Signed-off-by: Subhransu S. Prusty <subhransu.sekhar.prusty@xilinx.com>

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
ok to test

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
These platforms were enabled as part of https://github.com/Xilinx/XRT/pull/1920.  Please make any changes to the latest version of platforms.build.

**Comment by maxzhen** [comment]
Close based on @abalasa 's comment

**Pull request closed without merging**
