### PR TITLE
Suppress benign messages if command returns successful (weak-modules)

### PR DESCRIPTION
**Pull request by rradjabi**
RHEL/CentOS 'weak-modules' feature produces benign 'Error' messages from depmod and dkms. Instead of printing these to stdout, we are capturing them in a variable and only displaying if the call returns non-zero. This avoids confusion of seeing 'Error' when it is actually benign. 

Addresses JIRA CR-1031286

### CODE REVIEW

**Comment by stsoe** [comment]
ok to test

**Comment by rradjabi** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by keryell** [comment]
I am always scared when people try to hide stuff from me, specially when I have to use `sudo` to run *your* code on *my* computer and it might be a Trojan horse... :-)
Would it be safer to test for the existing installed modules and then just use the required commands to remove what has to be done?
If I do not understand correctly the problem, well, this code is not commented either and should not be open-sourced anyway... :-/
At least add a lot of comments explaining the issue and the solution.

**Comment by rradjabi** [comment]
@keryell Thanks for your feedback. I updated the title and description, as well as added comments to the block of code. I hope that makes sense now.

**Comment by keryell** [comment]
Thanks for the clarification in the script. Quite clearer now! :-)

**Comment by rradjabi** [comment]
Struggling to find a command that works on CentOS and Ubuntu. Closing for now.

**Pull request closed without merging**
