### PR TITLE
Use new xbutil commands to enable host memory

### PR DESCRIPTION
**Pull request by mariodruiz**
Addressing comments on #6276 

#### Problem solved by the commit

Update the documentation to use new xbutil commands

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

Documentation was referring to legacy tools

#### How problem was solved, alternative solutions (if any) and why they were rejected

Updated commands to new switches

#### Risks (if any) associated the changes in the commit

None

### CODE REVIEW

**Comment by uday610** [comment]
Thanks a lot @mariodruiz , I am reviewing it in a while!

**Comment by mariodruiz** [comment]
BTW, the commands in this page https://xilinx.github.io/XRT/master/html/cloud_vendor_support.html also need updating. However, I do not know what the new commands are, the migration guide does not cover this part.

**Comment by uday610** [comment]
@AShivangi , can you please review and check the output shown by >`xbutil examine -r pcie-info -d 0000:17:00.1` .  When I checked with master branch XRT the    `Enabled Host Memory`   is shown as a SIZE instead of a number that is shown from this PR update. So which should be correct and which one should be bug? Seems like there is a discrepancy between the last release and master branch.

**Comment by AShivangi** [comment]
@uday610, I am talking to @chienwei-lan about this and I'll have an update soon

**Comment by AShivangi** [comment]
Hi @uday610, there is no bug. Here is how the host mem works:
1. You can enable host-mem any time you want and it will be reflected in the report. So when an xclbin that supports HOST[0] is _not_ loaded and 1G host mem is enabled, the output would look like:
 ```
 Shared Host Memory   : 1G  
 Max Shared Host Memory : 0 Byte
 Enabled Host Memory  : 0 Byte
```
2. When you load an xclbin with the host mem support, the `Max Shared Host Mem` gets populated like:
 ```
 Shared Host Memory   : 1G  
 Max Shared Host Memory : 16 GB 
 Enabled Host Memory  : 0 Byte
```
3. Now when you run an application which exercises HOST[0], `Enabled Host Memory` is populated:
 ```
 Shared Host Memory   : 1G  
 Max Shared Host Memory : 16 GB 
 Enabled Host Memory  : 1G
```

**Review by uday610 — APPROVED** [review]

**Review by AShivangi — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
ok to test

**Pull request merged**
