### PR TITLE
Boost 1.80 for Windows

### PR DESCRIPTION
**Pull request by emenchen**
New script is modification of xrtdeps-win19.py, updated for Boost 1.80 and Visual Studio 2022.

### CODE REVIEW

**Comment by stsoe** [comment]
Add to whitelist

**Comment by stsoe** [comment]
ok to test

**Review by stsoe — COMMENTED** [review]
What is xrtdeps-win17-175.py for?   Maybe update the PR description so we have a record of what is changed / added and why.

**Comment by emenchen** [comment]
Sorry @stsoe . xrtdeps-win17-175.py should not have been included. git status showed it not in the publish, but in my multiple attempts to get this through, it may have been picked up inadvertently.

**Comment by stsoe** [comment]
Hi @emenchen Can you remove the stale file from the PR?

**Pull request merged**
