### PR TITLE
Create xrt/xrt.h

### PR DESCRIPTION
**Pull request by wilderfield**
Provide users with an aggregating header file.

This will allow users who are less familiar with xrt code base to quickly bring all of the APIs into their compilation unit.

#### Problem solved by the commit
Ease of Use Enhancement

### CODE REVIEW

**Comment by stsoe** [comment]
> I would prefer `xrt/xrt.h`.

Yes,  I agree.  Even as we have a deprecated include/xrt.h, having xrt/xrt.h does not conflict.  Do watch out for the include guard though.

**Comment by wilderfield** [comment]
> > I would prefer `xrt/xrt.h`.
> 
> Yes, I agree. Even as we have a deprecated include/xrt.h, having xrt/xrt.h does not conflict. Do watch out for the include guard though.
> 
> Personally, I hate these kind of include all buckets, I prefer include-what-you-use, but I know many like a mixed bag of useless stuff.

Would you prefer that I directly add xrt/xrt.h ?
Or do you prefer that I generate this header file at CMake config time by detecting all the header files in */include/xrt ?

The second approach would require no maintenance unless there is a repo restructure.

Once you provide guidance I’ll make new well formed PR.

**Comment by stsoe** [comment]
> Would you prefer that I directly add xrt/xrt.h ?
> Or do you prefer that I generate this header file at CMake config time by detecting all the header files in */include/xrt ?

I prefer explicitly added xrt/xrt.h,

**Comment by bryanloz-xilinx** [comment]
Please close this in favor of #7548

**Pull request closed without merging**
