### PR TITLE
XMA changes for DDR mapping to support HBM and xclbins with more kernels (2019.1)

### PR DESCRIPTION
**Pull request by hasansayani-xilinx**
Changing limits to handle more connections (eg. HBM, more kernels) & putting a place holder for MAX_REGS_PER_IP = 1, to take it into consideration in future
Changing a temporary struct variable to move from stack to heap to avoid causing stack smashing

### CODE REVIEW

**Comment by hasansayani-xilinx** [comment]
@sarab96 / @sonals , please can we have it reviewed and pulled it?

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
@sarab96 @hasansayani-xilinx do we need a fix for master?

**Comment by hasansayani-xilinx** [comment]
@maxzhen yes please. Do you want me to send a new PR for master branch or we can use 2019.1 ?

**Comment by maxzhen** [comment]
Please file a new PR for master.

**Pull request merged**
