### PR TITLE
AWS Component Installation & Pegasus Support

### PR DESCRIPTION
**Pull request by rradjabi**
Adds component installation for xrt-aws including libxrt_aws, awssak, and awsmgmt

### CODE REVIEW

**Comment by rradjabi** [comment]
@stsoe This may not work, i'm looking in the build pipeline console output and already see: 
```
14:57:58 [Build XRT and create RPM on Centos7.4] CMake Error at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
14:57:58 [Build XRT and create RPM on Centos7.4]   CMake 3.0.0 or higher is required.  You are running version 2.8.12.2
```

**Comment by abalasa** [comment]
retest this please

**Comment by sonals** [comment]
xrt-aws rpm should depend on xrt.rpm, not the other way round. @rradjabi  can you review the makefiles?

**Comment by rradjabi** [comment]
I will update the PR to make xrt-aws require xrt as a pre-requisite.

**Comment by rradjabi** [comment]
My latest change 8d86195 made the fix for RPM, but it isn't working for DEBIAN. I have not set the equivalent variable to set -Unspecified as the main component for Debian. That setting was set(CPACK_RPM_MAIN_COMPONENT "Unspecified). @stsoe can you test and find the equivalent setting for Debian?

**Comment by stsoe** [comment]
This PR is replaced by PR #656

**Comment by rradjabi** [comment]
Closing instead of #656

**Pull request closed without merging**
