### PR TITLE
fix xbutil validate failed issue on versal

### PR DESCRIPTION
**Pull request by mamin506**
#### Problem solved by the commit
xbutil validate failed on VCK5000 shell.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
@xdavidz reports this issue and provide instructions to reproduce.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Add XGQ resource, so that ert_ctrl subdev could be created.

#### Risks (if any) associated the changes in the commit
low

#### What has been tested and how, request additional testing if necessary
Test on vck5000

### CODE REVIEW

**Review by xdavidz — APPROVED** [review]

**Comment by xdavidz** [comment]
@mamin506 Tested and Passed.

**Review by maxzhen — APPROVED** [review]

**Comment by kbhardwa-xilinx** [comment]
Retest this please

**Comment by xdavidz** [comment]
@mamin506 can this be tested and merged ASAP? Otherwise, the TA of XRT cannot be used for testing. There are some people are waiting for the fix. I told them tomorrow but seems not going to happen.

**Comment by maxzhen** [comment]
Merging without waiting for pipeline.

**Pull request merged**
