### PR TITLE
CR-1107094: Adding xocl debug log to the run summary if enabled

### PR DESCRIPTION
**Pull request by jvillarre**
On the first XDP plugin creation, check if xocl.log is being generated and add it to the run summary.

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during Amazon Linux build. Looks like the Amazon site down. Try again.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by IshitaGhosh — APPROVED** [review]
Change looks good

**Pull request merged**
