### PR TITLE
Various Bug Fixes: Added global force option & fixed validate output

### PR DESCRIPTION
**Pull request by rozumx**
Work Done
---------
+ Added a global force option
+ Removed "false" exception regarding using the "-f" option (CR 1096041)
+ Added support to overwrite existing files with the --force option (CR 1096038)
+ Added temporary fix for to indicate work is being done when validation is be performed (CR 1096051)
+ Fixed previous line escape sequence issue (CR 1096046)

(cherry picked from commit 965ca291a4517cf0123463a16e2f5164c45e76c7)
(cherry picked from commit 34a9f9851c7a37ec52688585acc6ac7668430105)

### CODE REVIEW

**Comment by rozumx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please. Boardfarm team has made the fix to u30 validate package

**Comment by rozumx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please. Extracted test from today's sprite run. Try again.

**Comment by dayeh-xilinx** [comment]
retest this please. XRT pipeline is fixed and ready to go.

**Comment by xilinxgitops** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by rozumx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please. Previous build failed with boardfarm host cold reboot timeout. Try again.

**Pull request merged**
