### PR TITLE
xbmgmt: add an option to output flash scan data in json format

### PR DESCRIPTION
**Pull request by antonl1911**
Add the ability to output json for xbmgmt flash scan sub-command. Mutually exclusive with --verbose. Re used sensor_tree class.

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by antonl1911** [comment]
How can I access the build log?

**Comment by maxzhen** [comment]
the build failure is a known issue and we are working on it. will restart the test after it's fixed.

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
