### PR TITLE
Disable cuisr while debugging hang

### PR DESCRIPTION
**Pull request by stsoe**

### CODE REVIEW

**Comment by maxzhen** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by maxzhen** [comment]
@abalasa , there is no need to retest this PR until we have a root cause. We currently think that the ERT on the board pipeline is using is too old and is missing a critical bug fix to work without CUISR.

**Comment by abalasa** [comment]
retest this please

**Comment by stsoe** [comment]
While now passing, this PR requires that ERT firmware includes rev df87edfe8eb831f61e85c595e4ecbc489d933948 from Apr 17.  There are dsabins with older ERT.

**Pull request merged**
