### PR TITLE
XRT-845 New kds stress test

### PR DESCRIPTION
**Pull request by mamin506**
Use this PR to fix new kds, use kds mode, stress test issues.

### CODE REVIEW

**Review by maxzhen — APPROVED** [review]

**Comment by mamin506** [comment]
One issue I observed is when two applications are using different xclbin. One application is allocation bo and the other is in  downloading xclbin. This might lead to icap reader counter remain 1 and the download cannot finished.

This should be able to reproduce with mb_scheduler as well with proper application.

The new KDS remove dev_lock when open context, so this issue is exposed.
I would fix the open context issue in next commit.

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by mamin506** [comment]
The original 29 processes stress test can run 2 hours. Waiting for the 7 hours stress test result.

**Comment by dayeh-xilinx** [comment]
retest this please

**Review by maxzhen — APPROVED** [review]

**Review by chienwei-lan — APPROVED** [review]

**Pull request merged**
