### PR TITLE
 CR-1132359 Compute board power using cached voltage/current sensors

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Signed-off-by: Rajkumar Rampelli <rampelli@amd.com>

#### Problem solved by the commit
Occasionally ASTeR testing on the U250 card will show a discrepancy between calculated and reported power consumption.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
 CR-1132359
#### How problem was solved, alternative solutions (if any) and why they were rejected
Added changes in XMC driver for measuring the board power using cached voltage & current sensor readings wherever required to solve this issue.
#### Risks (if any) associated the changes in the commit
NA
#### What has been tested and how, request additional testing if necessary
xbutil examine -r all -d <BDF> -f json -o output_<i>.json
#### Documentation impact (if any)
NA

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
Validated it on u250 device.
$xbutil examine -r all -d <BDF> -f json -o output_<i>.json

Output is copied at below path
https://jira.xilinx.com/secure/attachment/470273/470273_cr132359_out.json

**Comment by rajkumar-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by rajkumar-xilinx** [comment]
Hi @stsoe & @rozumx , could you please review this PR and let me know your comments. Thank you.

**Review by stsoe — APPROVED** [review]

**Pull request merged**
