### PR TITLE
CR-1055109 Change DMESG entries for clock events to remove reference …

### PR DESCRIPTION
**Pull request by xdavidz**
small fix for health check

### CODE REVIEW

**Comment by david2011qq** [comment]
retest this please

**Comment by xdavidz** [comment]
retest this please

**Comment by xdavidz** [comment]
need a small tweak, please hold on a little bit

**Comment by xdavidz** [comment]
reset this please

**Comment by xdavidz** [comment]
> need a small tweak, please hold on a little bit

decide not to change the message, even though it is wordy, but meaningful. We would think about a longer term solution, like a debugfs subdev to handle all debugging related infra. It will provide more facilities rather than print lots info into the ring buffer dmesg and still not enough for some cases.

**Comment by xdavidz** [comment]
reset this please

**Comment by xdavidz** [comment]
reset this please

**Comment by xdavidz** [comment]
reset this please

**Comment by salindac** [comment]
retest this please

**Comment by xdavidz** [comment]
retest this please

**Comment by xdavidz** [comment]
retest this please

**Comment by xdavidz** [comment]
retest this please

**Pull request merged**
