### PR TITLE
Update dynamic regions to better display PL and PS kernels

### PR DESCRIPTION
**Pull request by dbenusov-xilinx**
#### Problem solved by the commit
Update the dynamic regions report to display hardware context ID. Prevent printout of compute unit headers if no units of that type are present

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
After the display discussion we determined we should add a hardware context ID to the dynamic report output. The code has been refactored to use the common table logic for displaying correlated data.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Added hardware context id into dynamic region report.

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Ubuntu 20.04 U55C
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov/XRT$ xbutil examine -d 04:00 -r dynamic-regions
WARNING: Unexpected xocl version (2.14.0) was found. Expected 2.15.0, to match XRT tools.

-------------------------------------------------
[0000:04:00.1] : xilinx_u55c_gen3x16_xdma_base_3
-------------------------------------------------
  Hardware Context ID: 0
    Xclbin UUID: E106E953-CF90-4024-E075-282D1A7D820B
    PL Compute Units
      Index  Name             Base Address  Usage  Status
      -----------------------------------------------------
      0      verify:verify_1  0x800000      4      (IDLE)
```

#### Documentation impact (if any)
None

### CODE REVIEW

**Review by stsoe — APPROVED** [review]
LGTM

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Pull request merged**
