### PR TITLE
Add drc to skip if xclbin is not found

### PR DESCRIPTION
**Pull request by AShivangi**
Missed a drc check to make sure that the xclbin path is valid

Sample output:
```
$ ./xbutil2_static validate -d -p test-xclbins/ -r "Bandwidth kernel" --verbose
Verbose: Enabling Verbosity
Verbose: Sub command: --path
Starting validation for 1 devices

Validate Device           : [0000:85:00.0]
    Platform              : xilinx_aws-vu9p-f1_dynamic-shell
    SC Version            : N/A
    Platform ID           : 0xabcd
-------------------------------------------------------------------------------
Test 1 [0000:85:00.0]     : Bandwidth kernel 
    Description           : Run 'bandwidth kernel' and check the throughput
    Test Status           : [SKIPPED]
-------------------------------------------------------------------------------
Validation completed
```

### CODE REVIEW

**Comment by AShivangi** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
