### PR TITLE
Use "NPU" in adaptor name for matching

### PR DESCRIPTION
**Pull request by kingtamamd**
"IPU" will change to "NPU" in adaptor name.

### CODE REVIEW

**Comment by kingtamamd** [comment]
Jason will have a corresponding PR for XRT-MCDM

**Review by stsoe — COMMENTED** [review]
Please note that this PR is a breaking change for XRT-MCDM.
Update of XRT in XRT-MCDM will have to make changes.

**Comment by stsoe** [comment]
ok to test

**Review by pranjalv-xilinx — APPROVED** [review]

**Comment by kingtamamd** [comment]
ok to test

**Comment by pranjalv-xilinx** [comment]
ok to test

**Comment by kingtamamd** [comment]
Required for https://gitenterprise.xilinx.com/XRT/XRT-MCDM/pull/500

**Pull request merged**
