### PR TITLE
zcu102/104_base: Add interconnects for hp ports with clk 300MHz

### PR DESCRIPTION
**Pull request by subhransu-xilinx**
FullPlatformBuild:Yes

Signed-off-by: Subhransu S. Prusty <subhransu.sekhar.prusty@xilinx.com>

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
ok to test

**Comment by abalasa** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
