### PR TITLE
enable zcu102 base DFX platform

### PR DESCRIPTION
**Pull request by sivarajeshjarugula**
Signed-off-by: Siva Rajesh Jarugula <sivaraj@xilinx.com>

### CODE REVIEW

**Comment by abalasa** [comment]
ok to test

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
