### PR TITLE
add several zocl sysfs nodes

### PR DESCRIPTION
**Pull request by larry9523**
1. Modify/add following zocl sysfs BIN attributes
    debug_ip_layout
    ip_layout
    connectivity
    mem_topology
2. Add following sysfs zocl regular attributes
    xclbinid
    kds_numcus
    kds_custat
    memstat
    memstat_raw
3. Fix a hang situations (when configured with interrupt mode but unsuccessfully configuring interrupt)
4. Enhance zocl driver probe to handle some failure situations.

### CODE REVIEW

**Comment by larry9523** [comment]
@mamin506 I can not select Reviewers. So please be noted to take a look at my changes. Thanks!

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
retest this please

**Comment by sonals** [comment]
retest this please

**Pull request merged**
