### PR TITLE
Add missing std vector header to fix xrt test 03_loopback host compilation issue

### PR DESCRIPTION
**Pull request by haeseunglee**
Add missing std vector header to fix xrt test 03_loopback host compilation issue

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
