### PR TITLE
CR-1122950, CR-1122952, & CR-1123262 Fix issues with AIE status & profile

### PR DESCRIPTION
**Pull request by pgschuey**
CR-1122950: ensure AIE status only writes valid files
CR-1122952: catch error messages before writing AIE status file
CR-1123262: add master/slave and stream ID to PLIO payload for AIE profiling
Additionally: change naming of 'shim' to 'interface tile'

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by pgschuey** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by pgschuey** [comment]
looks like failing test uses xilinx_u200_gen3x16_xdma_**1**_202110_1, which no longer exists. It should use xilinx_u200_gen3x16_xdma_**2**_202110_1

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by pgschuey** [comment]
@nishraptor

**Review by jvillarre — APPROVED** [review]

**Pull request merged**
