### PR TITLE
windowsXRT: Implement get_total_devices() in device_windows layer

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Implemented get_total_devices() in device_windows layer.
Output when 1 Xilinx device is connected to the system is:

    >xbutil --override scan
INFO: Found total 1 card(s), 0 are usable.

Also, added small fix in XBReport to display XRT info correctly.

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by stsoe** [comment]
The changes in this PR were merged as part of #2492 .
This PR is now obsolete.

**Comment by rajkumar-xilinx** [comment]
This change merged as part of https://github.com/Xilinx/XRT/pull/2492/

**Pull request closed without merging**
