### PR TITLE
Enabled control packet flow for next gen AIE devices

### PR DESCRIPTION
**Pull request by chvamshi-xilinx**
#### Problem solved by the commit
Enabled Control packet flow for next gen AIE devices. Currently this flow is supported only for AIE2 devices. 

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
This is a new feature. Enabled control packet flow for next gen AIE devices.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Patching control packet address in Instruction buffer, 
Created a new patching schema for new class of AIE devices,
Patching control packet with other buffers.

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Verified multiple cases with and without control packets

#### Documentation impact (if any)
None

### CODE REVIEW

**Comment by chvamshi-xilinx** [comment]
Thanks @rbramand-xilinx for providing initial changes.

**Review by stsoe — APPROVED** [review]
The functions in this file are getting much too long.
It may be time for a re-write.

**Comment by chvamshi-xilinx** [comment]
There is small spec change , need to update this PR after aiebu is ready.

**Comment by chvamshi-xilinx** [comment]
Infra issue on apu package build. It is not starting. Verified it locally.

**Pull request merged**
