### PR TITLE
Interrupt-based completion echo mode

### PR DESCRIPTION
**Pull request by chienwei-lan**

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Review by maxzhen — APPROVED** [review]
@chienwei-lan , what is the number in MB ERT echo mode v.s. non-echo mode? I'd expect the bottleneck is in MB ERT...

**Comment by chienwei-lan** [comment]
> @chienwei-lan , what is the number in MB ERT echo mode v.s. non-echo mode? I'd expect the bottleneck is in MB ERT...

echo mode: -t 3 -l64 -a 1000000 => ~1M
non-echo mode: -t 3 -l64 -a 1000000 => 150k

**Review by mamin506 — APPROVED** [review]

**Pull request merged**
