### PR TITLE
Fix for 1120119 : Seg fault in AIE design with aie_trace enabled

### PR DESCRIPTION
**Pull request by IshitaGhosh**
Seg fault in AIE design was due to access to deleted AieTracePlugin static object from Edge SHIM destructor to finish AIE device flush
This is fixed by introducing a status flag in AieTracePlugin and checking its validity before any callback.

### CODE REVIEW

**Review by jvillarre — APPROVED** [review]
Added guards look good to protect against the situation when the static destructors are called in the order where the shim destructor and callbacks happen after the plugin is destroyed.

**Review by pgschuey — APPROVED** [review]
Changes looks good. Great detective work.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by branching work.

**Comment by dayeh-xilinx** [comment]
retest this please. Infra error caused by github.com fetch.

**Pull request merged**
