### PR TITLE
CR-1082775 fix xclOpenIPInterruptNotify return issue

### PR DESCRIPTION
**Pull request by Himanshu-xilinx**

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Review by maxzhen — APPROVED** [review]

**Comment by maxzhen** [comment]
Approved by Sumit.

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
