### PR TITLE
CR-1067669 xbutil query should show the host_mem allocated for the devices, CR-1067670 xbutil query should show max host memory aperture possible for the card

### PR DESCRIPTION
**Pull request by chienwei-lan**
* Add allocated host memory size in xbutil query

     * Add Max host memory for CR-1067670 xbutil query

       should show max host memory aperture possible for the card

### CODE REVIEW

**Comment by chienwei-lan** [comment]
image

**Comment by maxzhen** [comment]
this also address CR-1067670, no?

**Comment by chienwei-lan** [comment]
yes, it solves CR-1067670 & CR-1067669

**Comment by maxzhen** [comment]
> 
> 
> yes, it solves CR-1067670 & CR-1067669

pls add both cr in your commit msg and pr subject, then.

**Pull request merged**
