### PR TITLE
Eliminate possibility of race condition in alloc kernel

### PR DESCRIPTION
**Pull request by jmouroux**
Signed-off-by: Jeffrey Mouroux <jmouroux@xilinx.com>

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by stsoe** [comment]
retest this please

**Comment by maxzhen** [comment]
@sarab96 could you take a look?

**Comment by sarab96** [comment]
Closing. Based on discussion not to allow changes in previous release

**Pull request closed without merging**
