### PR TITLE
xrt aie interface

### PR DESCRIPTION
**Pull request by larry9523**
This Pull Request introduce XRT AIE graph APIs including open, close, reset, run, suspend, resume, stop, etc. an AIE graph.

The APIs are exposed within libxrt_core.
The API header files are put into /usr/include/xrt/experimental/xrt_aie.h
This Pull Request is for edge only.

This add a new dependencies for building libxrt_core on edge that libxrt_core will now depend on libaiengien and libmetal

### CODE REVIEW

**Comment by larry9523** [comment]
The pipeline build passed. @mamin506 @chvamshi-xilinx, do you see any chance for this PR to break ZYNQ build by adding depencies on libaiengine and libmetal?

**Comment by mamin506** [comment]
> The pipeline build passed. @mamin506 @chvamshi-xilinx, do you see any chance for this PR to break ZYNQ build by adding depencies on libaiengine and libmetal?

The embedded pipeline is disabled. Please do not merge this.
I highly suspect if libaiengine is there in the BSP of ZynqMP/Zynq. This depends on petalinux default or BSP creator.

**Comment by chvamshi-xilinx** [comment]
> 
> 
> > The pipeline build passed. @mamin506 @chvamshi-xilinx, do you see any chance for this PR to break ZYNQ build by adding depencies on libaiengine and libmetal?
> 
> The embedded pipeline is disabled. Please do not merge this.
> I highly suspect if libaiengine is there in the BSP of ZynqMP/Zynq. This depends on petalinux default or BSP creator.

Hi @larry9523 , @mamin506 is correct. libaiengine is not enabled by default in Zynq/ZynqMP. Most likely, this is not enabled by default in versal aswell. I have checked vck190 sysroot and didn't find  this library
libmetal.so is enabled in both versal/zynqmp, but that is not enabled in Zynq.

**Comment by larry9523** [comment]
> @larry9523 @mamin506 Can we merge this PR but disable / condition building appropriately?

Hi @stsoe, discussed with @mamin506 , I will work out a way to conditionally build this piece of code shortly.

**Comment by larry9523** [comment]
@mamin506 I've added some condition in cmake to skipping building these code on edge platform (unless the following lines are added to the xrt_git.bbappend.
EXTRA_OECMAKE += "-DXRT_AIE_BUILD=yes"
TARGET_CXXFLAGS += "-DXRT_ENABLE_AIE"

DEPENDS += " libmetal libxaiengine"
RDEPENDS_${PN} += " libxaiengine"

**Comment by chvamshi-xilinx** [comment]
> 
> 
> @mamin506 I've added some condition in cmake to skipping building these code on edge platform (unless the following lines are added to the xrt_git.bbappend.
> EXTRA_OECMAKE += "-DXRT_AIE_BUILD=yes"
> TARGET_CXXFLAGS += "-DXRT_ENABLE_AIE"
> 
> DEPENDS += " libmetal libxaiengine"
> RDEPENDS_${PN} += " libxaiengine"

Looks Good.

**Pull request merged**
