### PR TITLE
Unify the host side code of new kds flow

### PR DESCRIPTION
**Pull request by chienwei-lan**

### CODE REVIEW

**Comment by xdavidz** [comment]
@chienwei-lan should you or me refactor the ert_versal code? Given it is almost copied from ert_user but has some versal specific handling.

**Comment by maxzhen** [comment]
> 
> 
> @chienwei-lan should you or me refactor the ert_versal code? Given it is almost copied from ert_user but has some versal specific handling.

can we leave versal one as a standalone subdev? how bad is it? @xdavidz

**Comment by xdavidz** [comment]
> > @chienwei-lan should you or me refactor the ert_versal code? Given it is almost copied from ert_user but has some versal specific handling.
> 
> can we leave versal one as a standalone subdev? how bad is it? @xdavidz

We can leave it alone. The bad thing is that 99% code in it is dup with ert_user.c. I can do the clean up.

**Comment by chienwei-lan** [comment]
> > > @chienwei-lan should you or me refactor the ert_versal code? Given it is almost copied from ert_user but has some versal specific handling.
> > 
> > 
> > can we leave versal one as a standalone subdev? how bad is it? @xdavidz
> 
> We can leave it alone. The bad thing is that 99% code in it is dup with ert_user.c. I can do the clean up.

we can have a discuss about how to integrate ert_versal too

**Pull request closed without merging**
