### PR TITLE
Add changes to build debian package using sbuild for embedded platforms

### PR DESCRIPTION
**Pull request by rbramand-xilinx**
> Added a script 'build_edge_deb.sh' to build deb packages for edge platforms
> Added debian directory inside build which provides control information for packaging
> This is approved way by canonical to create deb packages for upstreaming, the script added uses sbuild mechanism where it expects source code to be in archieve format(tar.xz in current flow)
> Host machine for running this script should have Ubuntu OS.
> The following Confluence page provides details of building and verification steps :
https://confluence.xilinx.com/display/DCG/XRT+packaging+using+debianization+for+embedded+platforms

### CODE REVIEW

**Review by stsoe — APPROVED** [review]
This is organized nicely, thanks!
I did not review the content.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please. Build failed on artifactory downloading. Loooks like a network glitch.

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
