### PR TITLE
Removed unused code files from XMA

### PR DESCRIPTION
**Pull request by vboggara-xilinx**

### CODE REVIEW

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please. Disabled PCIE emulation test on Ubuntu.

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by vboggara-xilinx** [comment]
Build pipeline passed, pl merge this PR.

**Review by sarab96 — APPROVED** [review]
Should be fine. Though don't know plan for next changes

**Pull request merged**
