### PR TITLE
CR-1126348 Align Sensor names with VMR

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

#### Problem solved by the commit
Matching sensor name with VMR update. Align sensor names as per https://confluence.xilinx.com/pages/viewpage.action?pageId=482822748 and also with https://github.com/Xilinx/VMR/pull/110 

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
CR-1126348

#### How problem was solved, alternative solutions (if any) and why they were rejected
Added changes in hwmon_sdm driver in XRT

#### Risks (if any) associated the changes in the commit
NA

#### What has been tested and how, request additional testing if necessary
$xbutil & xbmgmt examine report commands

#### Documentation impact (if any)
NA

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
VMR PR https://github.com/Xilinx/VMR/pull/110/files is under review. Once it is merged, I will remove "do not merge" tag.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
Hi @rajkumar-xilinx . VMR  change is merged now. is "do not merge" tag still valid?

**Review by chvamshi-xilinx — APPROVED** [review]
Hi @rajkumar-xilinx , 
Lets have an action item for 2022.2 on "how to avoid" changes in XRT when board info sensors are changed at VMR side. We need to close this with Stephen.

**Comment by xilinxgitops** [comment]
retest this please

**Pull request merged**
