### PR TITLE
error msg updated (#5983)

### PR DESCRIPTION
**Pull request by sarab96**
(cherry picked from commit 53e1e716f409d11a0d65365ff757d2b53ada9c21)

Backporting for U30 to 2021.1 branch

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during PCIE emulation test update.

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during PCIE emulation test update. Try again.

**Comment by dayeh-xilinx** [comment]
retest this please. Fixed PCIE emulation test issue.

**Comment by dayeh-xilinx** [comment]
retest this please. Fixed 2021.1 hardware test.

**Comment by xilinxgitops** [comment]
retest this please

**Review by maxzhen — APPROVED** [review]

**Pull request merged**
