### PR TITLE
Enabling kds_mode=1, by default on embedded of stress testing

### PR DESCRIPTION
**Pull request by Himanshu-xilinx**
* enabling common kds on embedded
* this is enabled to do stress testing on sprite

### CODE REVIEW

**Comment by larry9523** [comment]
This might break the AIE SPRITE tests until we have graph/aie context support in new kds

**Comment by dayeh-xilinx** [comment]
retest this please. Build failed due to emulation test issue.

**Comment by mamin506** [comment]
@Himanshu-xilinx, could you turn off new kds when "ert_hw" sub-device presented? I think this is needed.
Since PS ERT mode is still based on old KDS. We would implement something else that based on new KDS in next release.

Unless you tried enable new KDS on u30 and it still work.

**Comment by chvamshi-xilinx** [comment]
CLosing as this got merged from another PR

**Pull request closed without merging**
