### PR TITLE
CR-1101325: Improve profiling information on Native XRT profiling

### PR DESCRIPTION
**Pull request by jvillarre**
This change internally keeps track of xrt::bo::sync calls as either reads or writes and creates a more detailed trace view that explicitly shows when read/write transactions are happening on Native XRT applications.

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during Amazon Linux build. Looks like the Amazon site down. Try again.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Review by IshitaGhosh — APPROVED** [review]
Changes look good

**Pull request merged**
