### PR TITLE
CR-1155102 common: Fix reading sc & cmc controller info

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
#### Problem solved by the commit
SC & CMC controller info is missing on V70 board
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
CR-1155102
#### How problem was solved, alternative solutions (if any) and why they were rejected
Fixed reading SC controller & CMC controller information in XRT 
#### Risks (if any) associated the changes in the commit
NA
#### What has been tested and how, request additional testing if necessary
xbutil examine commands
#### Documentation impact (if any)
NA

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]
Looks good. Please rename the strings to some meaningful names 
for example: sn should be renamed to serial_number, oid should be renamed as oem_id etc

**Comment by rajkumar-xilinx** [comment]
> Looks good. Please rename the strings to some meaningful names for example: sn should be renamed to serial_number, oid should be renamed as oem_id etc

Hi @chvamshi-xilinx Thank you for reviewing the change. I have taken care of your suggestions and updated the PR. Please review it again. Thank you.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by rajkumar-xilinx** [comment]
retest this please

**Review by stsoe — CHANGES_REQUESTED** [review]
Can you refactor add_controller_info into a versal and non-versal function?
The deep nested try/catch confuses me.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by rajkumar-xilinx** [comment]
$xbutil examine --force --report platform --device 3b:00.1 --output /tmp/platform_after_validate_9mar2.json

-----------------------------------------------
[0000:3b:00.1] : xilinx_v70_gen5x8_qdma_base_3
-----------------------------------------------
Platform
  XSA Name               : xilinx_v70_gen5x8_qdma_base_3
  Platform UUID          : 95758332-1A62-070A-3070-7819EB5B7996
  FPGA Name              :
  JTAG ID Code           : 0x0
  DDR Size               : 0 Bytes
  DDR Count              : 0
  Revision               : B
  MFG Date               : 0xd737a7
  Mig Calibrated         : false
  P2P Status             : not supported

Successfully wrote the json file: /tmp/platform_after_validate_9mar2.json
$ cat /tmp/platform_after_validate_9mar2.json
{
    "schema_version": {
        "schema": "JSON",
        "creation_date": "Thu Mar  9 06:19:36 2023 GMT"
    },
    "devices": [
        {
            "interface_type": "pcie",
            "device_id": "0000:3b:00.1",
            "platforms": [
                {
                    "static_region": {
                        "vbnv": "xilinx_v70_gen5x8_qdma_base_3",
                        "logic_uuid": "95758332-1A62-070A-3070-7819EB5B7996",
                        "jtag_idcode": "0x0",
                        "fpga_name": ""
                    },
                    "off_chip_board_info": {
                        "ddr_size_bytes": "0",
                        "ddr_count": "0",
                        "revision": "B",
                        "mfg_date": "0xd737a7"
                    },
                    "status": {
                        "mig_calibrated": "false",
                        "p2p_status": "not supported"
                    },
                    "controller": {
                        "satellite_controller": {
                            "version": "8.5.2",
                            "expected_version": "8.5.2"
                        },
                        "card_mgmt_controller": {
                            "version": "",
                            "serial_number": "51171B22AK33",
                            "oem_id": "Xilinx"
                        }
                    },
                    "config": ""
                }
            ]
        }
    ]
}

**Review by stsoe — APPROVED** [review]
LGTM

**Comment by rajkumar-xilinx** [comment]
Thank you Soren for reviewing the PR.

Hi @rozumx 
Could you please review and let me know your comments. Thank you.

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
