### PR TITLE
CR-1142798 Platform UUID should be updated in xbmgmt examine report

### PR DESCRIPTION
**Pull request by dbenusov-xilinx**
#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1142798

Customers and developers are constantly confused by Platform UUID and Logic UUID.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected
Refactor `Platform UUID` to `Logic UUID`

#### Risks (if any) associated the changes in the commit
None.

#### What has been tested and how, request additional testing if necessary
Ubuntu 20.04 U55C
Host Report
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov$ xbutil examine
WARNING: Unexpected xocl version (2.14.0) was found. Expected 2.16.0, to match XRT tools.
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-126-generic
  Version              : #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 64007 MB
  Distribution         : Ubuntu 20.04.1 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.16.0
  Branch               : CR-1142798
  Hash                 : e45f7d71fd83ae8a4925f311c4bb313a14b43b77
  Hash Date            : 2023-04-20 14:01:55
  XOCL                 : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a
  XCLMGMT              : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a

Devices present
BDF             :  Shell                            Logic UUID                            Device ID       Device Ready*
-------------------------------------------------------------------------------------------------------------------------
[0000:04:00.1]  :  xilinx_u55c_gen3x16_xdma_base_3  97088961-FEAE-DA91-52A2-1D9DFD63CCEF  user(inst=129)  Yes


* Devices that are not ready will have reduced functionality when using XRT tools
```
xbutil Platform Report
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov$ xbutil examine -d 04:00
WARNING: Unexpected xocl version (2.14.0) was found. Expected 2.16.0, to match XRT tools.

-------------------------------------------------
[0000:04:00.1] : xilinx_u55c_gen3x16_xdma_base_3
-------------------------------------------------
Platform
  XSA Name               : xilinx_u55c_gen3x16_xdma_base_3
  Logic UUID             : 97088961-FEAE-DA91-52A2-1D9DFD63CCEF
  FPGA Name              :
  JTAG ID Code           : 0x14b7d093
  DDR Size               : 0 Bytes
  DDR Count              : 0
  Mig Calibrated         : true
  P2P Status             : disabled
  P2P IO space required  : 32 GB

Clocks
  DATA_CLK (Data)        : 300 MHz
  KERNEL_CLK (Kernel)    : 500 MHz
  hbm_aclk (System)      : 450 MHz

Mac Addresses            : 00:0A:35:0B:23:98
                         : 00:0A:35:0B:23:99
                         : 00:0A:35:0B:23:9A
                         : 00:0A:35:0B:23:9B
                         : 00:0A:35:0B:23:9C
                         : 00:0A:35:0B:23:9D
                         : 00:0A:35:0B:23:9E
                         : 00:0A:35:0B:23:9F

  Hardware Context ID: 0
    Xclbin UUID: E106E953-CF90-4024-E075-282D1A7D820B
    PL Compute Units
      Index  Name             Base Address  Usage  Status
      -----------------------------------------------------
      0      verify:verify_1  0x800000      1      (IDLE)
```
xbmgmt platform report
```
root@xsjdbenusov50:~# xbmgmt examine -d 04:00
WARNING: Unexpected xclmgmt version (2.14.0) was found. Expected 2.16.0, to match XRT tools.

-------------------------------------------------
[0000:04:00.0] : xilinx_u55c_gen3x16_xdma_base_3
-------------------------------------------------
Flash properties
  Type                 : spi
  Serial Number        : XFL10MFUZEB2

Device properties
  Type                 : u55c
  Name                 : ALVEO U55C PQ
  Config Mode          : 0x7
  Max Power            : 225W

Flashable partitions running on FPGA
  Platform             : xilinx_u55c_gen3x16_xdma_base_3
  SC Version           : 7.1.22
  Logic UUID           : 97088961-FEAE-DA91-52A2-1D9DFD63CCEF
  Interface UUID       : B7AC1ABE-1E3E-1CB6-86D5-A81232452676

Flashable partitions installed in system
  Platform             : xilinx_u55c_gen3x16_xdma_base_3
  SC Version           : 7.1.22
  Logic UUID           : 97088961-FEAE-DA91-52A2-1D9DFD63CCEF


  Mac Address          : 00:0A:35:0B:23:98
                       : 00:0A:35:0B:23:99
                       : 00:0A:35:0B:23:9A
                       : 00:0A:35:0B:23:9B
                       : 00:0A:35:0B:23:9C
                       : 00:0A:35:0B:23:9D
                       : 00:0A:35:0B:23:9E
                       : 00:0A:35:0B:23:9F
```
xbmgmt program
```
root@xsjdbenusov50:~# xbmgmt program -d 04:00 -b --force
WARNING: Unexpected xclmgmt version (2.14.0) was found. Expected 2.16.0, to match XRT tools.
----------------------------------------------------
Device : [0000:04:00.0]

Current Configuration
  Platform             : xilinx_u55c_gen3x16_xdma_base_3
  SC Version           : 7.1.22
  Platform ID          : 0x97088961feaeda91


Incoming Configuration
  Deployment File      : partition.xsabin
  Deployment Directory : /lib/firmware/xilinx/97088961feaeda9152a21d9dfd63ccef
  Size                 : 128,571,157 bytes
  Timestamp            : Wed Mar  8 11:44:14 2023

  Platform             : xilinx_u55c_gen3x16_xdma_base_3
  SC Version           : 7.1.22
  Logic UUID           : 97088961-FEAE-DA91-52A2-1D9DFD63CCEF
----------------------------------------------------
Actions to perform:
  [0000:04:00.0] : Program base (FLASH) image
  [0000:04:00.0] : Program Satellite Controller (SC) image
----------------------------------------------------
Are you sure you wish to proceed? [Y/n]: Y (Force override)

INFO: Forcing flashing of the Satellite Controller (SC) image (Force flag is set).
[0000:04:00.0] : Updating Satellite Controller (SC) firmware flash image
Stopping user function...
```
#### Documentation impact (if any)
None.

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dbenusov-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by chvamshi-xilinx — APPROVED** [review]

**Pull request merged**
