### PR TITLE
CR-1083074: changed linking from xdp to xdp_core

### PR DESCRIPTION
**Pull request by pgschuey**

### CODE REVIEW

**Comment by pgschuey** [comment]
Please re-test

**Comment by stsoe** [comment]
The overloaded va_list send method appears to be conflicting with the already present inline method.  This begs the question why we need the va_list one in the first place?  If you want / need it, at least rename it.

**Comment by dayeh-xilinx** [comment]
retest this please

**Review by jvillarre — APPROVED** [review]
Changes look good and set up the right dependencies for the plugin

**Comment by dayeh-xilinx** [comment]
retest this please

**Pull request merged**
