### PR TITLE
XRT-929 mgmt driver load apu bin automatically and XRT-930 enable UART lite for versal discovery

### PR DESCRIPTION
**Pull request by xdavidz**
#### Problem solved by the commit
enable 2 uart lite IP for versal discovery
enable auto load apu bin during driver attach, just like loading ert sched_xxx.bin

#### What has been tested and how, request additional testing if necessary
Tested with recent linux pkg build by build_edge.sh and pkgapu.sh

#### Documentation impact (if any)
https://confluence.xilinx.com/pages/viewpage.action?pageId=302345261#XGQ1.0CommandandQueueSpecification(WIP)-Overview

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during PCIE emulation test update.

**Comment by dayeh-xilinx** [comment]
retest this please. Failed during PCIE emulation test update. Try again.

**Review by mamin506 — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please. Fixed PCIE emulation test issue.

**Comment by xilinxgitops** [comment]
retest this please

**Review by houlz0507 — APPROVED** [review]

**Review by stsoe — APPROVED** [review]
lgtm

**Review by maxzhen — APPROVED** [review]

**Review by chienwei-lan — APPROVED** [review]

**Pull request merged**
