### PR TITLE
NSPR-8677 SDx_PCIe_Platforms: New MAC Addressing Reporting Scheme for…

### PR DESCRIPTION
**Pull request by xdavidz**
… greater than 8 Addresses (XRT) - Only for U55N

> Test Results

Test Results;
```
root@xsjyliu50:~# /proj/rdi/staff/davidzha/share/cmcpy1/cmc_board_info.py -c b1
pyxbb: U55N on PCI bus 0000:b1:00.0 found
 SNSR_ID_BOARD_SN:XFL1LWAB5Y1M
 SNSR_ID_TOTAL_POWER_AVAIL:225W
 SNSR_ID_CONFIG_MODE:Master_SPI_x4
 SNSR_ID_FAN_PRESENCE:P
 SNSR_ID_NEW_MAC_SCHEME:Number of MAC addresses 8
 SNSR_ID_NEW_MAC_SCHEME:First MAC addresses 00:0a:35:08:83:01
 SNSR_ID_BOARD_REV:B
 SNSR_ID_SAT_VERSION:7.1.4
 SNSR_ID_BOARD_NAME:ALVEO U55N ES3

root@xsjyliu50:~# ./xbmgmt flash --scan --verbose
Card [0000:b1:00.0]
 Card type: u55n
 Flash type: SPI
 Flashable partition running on FPGA:
 xilinx_u55n_gen3x16_xdma_base_2,[ID=0x881fcec1f8fd0720],[SC=7.1.4]
 Logic UUID:
 881fcec1f8fd0720fb3d345a9430a159
 Flashable partitions installed in system:
 xilinx_u55n_gen3x16_xdma_base_2,[ID=0x881fcec1f8fd0720],[SC=7.1.2]
 Logic UUID:
 881fcec1f8fd0720fb3d345a9430a159
 Card name ALVEO U55N ES3
 Card S/N: XFL1LWAB5Y1M
 Config mode: 7
 Fan presence: P
 Max power level: 225W
 MAC address0: 00:0A:35:08:83:01
 MAC address1: 00:0A:35:08:83:02
 MAC address2: 00:0A:35:08:83:03
 MAC address3: 00:0A:35:08:83:04
 MAC address4: 00:0A:35:08:83:05
 MAC address5: 00:0A:35:08:83:06
 MAC address6: 00:0A:35:08:83:07
 MAC address7: 00:0A:35:08:83:08

root@xsjyliu50:~# ./xbmgmt flash --scan --json
{
 "card0": {
 "shellpackage": "xilinx_u55n_gen3x16_xdma_base_2,[ID=0x881fcec1f8fd0720],[SC=7.1.2]; ",
 "name": "ALVEO U55N ES3",
 "serial": "XFL1LWAB5Y1M",
 "config_mode": "7",
 "fan_presence": "P",
 "max_power": "225W",
 "mac0": "00:0A:35:08:83:01",
 "mac1": "00:0A:35:08:83:02",
 "mac2": "00:0A:35:08:83:03",
 "mac3": "00:0A:35:08:83:04",
 "mac4": "00:0A:35:08:83:05",
 "mac5": "00:0A:35:08:83:06",
 "mac6": "00:0A:35:08:83:07",
 "mac7": "00:0A:35:08:83:08"
 }
}

cat /sys/bus/pci/drivers/xclmgmt/0000\:b1\:00.0/xmc.m.16777217/mac_addr_first
 00:0A:35:08:83:01

cat /sys/bus/pci/drivers/xclmgmt/0000\:b1\:00.0/xmc.m.16777217/mac_contiguous_num
 8

```

### CODE REVIEW

**Review by maxzhen — COMMENTED** [review]
@xdavidz , how about xbmgmt2?

**Comment by xdavidz** [comment]
> @xdavidz , how about xbmgmt2?

I have no idea. Is there dup code in xbmgmt2?

**Comment by AShivangi** [comment]
We currently don't display any mac addresses in xbmgmt2. It will take some time to review how this information should be added to json and I'll have to run it past Stephen. David is going to file a ticket to track this issue and I'll revisit this once I have some time

**Review by AShivangi — APPROVED** [review]
I don't like the fixed length of mac addresses, but we can revisit this when we add this to xbmgmt2. This looks good for now

**Comment by maxzhen** [comment]
@xdavidz , you tested on old shell and MAC addresses can be showed correctly, right?

**Comment by xdavidz** [comment]
> I don't like the fixed length of mac addresses, but we can revisit this when we add this to xbmgmt2. This looks good for now

The current MAC is eui-48 which is fixed 6 bytes and CMC protocol won't be changed for that.
If we need to support eui-64, which I think we will need a new design between CMC and XRT.

**Comment by xdavidz** [comment]
> @xdavidz , you tested on old shell and MAC addresses can be showed correctly, right?

```
./xbmgmt flash --scan --verbose|grep -B5 -A2 MAC
    Card name                   ALVEO U55N ES3
    Card S/N:                   XFL1LWAB5Y1M
    Config mode:                7
    Fan presence:               P
    Max power level:            225W
    MAC address0:               00:0A:35:08:83:01
    MAC address1:               00:0A:35:08:83:02
    MAC address2:               00:0A:35:08:83:03
    MAC address3:               00:0A:35:08:83:04
    MAC address4:               00:0A:35:08:83:05
    MAC address5:               00:0A:35:08:83:06
    MAC address6:               00:0A:35:08:83:07
    MAC address7:               00:0A:35:08:83:08

Card [0000:3b:00.0]
--
    Card name                   ALVEO U50 ES3
    Card S/N:                   50121B39AN0J
    Config mode:                7
    Fan presence:               P
    Max power level:            75W
    MAC address0:               00:0A:35:06:47:7D
    MAC address1:               00:0A:35:06:47:7E
    MAC address2:               00:0A:35:06:47:7F
    MAC address3:               00:0A:35:06:47:80


./xbmgmt flash --scan --json|grep -B5 mac
        "name": "ALVEO U55N ES3",
        "serial": "XFL1LWAB5Y1M",
        "config_mode": "7",
        "fan_presence": "P",
        "max_power": "225W",
        "mac0": "00:0A:35:08:83:01",
        "mac1": "00:0A:35:08:83:02",
        "mac2": "00:0A:35:08:83:03",
        "mac3": "00:0A:35:08:83:04",
        "mac4": "00:0A:35:08:83:05",
        "mac5": "00:0A:35:08:83:06",
        "mac6": "00:0A:35:08:83:07",
        "mac7": "00:0A:35:08:83:08"
--
        "name": "ALVEO U50 ES3",
        "serial": "50121B39AN0J",
        "config_mode": "7",
        "fan_presence": "P",
        "max_power": "75W",
        "mac0": "00:0A:35:06:47:7D",
        "mac1": "00:0A:35:06:47:7E",
        "mac2": "00:0A:35:06:47:7F",
        "mac3": "00:0A:35:06:47:80"
```

**Review by maxzhen — APPROVED** [review]

**Pull request merged**
