### PR TITLE
Add aggregating header file for xrt/ APIs

### PR DESCRIPTION
**Pull request by bryanloz-xilinx**
#### Problem solved by the commit
Ease of use enhancement. Single include can bring in all the pieces a new user needs.

#### Documentation impact (if any)
Doesn't need to impact documentation

### CODE REVIEW

**Review by stsoe — APPROVED** [review]

**Review by uday610 — APPROVED** [review]

**Comment by wilderfield** [comment]
There is some conflict between the old XRT.h and the new one in the unittests…

**Comment by stsoe** [comment]
> There is some conflict between the old XRT.h and the new one in the unittests…

Yes.  Makes sense unfortunately.  I would like to think about getting rid of legacy include/xrt.h since we anyway stating the xcl APIs are no longer available in 23.2.

I am not keen on using a different name for the umbrella xrt.h you are creating.

**Comment by keryell** [comment]
If the old one is `include/xrt.h`, why should it conflict with `include/xrt/xrt.h`?

**Comment by wilderfield** [comment]
> If the old one is `include/xrt.h`, why should it conflict with `include/xrt/xrt.h`?

It must be that the test case being compiled is somehow supplied with both include/ and include/xrt as include paths. There is no other way for this to be a problem, but I haven’t actually debugged yet.

**Comment by stsoe** [comment]
> If the old one is `include/xrt.h`, why should it conflict with `include/xrt/xrt.h`?

Because some xrt/*.h files want to include legacy xrt.h for typedefs that do not belong there but happen to be for historical reasons.
```
% cat xrt/xrt_bo.h
...
#include "xrt.h"   // <-- want legacy xrt.h
...
```
that ends up including the new umbrella.

**Comment by stsoe** [comment]
I am not willing to spend cycles cleaning this up now.  Folks who want umbrellas, can create their own until we have cleaned up our mess for which we have a 23.2 story any way.

**Comment by wilderfield** [comment]
Ok, this can wait then

**Review by vboggara-xilinx — APPROVED** [review]

**Comment by stsoe** [comment]
Not ready for this PR

**Pull request closed without merging**
