### PR TITLE
XRT-812 command queue interrupt support on ps for u30

### PR DESCRIPTION
**Pull request by xuhz**
tested on u30 and u250 xdma 3.1, MB/PS cq can change between polling and interrupt mode.
also ran stress and performance comparison test on u30

### CODE REVIEW

**Comment by larry9523** [comment]
will this change break VCK5000?

**Comment by xuhz** [comment]
> will this change break VCK5000?

I don't test vck500.  the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working

**Comment by xdavidz** [comment]
> > will this change break VCK5000?
> 
> I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working

There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.

**Comment by larry9523** [comment]
> > > will this change break VCK5000?
> > 
> > 
> > I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working
> 
> There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.

My understanding is VCK5000 and U30 have different mechanism of CQ interrupt, where host->ert mailbox is used. If polling mode is still working (on U30 and VCK5000), I am OK with the change. 

A quick glance, I was scared that zocl-ert-thread was totally eliminated.

**Comment by xuhz** [comment]
> > > > will this change break VCK5000?
> > > 
> > > 
> > > I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working
> > 
> > 
> > There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.
> 
> My understanding is VCK5000 and U30 have different mechanism of CQ interrupt, where host->ert mailbox is used. If polling mode is still working (on U30 and VCK5000), I am OK with the change.
> 
> A quick glance, I was scared that zocl-ert-thread was totally eliminated.

The thread is not eliminated. The original one is, the thread is stopped in interrupt mode. with the change the thread is always there to iterate the cq -- difference is in interrupt mode, the thread is blocked to wait for signal from isr

**Comment by larry9523** [comment]
> > > > > will this change break VCK5000?
> > > > 
> > > > 
> > > > I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working
> > > 
> > > 
> > > There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.
> > 
> > 
> > My understanding is VCK5000 and U30 have different mechanism of CQ interrupt, where host->ert mailbox is used. If polling mode is still working (on U30 and VCK5000), I am OK with the change.
> > A quick glance, I was scared that zocl-ert-thread was totally eliminated.
> 
> The thread is not eliminated. The original one is, the thread is stopped in interrupt mode. with the change the thread is always there to iterate the cq -- difference is in interrupt mode, the thread is blocked to wait for signal from isr

I realized that too after closely looking at it. But still, it will be good if @xdavidz can take a look so that we know we can have most common code between vck5000 and u30.

**Comment by xdavidz** [comment]
> > > > > > will this change break VCK5000?
> > > > > 
> > > > > 
> > > > > I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working
> > > > 
> > > > 
> > > > There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.
> > > 
> > > 
> > > My understanding is VCK5000 and U30 have different mechanism of CQ interrupt, where host->ert mailbox is used. If polling mode is still working (on U30 and VCK5000), I am OK with the change.
> > > A quick glance, I was scared that zocl-ert-thread was totally eliminated.
> > 
> > 
> > The thread is not eliminated. The original one is, the thread is stopped in interrupt mode. with the change the thread is always there to iterate the cq -- difference is in interrupt mode, the thread is blocked to wait for signal from isr
> 
> I realized that too after closely looking at it. But still, it will be good if @xdavidz can take a look so that we know we can have most common code between vck5000 and u30.

For now, I can test the vck5000 new shell tomorrow. If the interrupt mode works, please verify vck5000 as well. 

I am also going to enable new KDS for vck5000 in 2021.1 or so, but it depends if KDS will be enabled in 2021.1.

**Comment by larry9523** [comment]
> > > > > > > will this change break VCK5000?
> > > > > > 
> > > > > > 
> > > > > > I don't test vck500. the polling mode is essentially the same with or without this change. interrupt mode, looks like versal doesn't support. If the cq part is identical between vck5000 and u30, I expect this makes the interrupt mode working
> > > > > 
> > > > > 
> > > > > There will be a new shell for vck5000 by tomorrow. I will let you know if interrupt mode works.
> > > > 
> > > > 
> > > > My understanding is VCK5000 and U30 have different mechanism of CQ interrupt, where host->ert mailbox is used. If polling mode is still working (on U30 and VCK5000), I am OK with the change.
> > > > A quick glance, I was scared that zocl-ert-thread was totally eliminated.
> > > 
> > > 
> > > The thread is not eliminated. The original one is, the thread is stopped in interrupt mode. with the change the thread is always there to iterate the cq -- difference is in interrupt mode, the thread is blocked to wait for signal from isr
> > 
> > 
> > I realized that too after closely looking at it. But still, it will be good if @xdavidz can take a look so that we know we can have most common code between vck5000 and u30.
> 
> For now, I can test the vck5000 new shell tomorrow. If the interrupt mode works, please verify vck5000 as well.
> 
> I am also going to enable new KDS for vck5000 in 2021.1 or so, but it depends if KDS will be enabled in 2021.1.

If interrupt does not work, we'd better make sure polling mode is still working on VCK5000

**Comment by xdavidz** [comment]
I tested Brian's code on vck5000 shell, zocl works as expected.

**Review by larry9523 — APPROVED** [review]

**Review by mamin506 — APPROVED** [review]

**Pull request merged**
