### PR TITLE
CR-1112696

### PR DESCRIPTION
**Pull request by maxzhen**
(cherry picked from commit a6bf41b5899bc23c1d6b32399747fdac53e6bc76)

### CODE REVIEW

**Comment by maxzhen** [comment]
retest this please -
ERROR: /proj/petalinux/2021.2/petalinux-v2021.2_0922_1/tool/petalinux-v2021.2-final/../../bsp/internal/zynq/zynq-rootfs-common-v2021.2-final.bsp not accessible

**Comment by dayeh-xilinx** [comment]
retest this please. There was a build issue with edge platform.

**Comment by dayeh-xilinx** [comment]
retest this please. There was a build issue with edge platform.

**Review by anupcs-xlnx — APPROVED** [review]
Approved

**Pull request merged**
