### PR TITLE
CR-1176493 : Fixed xbutil validate after ps test added

### PR DESCRIPTION
**Pull request by saifuddin-xilinx**
#### Problem solved by the commit
[CR-1176493](https://jira.xilinx.com/browse/CR-1176493)
While running 'xbutil validate', it's passing on first attempt and failing the second one. After device reset first run works fine.

#### How problem was solved, alternative solutions (if any) and why they were rejected
-- There are two issues : 
   1) Userspace XRT is not updated for OpenCL application. The new ps_bandwidth test is implemented based on the OpenCL way. Hence need to add one more entry for SCU kernels
  2) There is an issue for XGQ. We are actually removing XGQ while reloading a xclbin to a slot in XOCL side. But there can a situation that same XGQ can be shared between multiple SLOT as there are only limited slots available. 
       i) Added a ref_count  for XGQ if multiple CUs/SCUs are sharing the same. If oef_count is   "0" then only removing that XGQ.

### CODE REVIEW

**Comment by saifuddin-xilinx** [comment]
retest this please

**Review by stsoe — APPROVED** [review]
The core/common/device changes looks good.
I assume they have been tested thoroughly?

**Review by mamin506 — APPROVED** [review]

**Review by maxzhen — APPROVED** [review]

**Comment by saifuddin-xilinx** [comment]
retest this please

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by saifuddin-xilinx** [comment]
retest this please

**Comment by saifuddin-xilinx** [comment]
retest this please

**Comment by saifuddin-xilinx** [comment]
retest this please

**Comment by saifuddin-xilinx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
Please backport it to 2023.2 and take Sumit approval.

**Pull request merged**
