### PR TITLE
Fix for incorrect xrt rpm name

### PR DESCRIPTION
**Pull request by saumyag-xilinx**
#### Problem solved by the commit
[CR-1149492](https://jira.xilinx.com/browse/CR-1149492)
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Fixed the change in XRT rpm name format.
#### Risks (if any) associated the changes in the commit
low
#### What has been tested and how, request additional testing if necessary
Tested xrt package creation on redhat, centos and ubuntu
#### Documentation impact (if any)
na

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]

**Review by stsoe — COMMENTED** [review]
I am wary of redhat-relaese.  I think it is a mistake that we append .x to the package name.   major.x is compatible with major.y where y>=x.   So there is no point including x when we know what the least minor we support is.

**Comment by chvamshi-xilinx** [comment]
> I am wary of redhat-relaese. I think it is a mistake that we append .x to the package name. major.x is compatible with major.y where y>=x. So there is no point including x when we know what the least minor we support is.

That is true Soren, but this new naming convention broke Sprite regressions, Thatswhy we wanted to add it back. Saumya can send another PR after intimating DevOps/DSV about this name change. We also wanted to add OS_DIST as part of the package name. Saumya will do all those changes together

**Comment by chvamshi-xilinx** [comment]
> > I am wary of redhat-relaese. I think it is a mistake that we append .x to the package name. major.x is compatible with major.y where y>=x. So there is no point including x when we know what the least minor we support is.
> 
> That is true Soren, but this new naming convention broke Sprite regressions, Thatswhy we wanted to add it back. Saumya can send another PR after intimating DevOps/DSV about this name change. We also wanted to add OS_DIST as part of the package name. Saumya will do all those changes together

@stsoe , shall i go ahead and merge once build passes as it is blocking sprite regressions

**Review by stsoe — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
> > @stsoe , shall i go ahead and merge once build passes as it is blocking sprite regressions
> 
> Yes please.

Thanks Soren.

**Pull request merged**
