### PR TITLE
covertiry fixes-1 (2018.3)

### PR DESCRIPTION
**Pull request by sarab96**
Coverity fixes
@stsoe  Please check

### CODE REVIEW

**Comment by stsoe** [comment]
ok to test

**Comment by sarab96** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by sarab96** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by NaAl-Xlnx** [comment]
retest this please

**Pull request merged**
