### PR TITLE
CR-1118993 Application runtime hang observed for Head Canary test

### PR DESCRIPTION
**Pull request by chienwei-lan**
#### Problem solved by the commit
HW_EMU tests hang
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://github.com/Xilinx/XRT/pull/6115, discovered in Head Canary test
#### How problem was solved, alternative solutions (if any) and why they were rejected
Correct the configure CU logic in HW_EMU

#### What has been tested and how, request additional testing if necessary
Rerun the test

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by boxerab** [comment]
hello - I am seeing a hw emu hang for the zcu 102
https://github.com/Xilinx/XRT/issues/6139
Could this fix be related ?

**Comment by maxzhen** [comment]
No, it's unrelated. Something else is going on here.

**Pull request merged**
