### PR TITLE
Add the chance to build XRT with dynamic Boost libraries

### PR DESCRIPTION
**Pull request by mclayton1000**
Add in build.sh script the option to build XRT runtime with dynamically linked Boost libraries.

### CODE REVIEW

**Comment by stsoe** [comment]
Hi @mclayton1000 .  The default should be to link with dynamic Boost always.  I would prefer to remove    set(Boost_USE_STATIC_LIBS     ON) from all Individual CMakeLists.txt files.   The only option for static linking boost should be through XRT_BOOST_INSTALL environment variable (see nativeLnx.cmake and runtime_src/tools/scripts/boost.sh).

**Comment by mclayton1000** [comment]
Hi @stsoe ,
Thank you for the reply. It would be grateful to have the chance to build XRT without the need of static boost libraries.
Please, feel free to contact me if you need support for this.

Best regards,

mclayton1000

**Comment by stsoe** [comment]
@mclayton1000 please check #4449 and see if that addresses your issues.  Linux defaults to dynamic, all makefile overwrites were removed.  On Windows only static linking works.

**Comment by mclayton1000** [comment]
Hi @stsoe ,
patchset #4449 resolve the issues described. The compilation went fine on Linux. Really thank you.

**Comment by stsoe** [comment]
Obsoleted by #4449

**Pull request closed without merging**
