### PR TITLE
Update 15_buffer and host_src/utils.h to fix the host code compilation issue on Sprite

### PR DESCRIPTION
**Pull request by haeseung81**
Update 15_buffer and host_src/utils.h to fix the host code compilation issue on Sprite (4/4/2019).

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by haeseung81** [comment]
Can you do the retest?

**Comment by maxzhen** [comment]
retest this please

**Comment by houlz0507** [comment]
retest this please

**Pull request merged**
