### PR TITLE
CR-1057939 U30 SC flash should preform on master SC only

### PR DESCRIPTION
**Pull request by xdavidz**
This is pre-review request, please take a look and let me know your thoughts.

### CODE REVIEW

**Comment by xdavidz** [comment]
retest this please

**Comment by xdavidz** [comment]
Tested with golden and shell +CMC 1.4.3.

`
## U30 Golden ##
Card [0000:da:00.0]
    Card type:          u30
    Flash type:         QSPI_PS
    Flashable partition running on FPGA:
        xilinx_u30_GOLDEN_0,[SC=INACTIVE]
    Flashable partitions installed in system:   (None).

## Flash U30 Golden ##
/xbmgmt flash --shell --path U30_RevB_RC5/flash_image/BOOT_full_RC4.1.bin --card 0000:da:00.0
Warning: QSPIPS mode does not support secondary file.
INFO: ***BOOT.BIN has 65834856 bytes
Idcode byte[0]=20
Idcode byte[1]=bb
Idcode byte[2]=21
Idcode byte[3]=10
Idcode byte[4]=44
Idcode byte[5]=0
Erasing flash........

## Regular Shell ##
Card [0000:da:00.1]
    Card type:          U30
    Flash type:         QSPI_PS
    Flashable partition running on FPGA:
        xilinx_U30_xdma_1_1,[ID=0x5e3a0c82],[SC=6.3.1]
    Flashable partitions installed in system:
        xilinx_U30_xdma_1_1,[ID=0x5e3a0c82],[SC=4.3.4]

ERROR: SC is not ready: 0x0
ERROR: SC is not ready: 0x0
ERROR: SC is not ready: 0x0
Card [0000:d9:00.1]
    Card type:          U30
    Flash type:         QSPI_PS
    Flashable partition running on FPGA:
        xilinx_U30_xdma_1_1,[ID=0x5e3a0c82],[SC=UNKNOWN]
    Flashable partitions installed in system:
        xilinx_U30_xdma_1_1,[ID=0x5e3a0c82],[SC=4.3.4]

** Note: once CMC fixed the UNKNOWN issue, we should see SC=6.3.1(Fixed) **
`

**Comment by maxzhen** [comment]
The change you just added is a temp workaround, right? We should be able to stop any one of the FPGA on U30 at any time.

**Comment by xdavidz** [comment]
> The change you just added is a temp workaround, right? We should be able to stop any one of the FPGA on U30 at any time.

I found more issues after I figured out how to make CMC working. I will chat with you and lizhi first.

**Comment by xdavidz** [comment]
close this as need more work

**Pull request closed without merging**
