### PR TITLE
Dual qspi bitstream guard changes

### PR DESCRIPTION
**Pull request by cellery**
Updates to support bitstream guard for dual qspi boards.

### CODE REVIEW

**Comment by AShivangi** [comment]
@stsoe should xspi changes be made in xbmgmt2 as well?

**Comment by maxzhen** [comment]
ok to test

**Comment by cellery** [comment]
Pushed the same updates to xbmgmt2

**Comment by maxzhen** [comment]
@stsoe agreed to merge it for now. @AShivangi will finish porting xspi.cpp to xbmgmt2 after this merge.

**Pull request merged**
