### PR TITLE
Cleanup how XRT links with Boost libraries

### PR DESCRIPTION
**Pull request by stsoe**
On Linux, the default is dynamic linking with Boost in all make-files.  Static linking with Boost is supported only via runtime_src/tools/scripts/boost.sh, which downloads a release of boost, builds static boost libraries with proper options, and lists how to use these static libraries when building XRT.

On Windows, XRT only supports static linking with Boost through libraries built and installed using xrtdeps-win.py.

This PR replaces #4430

### CODE REVIEW

**Review by rozumx — APPROVED** [review]
Thank you for making these changes.   

I do believe that the Windows Static Boost libraries are no longer needed.  Let's think about removing these requirements in a future pull request.

**Comment by stsoe** [comment]
retest this please

**Comment by mclayton1000** [comment]
Hi @stsoe ,
patchset #4449 resolve the issues described. The compilation went fine on Linux. Really thank you.

**Comment by stsoe** [comment]
retest this please

**Pull request merged**
