### PR TITLE
cpp changes and hal_probe updated for new hwcfg without yaml stuff

### PR DESCRIPTION
**Pull request by sarab96**
cpp changes and hal_probe updated for new hwcfg without yaml stuff

### CODE REVIEW

**Comment by stsoe** [comment]
Why are the atomic data members allocated on the heap?
I suspect its related to missing deletes of copy ctor and assignment ctor.

**Comment by sarab96** [comment]
yes Soren that is correct. atomic do not allow copy or move.

**Comment by stsoe** [comment]
But this should be changed.   Allocating these on the heap makes no sense.
Please disable the copy and assignment ctor.
Definitely atomics can be moved so make sure move ctor/assignment is defined, but that corresponding copies are deleted.

**Comment by stsoe** [comment]
Ok, so by design std::atomic cannot be moved.  Alas objects with std::atomic data members cannot be inserted into a vector if the vector will resize itself when new objects are emplace constructed.  Given this. I guess it makes sense that the std::atomic data member is on the heap.  Case rested :-)

**Pull request merged**
