### PR TITLE
mb_ch_state only changes while user probe

### PR DESCRIPTION
**Pull request by chienwei-lan**

### CODE REVIEW

**Comment by chienwei-lan** [comment]
http://jira.xilinx.com/browse/CR-1027256

**Comment by maxzhen** [comment]
ok to test

**Comment by maxzhen** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by maxzhen** [comment]
The change does not work, needs more thoughts. Closing it for now.

**Pull request closed without merging**
