### PR TITLE
Automatically install packages on amazon linux

### PR DESCRIPTION
**Pull request by ksmurakoshi**
When installing on amazon linux, XRT/src/runtime_src/tools/scripts/xrtdeps.sh requires user input (yum install <package>). Fix to allow xrtdeps.sh to install without user input. 

Signed-off-by: Kevin Murakoshi <murakevi@amazon.com>

### CODE REVIEW

**Comment by sonals** [comment]
ok to test

**Review by stsoe — COMMENTED** [review]
@ksmurakoshi Thanks looks good.  If you're from outside of Xilinx, you need "sign-off-by" in your pull request. Please follow the instructions listed here: https://github.com/Xilinx/XRT/blob/master/CONTRIBUTING.rst

**Comment by ksmurakoshi** [comment]
@stsoe I updated my initial pull request. Is that enough? (or do you need me to do something else)?

**Comment by stsoe** [comment]
@ksmurakoshi Can you add signed-off in this PR also?  Maybe update your commit comment with a force push?

**Comment by stsoe** [comment]
Thank you!

**Pull request merged**
