### PR TITLE
XRT-804 We see occasional kernel panic on wistronserver host with 8 U…

### PR DESCRIPTION
**Pull request by houlz0507**
…30 cards, possibly due to xrt driver (xdma_request_alloc) in 2020.1

### CODE REVIEW

**Review by maxzhen — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Pull request merged**
