### PR TITLE
CR-1076108 ASTeR TC 4.01 Firewall test causes server reboot

### PR DESCRIPTION
**Pull request by xdavidz**
I hope this won't cause u30 regression and still can catch the 0xDEADFA11 earlier.

This will prevent later read32 panic the system before heath check thread could find the firewall trip and reset.
Detailed reason listed in the CR.
https://jira.xilinx.com/browse/CR-1076108

### CODE REVIEW

**Review by maxzhen — CHANGES_REQUESTED** [review]
please create a function for reading mailbox offset and hide this ugly check inside.

**Review by xuhz — COMMENTED** [review]
I am wondering whether this really can fix the issue if this issue needs to be fixed or worthy of fixing.
there are other possible register writes other than the mailbox write after firewall.
how about check the word alignment in io_write32 and don't write if not aligned?

**Comment by maxzhen** [comment]
On a second thought, I agree with @xuhz that this fix is bogus. A firewall trip on **mgmt** pf is never OK. There is no way for driver to stay up and running when this happens. If firewall trip does happen on mgmt pf, it's a HW bug and must be fixed in HW. We can't workaround it inside drive. I'm closing this pull request and the CR.

**Comment by xdavidz** [comment]
> I am wondering whether this really can fix the issue if this issue needs to be fixed or worthy of fixing.
> there are other possible register writes other than the mailbox write after firewall.
> how about check the word alignment in io_write32 and don't write if not aligned?

Please check the comments in the CR. I will include you and Max into the email loop with Niel.

**Pull request closed without merging**
