### PR TITLE
log operations into ring buffer memory and dump the log when timeout

### PR DESCRIPTION
**Pull request by xdavidz**
example of log dump

```
[ 3024.460028] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 1 sg cnt 1.
[ 3024.460028] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460034] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460036] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460036] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1
[ 3024.460037] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 2 sg cnt 1.
[ 3024.460038] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460038] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460039] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460040] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1
[ 3024.460040] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 4 sg cnt 1.
[ 3024.460041] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460042] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460042] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460043] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1
[ 3024.460044] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 8 sg cnt 1.
[ 3024.460044] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460045] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460046] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460046] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1
[ 3024.460047] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 16 sg cnt 1.
[ 3024.460048] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460048] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460049] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460050] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1
[ 3024.460050] 0000:3b:00.1 engine:0-H2C0-MM, channel 0, len 32 sg cnt 1.
[ 3024.460051] 0000:3b:00.1 start dma engine 0-H2C0-MM, channel 0
[ 3024.460052] 0000:3b:00.1 start waiting for req desc_cnt 1, desc_completed 0
[ 3024.460052] 0000:3b:00.1 irq:250 received. engine 0-H2C0-MM, channel 0
[ 3024.460053] 0000:3b:00.1 wait_event done req desc_cnt 1, desc_completed 1

```

### CODE REVIEW

**Review by houlz0507 — COMMENTED** [review]
Please add a debug print in interrupt handler. This may capture the issue of task scheduling.

**Comment by houlz0507** [comment]
> Please add a debug print in interrupt handler. This may capture the issue of task scheduling.

May bad. Interrupt log is added.

**Review by maxzhen — APPROVED** [review]

**Comment by xdavidz** [comment]
The last comment only removed one extra unnecessary line, should not be failed.
retest this please

**Comment by houlz0507** [comment]
Found a more efficient way to detect missing XDMA interrupt. https://github.com/Xilinx/XRT/pull/5879

**Pull request closed without merging**
