### PR TITLE
2019.1xrt : PR-11454

### PR DESCRIPTION
**Pull request by IshitaGhosh**
While loading and initializing XDP, detect whether there are multiple live processes on device. New API "xclGetNumLiveProcesses" has been added to XOCLShim which checks "kdsstat" to determine the current number of live processes. If there are multiple processes, turn off Debug/Profile support for the current process and give a Warning.
A skeletal version of xclGetNumLiveProcesses has been added to ZYNQShim, just to avoid crash in Zynq flow.

### CODE REVIEW

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Comment by sonals** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
