### PR TITLE
CR-1142089 - Improvements to AIE graph hierarchy and channel support

### PR DESCRIPTION
**Pull request by pgschuey**
**Problem solved by the commit**
* Improved subgraph support
* Corrected memory tile graph support - now using buffer name
* Corrected issues with channel numbers

**What has been tested and how, request additional testing if necessary**
* Tested on vck190 and vek280

**Documentation impact (if any)**
* Memory tile graph support is now graph-buffer (not kernel)

### CODE REVIEW

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by manikandan-xilinx** [comment]
retest this please.

**Comment by manikandan-xilinx** [comment]
retest this please. (Removed the host where there are some issues)

**Comment by manikandan-xilinx** [comment]
retest this please.

**Pull request merged**
