### PR TITLE
Add polling flag in ini file for internal debugging of XGQ based KDS

### PR DESCRIPTION
**Pull request by mamin506**
#### Problem solved by the commit
Add new polling flag for XGQ base KDS in the ini file.

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
CR-1141464

#### Documentation impact (if any)
No

### CODE REVIEW

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Review by maxzhen — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Review by rozumx — APPROVED** [review]

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by chvamshi-xilinx** [comment]
Hi @mamin506 , I think, we still need this for internal debug? If yes, we can merge this PR.

**Comment by mamin506** [comment]
> Hi @mamin506 , I think, we still need this for internal debug? If yes, we can merge this PR.

Hi @chvamshi-xilinx , yes. We need this. Please merge it.

**Comment by chvamshi-xilinx** [comment]
retest this please

**Pull request merged**
