### PR TITLE
Tools

### PR DESCRIPTION
**Pull request by sonals**

### CODE REVIEW

**Review by AShivangi — APPROVED** [review]

**Review by rozumx — CHANGES_REQUESTED** [review]
This is looks great.

Before approving the changes, can you validate that both the long and short version 2 options are represented in this list.  It looks like it is, but not 100% sure that this check was done. I

For example: "--help" and "-h"; "--device" and "-d"

**Comment by AShivangi** [comment]
retest this please

**Comment by AShivangi** [comment]
Hi @rozumx, I validated a few and they work as expected:
"-h", "--help", "-d <index>", "--device <index>", "-d <bdf>", "--device <bdf>", an overlapping command "xbutil validate"

**Review by rozumx — APPROVED** [review]
Approved.  Thank you Shivangi for double checkking.

**Pull request merged**
