### PR TITLE
CR-1079255 & CR-1078587 Add xmc_u2 subdev driver for u2

### PR DESCRIPTION
**Pull request by rajkumar-xilinx**
Add new xmc.u2 subdev driver, which will be loaded only for u2 platforms where sc firmware is absent.

Add new xmc_u2 driver in xrt for u2 platform to differentiate between SC & NOSC platforms. Platform team defined new regmap abstraction “cmc_regmap_u2” for u2 in raptor2 flow. So, added required changes to support this in XRT.

xilinx.com:reg_abs:axi_bram_ctrl:1.0 – For all other platforms
xilinx.com:reg_abs:cmc_regmap_u2:1.0 – For U2 platforms.

All u2 specific xmc changes will be added into this new driver "xmc_u2".

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

### CODE REVIEW

**Comment by rajkumar-xilinx** [comment]
**On U50**
`[root@xsjsda160 Release]# xbutil list
INFO: Found total 1 card(s), 1 are usable
WARNING: The xbutil sub-command list has been deprecated. Please use xbutil scan for equivalent functionality.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:	Linux
Release:	3.10.0-1127.el7.x86_64
Version:	#1 SMP Tue Mar 31 23:36:51 UTC 2020
Machine:	x86_64
Model:		PowerEdge R740
CPU cores:	12
Memory:		46556 MB
Glibc:		2.17
Distribution:	CentOS Linux 7 (Core)
Now:		Thu Nov  5 17:54:55 2020 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:	2.8.0
Git Hash:	c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
Git Branch:	HEAD
Build Date:	2020-11-05 09:46:29
XOCL:		2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
XCLMGMT:	2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 [0] 0000:3b:00.1 xilinx_u50_gen3x16_xdma_201920_3 user(inst=128)
[root@xsjsda160 Release]# xbutil validate
INFO: Found 1 cards

INFO: Validating card[0]: xilinx_u50_gen3x16_xdma_201920_3
INFO: == Starting Kernel version check: 
INFO: == Kernel version check PASSED
INFO: == Starting AUX power connector check: 
AUX power connector not available. Skipping validation
INFO: == AUX power connector check SKIPPED
INFO: == Starting Power warning check: 
INFO: == Power warning check PASSED
INFO: == Starting PCIE link check: 
INFO: == PCIE link check PASSED
INFO: == Starting SC firmware version check: 
INFO: == SC firmware version check PASSED
INFO: == Starting verify kernel test: 
INFO: == verify kernel test PASSED
INFO: == Starting DMA test: 
Host -> PCIe -> FPGA write bandwidth = 11642.184729 MB/s
Host <- PCIe <- FPGA read bandwidth = 11914.735176 MB/s
INFO: == DMA test PASSED
INFO: == Starting device memory bandwidth test: 
............
Maximum throughput: 43855 MB/s
INFO: == device memory bandwidth test PASSED
INFO: == Starting PCIE peer-to-peer test: 
P2P BAR is not enabled. Skipping validation
INFO: == PCIE peer-to-peer test SKIPPED
INFO: == Starting memory-to-memory DMA test: 
M2M is not available. Skipping validation
INFO: == memory-to-memory DMA test SKIPPED
INFO: == Starting host memory bandwidth test: 
Host_mem is not available. Skipping validation
INFO: == host memory bandwidth test SKIPPED
INFO: Card[0] validated successfully.

INFO: All cards validated successfully.
[root@xsjsda160 Release]# xbmgmt flash --scan
Card [0000:3b:00.0]
    Card type:		u50
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u50_gen3x16_xdma_201920_3,[ID=0xf465b0a3ae8c64f6],[SC=5.1.7]
    Flashable partitions installed in system:	
        xilinx_u50_gen3x16_xdma_201920_3,[ID=0xf465b0a3ae8c64f6],[SC=5.1.7]
`

**Comment by chvamshi-xilinx** [comment]
@rajkumar-xilinx  is verifying U.2/U50/U250 . Marking do-not-merge

**Comment by maxzhen** [comment]
please also try xbutil query to make sure all sensor readings from xmc are good on shells you are testing with.

**Comment by rajkumar-xilinx** [comment]
**U2 + U250 setup**

$ xbutil list
INFO: Found total 2 card(s), 2 are usable
WARNING: The xbutil sub-command list has been deprecated. Please use xbutil scan for equivalent functionality.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:	Linux
Release:	4.15.0-122-generic
Version:	#124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020
Machine:	x86_64
Model:		PowerEdge T640
CPU cores:	12
Memory:		63819 MB
Glibc:		2.23
Distribution:	Ubuntu 16.04.6 LTS
Now:		Fri Nov  6 03:05:09 2020 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:	2.8.0
Git Hash:	c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
Git Branch:	HEAD
Build Date:	2020-11-06 08:15:26
XOCL:		2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
XCLMGMT:	2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 [0] 0000:5e:00.1 xilinx_u250_gen3x16_base_3 user(inst=129)
 [1] 0000:3e:00.1 xilinx_u2_gen3x4_xdma_base_1 user(inst=128)


$xbmgmt flash --scan
Card [0000:5e:00.0]
    Card type:		u250
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=0.0]
    Flashable partitions installed in system:	
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=4.6.6]

Failed to open XMC device on card
Failed to open XMC device on card
Failed to open XMC device on card
Card [0000:3e:00.0]
    Card type:		u2
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b],[SC=INACTIVE]
    Flashable partitions installed in system:	
        xilinx_samsung_u2x4_202010_1,[ID=0x5f19544a]
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b]

=======================================================================
**u2: xbutil query -d 1**
INFO: Found total 2 card(s), 2 are usable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:	Linux
Release:	4.15.0-122-generic
Version:	#124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020
Machine:	x86_64
Model:		PowerEdge T640
CPU cores:	12
Memory:		63819 MB
Glibc:		2.23
Distribution:	Ubuntu 16.04.6 LTS
Now:		Fri Nov  6 03:07:50 2020 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:	2.8.0
Git Hash:	c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
Git Branch:	HEAD
Build Date:	2020-11-06 08:15:26
XOCL:		2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
XCLMGMT:	2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shell                           FPGA                            IDCode
xilinx_u2_gen3x4_xdma_base_1                                    0x14a56093
Vendor          Device          SubDevice       SubVendor       SerNum          
0x10ee          0x6988          0x1351          0x10ee                          
DDR size        DDR count       Clock0          Clock1          Clock2          
0 Byte          0               300             500             0               
PCIe            DMA chan(bidir) MIG Calibrated  P2P Enabled     OEM ID          
GEN 3x4         2               false           true            0x0(N/A)        
Interface UUID
109f96074632cd8264b329f84b14cb30
Logic UUID
fd5aae95f114297b10995aacac916eb7
DNA                             CPU_AFFINITY    HOST_MEM size   Max HOST_MEM    
                                0,2,4,6,8,10    0 Byte          0 Byte          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Temperature(C)
PCB TOP FRONT   PCB TOP REAR    PCB BTM FRONT   VCCINT TEMP     
N/A             N/A             N/A             N/A             
FPGA TEMP       TCRIT Temp      FAN Presence    FAN Speed(RPM)  
49              N/A                            N/A             
QSFP 0          QSFP 1          QSFP 2          QSFP 3          
N/A             N/A             N/A             N/A             
HBM TEMP        
N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Electrical(mV|mA)
12V PEX         12V AUX         12V PEX Current 12V AUX Current 
12000           N/A             2416            N/A             
3V3 PEX         3V3 AUX         DDR VPP BOTTOM  DDR VPP TOP     
3300            N/A             N/A             N/A             
SYS 5V5         1V2 TOP         1V8 TOP         0V85            
N/A             N/A             N/A             N/A             
MGT 0V9         12V SW          MGT VTT         1V2 BTM         
N/A             N/A             N/A             N/A             
VCCINT VOL      VCCINT CURR     VCCINT IO VOL   VCC3V3 VOL      
N/A             N/A             N/A             N/A             
3V3 PEX CURR    VCCINT IO CURR  HBM1V2 VOL      VPP2V5 VOL      
N/A             N/A             N/A             N/A             
VCC1V2 CURR     V12 I CURR      V12 AUX0 CURR   V12 AUX1 CURR   
N/A             N/A             N/A             N/A             
12V AUX1 VOL    VCCAUX VOL      VCCAUX PMC VOL  VCCRAM VOL      
N/A             N/A             N/A             N/A             
3V3 AUX CURR    POWER WARN      
N/A             N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Card Power(W)
28
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Firewall Last Error Status
Level 0 : 0x0(GOOD)

ECC Error Status
Tag     Errors      CE Count  UE Count  CE FFA              UE FFA              
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Memory Status
     Tag                 Type        Temp(C)  Base Address    Size    Mem Usage   BO count
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DMA Transfer Metrics
Chan[0].h2c:  0 Byte
Chan[0].c2h:  0 Byte
Chan[1].h2c:  0 Byte
Chan[1].c2h:  0 Byte
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Streams
     Tag         Flow ID  Route ID Status   Total (B/#)     Pending (B/#)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Xclbin UUID
00000000-0000-0000-0000-000000000000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compute Unit Status
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Partition Info:
    installation
        installed_package_dir: /opt/xilinx/firmware/u2/gen3x4-xdma/base
        installed_package_name: xilinx-u2-gen3x4-xdma-base
        installed_package_release: 3050351
        installed_package_version: 1
    partition_card: u2
    partition_family: gen3x4-xdma
    partition_features
        pcie
            device_ids
                6987
                    role: management_pf
                6988
                    role: user_pf
            extended_capabilities: enabled
            max_link_speed: gen3x4
            subsystem_id: 000e
            vendor_id: 10ee
    partition_identifiers
        interface_uuids
            109f96074632cd8264b329f84b14cb30
                type: exposed
        logic_uuid: fd5aae95f114297b10995aacac916eb7
    partition_name: base
    partition_type: base
    partition_vendor: xilinx
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: xbutil query succeeded.
=====================================================================
**u250: xbutil query -d 0**
INFO: Found total 2 card(s), 2 are usable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:	Linux
Release:	4.15.0-122-generic
Version:	#124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020
Machine:	x86_64
Model:		PowerEdge T640
CPU cores:	12
Memory:		63819 MB
Glibc:		2.23
Distribution:	Ubuntu 16.04.6 LTS
Now:		Fri Nov  6 03:08:33 2020 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:	2.8.0
Git Hash:	c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
Git Branch:	HEAD
Build Date:	2020-11-06 08:15:26
XOCL:		2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b
XCLMGMT:	2.8.0,c50b9902a19a2faf2dffa9941a4bd4e44446fe8b

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shell                           FPGA                            IDCode
xilinx_u250_gen3x16_xdma_shell_3_1                                0x4b57093
Vendor          Device          SubDevice       SubVendor       SerNum          
0x10ee          0x5005          0x000e          0x10ee                          
DDR size        DDR count       Clock0          Clock1          Clock2          
0 Byte          0               0               0               0               
PCIe            DMA chan(bidir) MIG Calibrated  P2P Enabled     OEM ID          
GEN 3x16        2               false           false           0x0(N/A)        
Interface UUID
6ff0ecd07a52337485014edaded39636
Logic UUID
1b075270ee96025ca6409627d1cdbc10
DNA                             CPU_AFFINITY    HOST_MEM size   Max HOST_MEM    
                                0,2,4,6,8,10    0 Byte          0 Byte          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Temperature(C)
PCB TOP FRONT   PCB TOP REAR    PCB BTM FRONT   VCCINT TEMP     
N/A             N/A             N/A             N/A             
FPGA TEMP       TCRIT Temp      FAN Presence    FAN Speed(RPM)  
N/A             N/A                            N/A             
QSFP 0          QSFP 1          QSFP 2          QSFP 3          
N/A             N/A             N/A             N/A             
HBM TEMP        
N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Electrical(mV|mA)
12V PEX         12V AUX         12V PEX Current 12V AUX Current 
N/A             N/A             N/A             N/A             
3V3 PEX         3V3 AUX         DDR VPP BOTTOM  DDR VPP TOP     
N/A             N/A             N/A             N/A             
SYS 5V5         1V2 TOP         1V8 TOP         0V85            
N/A             N/A             N/A             N/A             
MGT 0V9         12V SW          MGT VTT         1V2 BTM         
N/A             N/A             N/A             N/A             
VCCINT VOL      VCCINT CURR     VCCINT IO VOL   VCC3V3 VOL      
N/A             N/A             N/A             N/A             
3V3 PEX CURR    VCCINT IO CURR  HBM1V2 VOL      VPP2V5 VOL      
N/A             N/A             N/A             N/A             
VCC1V2 CURR     V12 I CURR      V12 AUX0 CURR   V12 AUX1 CURR   
N/A             N/A             N/A             N/A             
12V AUX1 VOL    VCCAUX VOL      VCCAUX PMC VOL  VCCRAM VOL      
N/A             N/A             N/A             N/A             
3V3 AUX CURR    POWER WARN      
N/A             N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Card Power(W)
N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Firewall Last Error Status
Level 0 : 0x0(GOOD)

ECC Error Status
Tag     Errors      CE Count  UE Count  CE FFA              UE FFA              
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Memory Status
     Tag                 Type        Temp(C)  Base Address    Size    Mem Usage   BO count
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DMA Transfer Metrics
Chan[0].h2c:  0 Byte
Chan[0].c2h:  0 Byte
Chan[1].h2c:  0 Byte
Chan[1].c2h:  0 Byte
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Streams
     Tag         Flow ID  Route ID Status   Total (B/#)     Pending (B/#)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Xclbin UUID
00000000-0000-0000-0000-000000000000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compute Unit Status
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Partition Info:
    installation
        installed_package_dir: /opt/xilinx/firmware/u250/gen3x16/base
        installed_package_name: xilinx-u250-gen3x16-base
        installed_package_release: 3051647
        installed_package_version: 3
    partition_card: u250
    partition_family: gen3x16
    partition_features
        pcie
            device_ids
                5004
                    role: management_pf
                5005
                    role: user_pf
            extended_capabilities: enabled
            max_link_speed: gen3x16
            subsystem_id: 000e
            vendor_id: 10ee
    partition_identifiers
        interface_uuids
            541757bc1add2b667f78b5be5822de39
                type: exposed
        logic_uuid: ef6fdbfd98962bf2017baf5ec6db0e02
    partition_name: base
    partition_type: base
    partition_vendor: xilinx

Partition Info:
    installation
        installed_package_dir: /opt/xilinx/firmware/u250/gen3x16/xdma-shell
        installed_package_name: xilinx-u250-gen3x16-xdma-shell
        installed_package_release: 3051707
        installed_package_version: 3.1
    partition_card: u250
    partition_family: gen3x16
    partition_features
        clocks
            aclk_kernel_00
                freq_range
                    default: 300
                    maximum: 500
                    minimum: 100
                scalable: true
                stepable: false
        cmc
            qsfp_ctrl: enabled
            qsfp_interrupts: enabled
        dma
            num_channels: 2
            type: xdma
        ert
            command_queue_slots: tbd
            kernel_interrupts: enabled
        p2p
            maximum_memory_aperture: 64G
    partition_identifiers
        interface_uuids
            541757bc1add2b667f78b5be5822de39
                type: resolved
            6ff0ecd07a52337485014edaded39636
                type: exposed
        logic_uuid: 1b075270ee96025ca6409627d1cdbc10
    partition_name: xdma-shell
    partition_type: shell
    partition_vendor: xilinx
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: xbutil query succeeded.

**Review by houlz0507 — APPROVED** [review]

**Comment by rajkumar-xilinx** [comment]
Verified it on U2, U50.

**Comment by rajkumar-xilinx** [comment]
**On U2**
xbutil query -d 1
```
INFO: Found total 2 card(s), 2 are usable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:	Linux
Release:	4.15.0-122-generic
Version:	#124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020
Machine:	x86_64
Model:		PowerEdge T640
CPU cores:	12
Memory:		63819 MB
Glibc:		2.23
Distribution:	Ubuntu 16.04.6 LTS
Now:		Fri Nov  6 12:16:22 2020 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:	2.8.0
Git Hash:	08a0be4f02596ea830e56e2944d957cb88fa4082
Git Branch:	HEAD
Build Date:	2020-11-06 09:56:45
XOCL:		2.8.0,08a0be4f02596ea830e56e2944d957cb88fa4082
XCLMGMT:	2.8.0,08a0be4f02596ea830e56e2944d957cb88fa4082

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shell                           FPGA                            IDCode
xilinx_u2_gen3x4_xdma_base_1                                    0x14a56093
Vendor          Device          SubDevice       SubVendor       SerNum          
0x10ee          0x6988          0x1351          0x10ee                          
DDR size        DDR count       Clock0          Clock1          Clock2          
0 Byte          0               300             500             0               
PCIe            DMA chan(bidir) MIG Calibrated  P2P Enabled     OEM ID          
GEN 3x4         2               false           true            0x0(N/A)        
Interface UUID
109f96074632cd8264b329f84b14cb30
Logic UUID
fd5aae95f114297b10995aacac916eb7
DNA                             CPU_AFFINITY    HOST_MEM size   Max HOST_MEM    
                                0,2,4,6,8,10    0 Byte          0 Byte          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Temperature(C)
PCB TOP FRONT   PCB TOP REAR    PCB BTM FRONT   VCCINT TEMP     
N/A             N/A             N/A             N/A             
FPGA TEMP       TCRIT Temp      FAN Presence    FAN Speed(RPM)  
49              N/A                            N/A             
QSFP 0          QSFP 1          QSFP 2          QSFP 3          
N/A             N/A             N/A             N/A             
HBM TEMP        
N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Electrical(mV|mA)
12V PEX         12V AUX         12V PEX Current 12V AUX Current 
12000           N/A             2564            N/A             
3V3 PEX         3V3 AUX         DDR VPP BOTTOM  DDR VPP TOP     
3300            N/A             N/A             N/A             
SYS 5V5         1V2 TOP         1V8 TOP         0V85            
N/A             N/A             N/A             N/A             
MGT 0V9         12V SW          MGT VTT         1V2 BTM         
N/A             N/A             N/A             N/A             
VCCINT VOL      VCCINT CURR     VCCINT IO VOL   VCC3V3 VOL      
N/A             N/A             N/A             N/A             
3V3 PEX CURR    VCCINT IO CURR  HBM1V2 VOL      VPP2V5 VOL      
N/A             N/A             N/A             N/A             
VCC1V2 CURR     V12 I CURR      V12 AUX0 CURR   V12 AUX1 CURR   
N/A             N/A             N/A             N/A             
12V AUX1 VOL    VCCAUX VOL      VCCAUX PMC VOL  VCCRAM VOL      
N/A             N/A             N/A             N/A             
3V3 AUX CURR    POWER WARN      
N/A             N/A             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Card Power(W)
30
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Firewall Last Error Status
Level 0 : 0x0(GOOD)

ECC Error Status
Tag     Errors      CE Count  UE Count  CE FFA              UE FFA              
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Memory Status
     Tag                 Type        Temp(C)  Base Address    Size    Mem Usage   BO count
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DMA Transfer Metrics
Chan[0].h2c:  0 Byte
Chan[0].c2h:  0 Byte
Chan[1].h2c:  0 Byte
Chan[1].c2h:  0 Byte
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Streams
     Tag         Flow ID  Route ID Status   Total (B/#)     Pending (B/#)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Xclbin UUID
00000000-0000-0000-0000-000000000000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compute Unit Status
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Partition Info:
    installation
        installed_package_dir: /opt/xilinx/firmware/u2/gen3x4-xdma/base
        installed_package_name: xilinx-u2-gen3x4-xdma-base
        installed_package_release: 3050351
        installed_package_version: 1
    partition_card: u2
    partition_family: gen3x4-xdma
    partition_features
        pcie
            device_ids
                6987
                    role: management_pf
                6988
                    role: user_pf
            extended_capabilities: enabled
            max_link_speed: gen3x4
            subsystem_id: 000e
            vendor_id: 10ee
    partition_identifiers
        interface_uuids
            109f96074632cd8264b329f84b14cb30
                type: exposed
        logic_uuid: fd5aae95f114297b10995aacac916eb7
    partition_name: base
    partition_type: base
    partition_vendor: xilinx
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: xbutil query succeeded.
```
xbutil flash scan
```
Card [0000:3e:00.0]
    Card type:		u2
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b],[SC=INACTIVE]
    Flashable partitions installed in system:	
        xilinx_samsung_u2x4_202010_1,[ID=0x5f19544a]
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b]
```
xbmgmt flash --scan
```
Card [0000:3e:00.0]
    Card type:		u2
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b],[SC=INACTIVE]
    Flashable partitions installed in system:	
        xilinx_samsung_u2x4_202010_1,[ID=0x5f19544a]
        xilinx_u2_gen3x4_xdma_base_1,[ID=0xfd5aae95f114297b]
```

**Comment by rajkumar-xilinx** [comment]
**On U250**

xbmgmt flash --scan
```
Card [0000:5e:00.0]
    Card type:		u250
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=0.0]
    Flashable partitions installed in system:	
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=4.6.6]

```
xbutil flash scan
```
WARNING: The xbutil sub-command flash has been deprecated. Please use the xbmgmt utility with flash sub-command for equivalent functionality.
Card [0000:5e:00.0]
    Card type:		u250
    Flash type:		SPI
    Flashable partition running on FPGA:
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=0.0]
    Flashable partitions installed in system:	
        xilinx_u250_gen3x16_base_3,[ID=0xef6fdbfd98962bf2],[SC=4.6.6]

```

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
Thanks @rajkumar-xilinx  for verifying on U50/U250/U2. Removed the do not merge tag. As there is no auto-merging to 2020.2 anymore. Please send a PR to 2020.2 aswell

**Comment by rajkumar-xilinx** [comment]
> Thanks @rajkumar-xilinx for verifying on U50/U250/U2. Removed the do not merge tag. As there is no auto-merging to 2020.2 anymore. Please send a PR to 2020.2 aswell

2020.2 change https://github.com/Xilinx/XRT/pull/4416

**Comment by rajkumar-xilinx** [comment]
Tried to enable & disable clock scaling feature on u2

```
$ /opt/xilinx/xrt/bin/xbmgmt config --device --runtime_clk_scale enable --card 0000:3e:00.0
$dmesg | tail
[ 2014.141485] xclmgmt 0000:3e:00.0: xmc.u2.m.18874369 ffff8ddeba02d810 runtime_clk_scale_enable: Runtime clock scaling is enabled
$/opt/xilinx/xrt/bin/xbmgmt config --device --runtime_clk_scale disable --card 0000:3e:00.0
$dmesg | tail
[ 2027.389211] xclmgmt 0000:3e:00.0: xmc.u2.m.18874369 ffff8ddeba02d810 runtime_clk_scale_disable: Runtime clock scaling is disabled
```

**Pull request merged**
