### PR TITLE
Fix zocl build for Linux kernel 5.9

### PR DESCRIPTION
**Pull request by matwey**

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Review by larry9523 — APPROVED** [review]
Thanks for the patch. It looks good.
The only nit I have is it might be better if we are consistent on
LINUX_VERSION_CODE >= KERNEL_VERSION(5.9.0) and KERNEL_VERSION(5.9.0) >= KERNEL_VERSION(5.9.0)
I prefer the former.  ( I know we are not yet consistent across all zocl code :))

**Comment by matwey** [comment]
I see that there is already fix for this issue in: #4534

**Comment by larry9523** [comment]
> I see that there is already fix for this issue in: #4534

that is for xocl only, isn't it?

**Comment by matwey** [comment]
Ah, you are right... I will account your comments tomorrow.

**Comment by mclayton1000** [comment]
Hi @matwey  , hi @maxzhen , hi @larry9523 ,
as in #4534 , the patch should check for Linux >= 5.7, because those changes were introduced from kernel 5.7.
```
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,7,0)
+       .gem_free_object_unlocked       = xocl_free_object,
+#else
        .gem_free_object                = xocl_free_object,
+#endif
```
and:
```
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,7,0)
+       #define XOCL_DRM_GEM_OBJECT_PUT_UNLOCKED drm_gem_object_put
+       #define XOCL_DRM_GEM_OBJECT_GET drm_gem_object_get
+#elif LINUX_VERSION_CODE >= KERNEL_VERSION(4,12,0)
```
Best regards.

**Pull request merged**
