### PR TITLE
CR-1100087 - Change in the u30flashall.sh script to improve user experience

### PR DESCRIPTION
**Pull request by rozumx**
This submission replaces the `u30flashall.sh` script with `xball`.  This script is a generic script that will allow the user to:

1. Discover the installed devices on the server.
2. Filter (via a regex pattern) devices (via shell names) of interest
3. Call each device with a given set of xbutil or xbmgmt options.
4. Have a summary of success and/or failures for each call individual call for the device.

In addition, this script has error checking and a built in help function:
```
$ xball --help

DESCRIPTION: This script will discover the installed card(s) in the system,
             optionally filter the cards of interest, and execute the given
             command options for either the 'xbutil' or 'xbmgmt' applications.

USAGE: xball [--help] [--device-filter arg] <xbutil | xbmgmt> <application arguments>

OPTIONS:
  --help          - Help to use this script.
  --device-filter - Shell name regex filter.  For example:
                      '.'            - Applies command to ALL found devices (default)
                      'u30'          - Only u30 devices
                      '^xilinx_u250' - Shell names starting with xilnx_u250

Additionally, the 'application arguments' are the arguments that will be sent to
the given xrt application (e.g., xbutil or xbmgmt)
```

### CODE REVIEW

**Review by sonals — COMMENTED** [review]
deviceall seems a very generic name. Should it more like xball or xbstar?

**Comment by dayeh-xilinx** [comment]
retest this please. Failed with cold reboot timeout infra error.

**Comment by rozumx** [comment]
Rename to deviceall to xball

**Review by AShivangi — APPROVED** [review]

**Review by maxzhen — APPROVED** [review]

**Review by stsoe — APPROVED** [review]

**Review by sonals — APPROVED** [review]
Consider changing _application_ to _utility_ but good otherwise.

**Pull request merged**
