### PR TITLE
auto flash versal

### PR DESCRIPTION
**Pull request by AShivangi**
cherry-picking Larry's and my changes

### CODE REVIEW

**Comment by maxzhen** [comment]
@AShivangi @larry9523 is this CR approved for PU2 branch?

**Comment by AShivangi** [comment]
Not yet. Waiting for approval from Teresa

**Comment by maxzhen** [comment]
Holding off the merge while waiting for approval.

**Comment by maxzhen** [comment]
Merging based on Sumit's approval.

**Pull request merged**
