### PR TITLE
XRT-341 memory resource definition conflict (#3083)

### PR DESCRIPTION
**Pull request by chienwei-lan**
back port memory resource definition conflict to PU2 branch

### CODE REVIEW

**Comment by chienwei-lan** [comment]
retest this please

**Comment by stsoe** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by chienwei-lan** [comment]
Hello @chvamshi-xilinx, do you see any reason why this change may fail some sw_emu tests?

**Comment by chvamshi-xilinx** [comment]
> 
> 
> Hello @chvamshi-xilinx, do you see any reason why this change may fail some sw_emu tests?

Hi Chienwei, This is not going to effect sw_emu at all. Looks like some infra issue. You can safely ignore sw_emu failures..

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
