### PR TITLE
Disable warnings about anymous structs when compiled with GCC and -Wp…

### PR DESCRIPTION
**Pull request by qberthet**
#### Problem solved by the commit
When XRT is linked to projects compiled with GCC and using -Wpedantic, few warnings concerning anonymous structs are fired:
```
...
/opt/xilinx/xrt/include/xrt_mem.h:59:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
   59 |     struct {
...
/opt/xilinx/xrt/include/ert.h:93:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
   93 |     struct {
...
```
#### How problem was solved, alternative solutions (if any) and why they were rejected
Added 
```
#if defined(__GNUC__)
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wpedantic"
#endif
```
to disable -Wpedantic in the two headers causing the warning. 

**Note:** Another approach to fix these warning would have been to prefix the structs definition by `__extension__` intrinsic for GCC only as shown in [this](https://github.com/boostorg/winapi/commit/f004b4753d6fee6f68c90cfc65b075fa0a33d092) commit. This have the advantage of not disabling -Wpedantic for the full file but reduces the code readability. I have choosen the above solution as a similar warning silencing seems to be implemented in both file for WIN32.

#### Risks (if any) associated the changes in the commit
-Wpedantic being disabled for these two file, it might silence usefull warning in the future.

#### What has been tested and how, request additional testing if necessary
The warnings are not fired during compilation anymore and the build is successful.
#### Documentation impact (if any)
None that I am aware of.

### CODE REVIEW

**Comment by qberthet** [comment]
Re-created with signed-off commit

**Review by stsoe — CHANGES_REQUESTED** [review]
Yeah, thanks.  But isn't a pop needed at end of file?  

Looks like the same goes for the windows disabling in the same headers, but changing that may have ripple effects so we will leave them for now.

**Comment by qberthet** [comment]
My bad, you're absolutely right.
PR updated.

Note that windows flags pop are already present at the end of the file.

**Review by stsoe — APPROVED** [review]
Great thanks!

**Review by keryell — COMMENTED** [review]
Naïve question: why not giving a name to the struct. It will replace the lacking comment anyway which is MISSING. :-)

**Comment by qberthet** [comment]
If that's an option for you, this is great, but be aware that this will change the access syntax:

if
```
struct xcl_bo_flags
{
  union {
    uint32_t flags;
    struct {
      uint16_t bank;       // [15-0]
      uint8_t  slot;       // [16-23]
      uint8_t  boflags;    // [24-31]
    };
  };
};
```
is changed for
```
struct xcl_bo_flags
{
  union {
    uint32_t flags;
    struct foo {
      uint16_t bank;       // [15-0]
      uint8_t  slot;       // [16-23]
      uint8_t  boflags;    // [24-31]
    };
  };
};
```
you will need to change all the `xcl_bo_flags.bank` access by `xcl_bo_flags.foo.bank`.
Would that be acceptable ?

**Comment by stsoe** [comment]
> you will need to change all the `xcl_bo_flags.bank` access by `xcl_bo_flags.foo.bank`. Would that be acceptable ?

IMO, not at this point.   I prefer we stick with disabling the warnings.

**Comment by keryell** [comment]
I guess there is another problem with the unnamed `union` too and you do not need the top-level `struct`.
It should be:
```c++
union xcl_bo_flags {
  uint32_t flags;
  struct individual {
    uint16_t bank;       // [15-0]
    uint8_t  slot;       // [16-23]
    uint8_t  boflags;    // [24-31]
  };
};
```

**Comment by keryell** [comment]
Actually the `boflags` was just here because a name conflict due to anonymous struct... :-(
```c++
union xcl_bo_flags {
  uint32_t flags;
  struct individual {
    uint16_t bank;   // [15-0]
    uint8_t  slot;   // [16-23]
    uint8_t  flags;  // [24-31]
  };
};
```

**Comment by qberthet** [comment]
As mentionned in the initial message, another approach could be something like
```
#if defined(__GNUC__)
#define GCC_DETAIL_EXTENSION __extension__
#else
#define GCC_DETAIL_EXTENSION
#endif

struct xcl_bo_flags
{
  GCC_DETAIL_EXTENSION union {
    uint32_t flags;
    GCC_DETAIL_EXTENSION struct {
      uint16_t bank;       // [15-0]
      uint8_t  slot;       // [16-23]
      uint8_t  boflags;    // [24-31]
    };
  };
};
```
Suppress the warnings only on the required lines without changing the access syntax.

**Comment by stsoe** [comment]
Keep changes to a minimum now.  We will stick with the warning push/pop for now.

**Comment by keryell** [comment]
> Keep changes to a minimum now. We will stick with the warning push/pop for now.

Yes, I guess the design train left the station long time ago...

**Comment by stsoe** [comment]
ok to test

**Comment by stsoe** [comment]
retest this please

**Pull request merged**
