### PR TITLE
Change xrt_core to amd_xrt_core

### PR DESCRIPTION
**Pull request by AShivangi**
#### Problem solved by the commit
This change is to mimic https://github.com/Xilinx/XRT/pull/7828 while getting all the changes for xbutil from master

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected
We are trying to have all the changes for our upcoming release but the the IPU specific (dll name change) change. Instead of trying to cherry-pick all changes to xrt-ipu-231130 branch, it made sense to branch off from master and include this change.

#### Risks (if any) associated the changes in the commit
N/A

#### What has been tested and how, request additional testing if necessary
N/A

#### Documentation impact (if any)
N/A

### CODE REVIEW

**Review by stsoe — CHANGES_REQUESTED** [review]
Why?

**Comment by AShivangi** [comment]
Hi @stsoe, 
We are trying to have all the changes for our upcoming release but the the IPU specific (dll name change) change. Instead of trying to cherry-pick all changes to xrt-ipu-231130 branch, it made sense to branch off from master and include this change.

**Comment by stsoe** [comment]
@AShivangi Update PR description please.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Comment by AShivangi** [comment]
This doesn't works as we need a new branch setup in CI which takes a while. Closing this

**Pull request closed without merging**
