### PR TITLE
Adding numpy dependency in xrtdeps.sh & installation

### PR DESCRIPTION
**Pull request by chvamshi-xilinx**
This change contains a fix for missing numpy depedency in both xrtdeps.sh and instllation

### CODE REVIEW

**Comment by xilinxgitops** [comment]
Ok to test

**Comment by sabarinaxil** [comment]
ok to test

**Comment by xilinxgitops** [comment]
ok to test

**Comment by xilinxgitops** [comment]
retest this please

**Comment by sonals** [comment]
Is this requirement coming from my recent changes to python bindings and validate examples?

**Comment by chvamshi-xilinx** [comment]
> Is this requirement coming from my recent changes to python bindings and validate examples?

Yes Sonal. all PRs are failing with "numpy module not found" error. Looks like you introduced a new dependency, I dont see this dependency in xrtdeps, Thatswhy added.
I am not sure how your PR passed in pipeline (or i might be missing something here,)

**Comment by xilinxgitops** [comment]
retest this please

**Comment by sonals** [comment]
I believe it is 23_bandwidth.py. I will submit a PR to remove the usage of numpy.

**Comment by chvamshi-xilinx** [comment]
> I believe it is 23_bandwidth.py. I will submit a PR to remove the usage of numpy.

That would be ideal. This change is just to let other PRs go thru.

**Comment by chvamshi-xilinx** [comment]
@sonals , looks like issue is resolved with latest builds. I am not sure how numpy dependency is getting resolved. 
We still need to fix this issue.

**Pull request closed without merging**
