### PR TITLE
CR-1045783 xbutil2 bdf host report enhancement

### PR DESCRIPTION
**Pull request by sadasivanshaiju**
sadasiva@pranjal-dell:/proj/rdi/staff/sadasiva/XRT/build$ xbutil examine
System Configuration
  OS Name              : Linux
  Release              : 4.15.0-147-generic
  Version              : #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15727 MB
  Distribution         : Ubuntu 18.04.5 LTS
  GLIBC                : 2.27
  Model                : Precision 5820 Tower

XRT
  Version              : 2.12.0
  Branch               : interface
  Hash                 : a2765388a8cd9b3c31ca670a789a7787872ea7a7
  Hash Date            : 2021-09-09 05:28:40
  XOCL                 : 2.12.69, 37f86ed80380ced5c192acd10f7d3a2f6751877f
  XCLMGMT              : 2.12.69, 37f86ed80380ced5c192acd10f7d3a2f6751877f

Devices present
  [0000:17:00.1] : xilinx_u200_gen3x16_xdma_base_1 [15FB8DA1-F552-A9F9-23DE-6DC54AA8968F] user(inst=129) 

sadasiva@pranjal-dell:/proj/rdi/staff/sadasiva/XRT/build$

### CODE REVIEW

**Review by AShivangi — CHANGES_REQUESTED** [review]
Hi @sadasivanshaiju, 

Can you please change the interface uuid to `logic_uuid` instead?

Please refer to https://github.com/Xilinx/XRT/pull/5742/files `info_platform.cpp` L 36-49 on how to get the logic_uuid

**Comment by dayeh-xilinx** [comment]
retest this please. build failed for infra error.

**Comment by xilinxgitops** [comment]
retest this please

**Review by AShivangi — APPROVED** [review]

**Review by rozumx — APPROVED** [review]

**Comment by stsoe** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Pull request closed without merging**
