### PR TITLE
Add changes to support 5.15 kernel in edge platforms

### PR DESCRIPTION
**Pull request by rbramand-xilinx**
> Petalinux kernel moved to version 5.15, added changes to fix zocl driver compilation with Linux kernel version - 5.15
> Tested by running hello world example in hw_emu using latest kernel(5.15), compatible rootfs and sysroot
> Backward compatibility is maintained

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by chvamshi-xilinx** [comment]
This is important PR. We need to merge this change once build passes

**Review by keryell — APPROVED** [review]
Such a modernism is a gift from Santa Claus!
Go on! :-)

**Comment by salindac** [comment]
retest please

**Comment by chvamshi-xilinx** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by kbhardwa-xilinx** [comment]
retest this please

**Comment by kbhardwa-xilinx** [comment]
retest this please

**Pull request merged**
