### PR TITLE
Add hal API to give generic access to sysfs for each device

### PR DESCRIPTION
**Pull request by tianhaoz95**
In debug and profile refactoring, the knowledge about the debug ip layout will be moved to a higher level and leave hal layer cleaner, so access to sysfs will be needed.

This API takes subdevice name, entry name, either read_all or a certain size and read the content from sysfs.

example usage:
```cpp
xclSysfsQuery query;
strcpy(query.subdev, subdev.c_str());
strcpy(query.entry, entry.c_str());
query.read_all = read_all;
query.size = size;
int err = xclReadSysfs(device_handle, query, data);
```

>note: if size is non-zero and read_all is true the code will return -1 to prevent potential uninitialized query.

### CODE REVIEW

**Comment by maxzhen** [comment]
ok to test

**Comment by abalasa** [comment]
retest this please

**Comment by tianhaoz95** [comment]
just resolved a conflict introduced by enum clean up. please build again

**Comment by tianhaoz95** [comment]
I think that will also work for our purpose. The full path of sysfs is exposed in my other PR #837. If that is the way we want to give access to sysfs. This PR can be ignored.

**Comment by maxzhen** [comment]
Are you sure about that? It seems PR#837 only retrieves path up to the device, not up to the entry, right? I'm talking about an API to return full abs path up to the entry...

**Pull request closed without merging**
