### PR TITLE
Add changes for supporting XRT on RHEL 8.4

### PR DESCRIPTION
**Pull request by eshwar-xilinx**
> added changes to fix driver compilation issues while installing XRT
> fixed segmentation fault in python_binding test

### CODE REVIEW

**Review by chvamshi-xilinx — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
ok to test

**Comment by xilinxgitops** [comment]
retest this please

**Comment by stsoe** [comment]
The order of import of pyxrt is not obvious, a commit comment would be good.

**Comment by eshwar-xilinx** [comment]
Hi stsoe,  edited commit message

**Pull request merged**
