### PR TITLE
Routing xma log to syslog (2018.3)

### PR DESCRIPTION
**Pull request by hasansayani-xilinx**
This was needed by client. This will be later deprecated once XRT provides log level control for xclLogMsg()

### CODE REVIEW

**Comment by hasansayani-xilinx** [comment]
@sarab96 , please can you review and accept PR.

**Comment by sonals** [comment]
ok to test

**Comment by NaAl-Xlnx** [comment]
retest this please

**Comment by maxzhen** [comment]
retest this please

**Pull request merged**
