### PR TITLE
Enable zc706

### PR DESCRIPTION
**Pull request by sivarajeshjarugula**
removed the commented line

### CODE REVIEW

**Comment by maxzhen** [comment]
@sivarajeshjarugula please resolve conflicts.

**Comment by sivarajeshjarugula** [comment]
resolved the conflicts

**Comment by mamin506** [comment]
@abalasa Please review the platforms.build change.

**Comment by abalasa** [comment]
ok to test

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
