### PR TITLE
CR-1151004 ASTeR TC 19.02 - v70 - server crash occurs shortly after a…

### PR DESCRIPTION
**Pull request by xdavidz**
… (#7306)

cold reboot and the xbmgmt examine command is ran

Signed-off-by: David Zhang <davidzha@xilinx.com>

Signed-off-by: David Zhang <davidzha@xilinx.com>

#### Problem solved by the commit
This was a clean backport.

### CODE REVIEW

**Review by maxzhen — APPROVED** [review]

**Comment by xdavidz** [comment]
retest this please
```
Manikandan Subramaniam
  [1 minute ago](https://xilinx.slack.com/archives/CG29V6XPF/p1674863013928569?thread_ts=1674851778.409159&cid=CG29V6XPF)
Is it failing consistently. If possible can you re-run
```

**Comment by manikandan-xilinx** [comment]
> retest this please
> 
> ```
> Manikandan Subramaniam
>   [1 minute ago](https://xilinx.slack.com/archives/CG29V6XPF/p1674863013928569?thread_ts=1674851778.409159&cid=CG29V6XPF)
> Is it failing consistently. If possible can you re-run
> ```

@xdavidz can you rerun the Github Actions job. Build pipeline was already passing right?

**Comment by xdavidz** [comment]
> > retest this please
> > ```
> > Manikandan Subramaniam
> >   [1 minute ago](https://xilinx.slack.com/archives/CG29V6XPF/p1674863013928569?thread_ts=1674851778.409159&cid=CG29V6XPF)
> > Is it failing consistently. If possible can you re-run
> > ```
> 
> @xdavidz can you rerun the Github Actions (binary_check) job. Build pipeline was already passing right?



> > retest this please
> > ```
> > Manikandan Subramaniam
> >   [1 minute ago](https://xilinx.slack.com/archives/CG29V6XPF/p1674863013928569?thread_ts=1674851778.409159&cid=CG29V6XPF)
> > Is it failing consistently. If possible can you re-run
> > ```
> 
> @xdavidz can you rerun the Github Actions (binary_check) job. Build pipeline was already passing right?

Manually re-run Actions passed. I was not aware of retest is only for pipeline and Actions should be re-run in different way. Let's wait for pipeline clean again.

**Comment by dayeh-xilinx** [comment]
retest this please.

**Pull request merged**
