### PR TITLE
Xbutil reset issue fixed related to hwmon

### PR DESCRIPTION
**Pull request by saifuddin-xilinx**
#### Problem solved by the commit
The issue solved the following CR:
https://jira.xilinx.com/browse/CR-1163852

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
-- The issue is because of deleting of sysfs entry. 
-- Currently without disabling the hwmon sub device  we are initiating the PCI reset , Which is removing the sysfs entry.
-- Added subdevice offline for hwmon device before reset. 
-- Verified the changes by running "xbutil reset" under a loop from inside doker and host machine of 50 times

### CODE REVIEW

**Comment by maxzhen** [comment]
What is the root cause of the CR?

**Comment by saifuddin-xilinx** [comment]
> What is the root cause of the CR?
While resetting device multiple time we are observing the following crash:

                    - [18908.446405] xclmgmt 0000:e2:00.0:  ffffa0053974c098 __xocl_subdev_offline: offline subdev xgq_vmr, cdev ffffa00c95163780
                    - [18908.446610] xclmgmt 0000:e2:00.0: xgq_vmr.m.55574528 ffffa00c9a4a6810 xgq_stop_services: stopping xgq services
                    - [18908.446616] xclmgmt 0000:e2:00.0: xgq_vmr.m.55574528 ffffa00c9a4a6810 xgq_stop_services: xgq services are stopped
                    - [18913.124322] xclmgmt 0000:e2:00.0:  ffffa0053974c098 __xocl_subdev_destroy: Destroy subdev hwmon_sdm, cdev           (null)
                    - [19083.717076] INFO: task kworker/u128:8:1578 blocked for more than 120 seconds.
                    - [19083.717233] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
                    - [19083.717366] kworker/u128:8  D ffffa0049ec5acc0     0  1578      2 0x00000000
                    - [19083.717533] Workqueue: mgmt_wq0 xclmgmt_work_cb [xclmgmt]
                    - [19083.717649] Call Trace:
                    - [19083.717777]  [<ffffffff8e787169>] schedule+0x29/0x70
                    - [19083.717907]  [<ffffffff8e2d880d>] __kernfs_remove+0x17d/0x260
                    - [19083.718062]  [<ffffffff8e0c6d10>] ? wake_up_atomic_t+0x30/0x30
                    - [19083.718208]  [<ffffffff8e2d97c1>] kernfs_remove+0x21/0x30
                    - [19083.718348]  [<ffffffff8e2dbd60>] sysfs_remove_dir+0x50/0x80
                    - [19083.718493]  [<ffffffff8e388938>] kobject_del+0x18/0x50
                    - [19083.718642]  [<ffffffff8e4b642d>] device_del+0x1ad/0x210
                    - [19083.718783]  [<ffffffff8e4b64ae>] device_unregister+0x1e/0x60
                    - [19083.718932]  [<ffffffff8e59a618>] hwmon_device_unregister+0x48/0xa0
                    - [19083.719108]  [<ffffffffc0dba2e7>] hwmon_sdm_remove+0xb7/0x140 [xclmgmt]
                    - [19083.719472]  [<ffffffff8e4bd713>] platform_drv_remove+0x23/0xa0

I have taken a reference of existing Linux code. Please refer https://elixir.bootlin.com/linux/latest/source/drivers/hwmon/ibmaem.c#L928

**Review by chvamshi-xilinx — COMMENTED** [review]
I dont understand this code. Removing myself from reviewer list.

**Comment by maxzhen** [comment]
Adding @houlz0507 who is the best person to review.

**Review by rajkumar-xilinx — CHANGES_REQUESTED** [review]
Hi @saifuddin-xilinx , as discussed offline, this is not right change. Driver has to register sysfs with hwmon handle only, otherwise, sysfs entries will not be available under hwmon/.

Please analyze the reset flow again.

**Review by chvamshi-xilinx — APPROVED** [review]
Looks good. Please update PR description aswell.

**Review by houlz0507 — APPROVED** [review]

**Review by maxzhen — APPROVED** [review]

**Comment by chvamshi-xilinx** [comment]
retest this please

**Review by rajkumar-xilinx — APPROVED** [review]

**Pull request merged**
