### PR TITLE
DFX platform hung loading multiple xclbins multiple times when interrupt enabled

### PR DESCRIPTION
**Pull request by Himanshu-xilinx**
FullPlatformBuild:Yes

### CODE REVIEW

**Comment by xdavidz** [comment]
This wouldn't needed after context switch, because context switch move the reset to the right place. But if 2019.2 only needs this small fix and exclude context switch for sure @chvamshi-xilinx , please go ahead.

**Comment by chvamshi-xilinx** [comment]
> 
> 
> This wouldn't needed after context switch, because context switch move the reset to the right place. But if 2019.2 only needs this small fix and exclude context switch for sure @chvamshi-xilinx , please go ahead.

Thanks David. This doesn't support context switch , but swapping xclbins one after the other is working as expected.

**Comment by xdavidz** [comment]
> > This wouldn't needed after context switch, because context switch move the reset to the right place. But if 2019.2 only needs this small fix and exclude context switch for sure @chvamshi-xilinx , please go ahead.
> 
> Thanks David. This doesn't support context switch , but swapping xclbins one after the other is working as expected.

Do we need context switch for 2019.2 due to this CR: http://jira.xilinx.com/browse/CR-1047439.
I haven't got time to verify that yet.

I am not targeting context switch for 2019.2 as of now. Please advise.

**Comment by chvamshi-xilinx** [comment]
> 
> 
> > > This wouldn't needed after context switch, because context switch move the reset to the right place. But if 2019.2 only needs this small fix and exclude context switch for sure @chvamshi-xilinx , please go ahead.
> > 
> > 
> > Thanks David. This doesn't support context switch , but swapping xclbins one after the other is working as expected.
> 
> Do we need context switch for 2019.2 due to this CR: http://jira.xilinx.com/browse/CR-1047439.
> I haven't got time to verify that yet.
> 
> I am not targeting context switch for 2019.2 as of now. Please advise.

No David. We are not targeting context switch for 2019.2. We can plan it for 2019.2_web if possible

**Comment by xdavidz** [comment]
> > > > This wouldn't needed after context switch, because context switch move the reset to the right place. But if 2019.2 only needs this small fix and exclude context switch for sure @chvamshi-xilinx , please go ahead.
> > > 
> > > 
> > > Thanks David. This doesn't support context switch , but swapping xclbins one after the other is working as expected.
> > 
> > 
> > Do we need context switch for 2019.2 due to this CR: http://jira.xilinx.com/browse/CR-1047439.
> > I haven't got time to verify that yet.
> > I am not targeting context switch for 2019.2 as of now. Please advise.
> 
> No David. We are not targeting context switch for 2019.2. We can plan it for 2019.2_web if possible

awesome, thanks!

**Pull request merged**
