### PR TITLE
CR 1087996: CU execution not reported in design with 2 cus (opencl_refactor)

### PR DESCRIPTION
**Pull request by pgschuey**
- now using CU events from trace to populate CU utilization table for HW and HW emu runs
- also reformatted a few files, using spaces instead of tabs

### CODE REVIEW

**Comment by pgschuey** [comment]
Please re-test.

**Comment by dayeh-xilinx** [comment]
retest this please. Disk space issue fixed.

**Comment by dayeh-xilinx** [comment]
retest this please. Try again for disk space issue.

**Review by jvillarre — APPROVED** [review]
Changes look good

**Pull request merged**
