### PR TITLE
CRs and qspi report for U30 (#4801)

### PR DESCRIPTION
**Pull request by AShivangi**
(cherry picked from commit db4164791ca87c0564d27814fba64e29568ce191)

### CODE REVIEW

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by xilinxgitops** [comment]
retest this please

**Comment by AShivangi** [comment]
retest this please

**Comment by dayeh-xilinx** [comment]
retest this please

**Pull request merged**
