### PR TITLE
Eliminate possibility of race condition in alloc kernel

### PR DESCRIPTION
**Pull request by jmouroux**
Signed-off-by: Jeffrey Mouroux <jmouroux@xilinx.com>

### CODE REVIEW

**Comment by maxzhen** [comment]
@sarab96 could you take a look?

**Comment by maxzhen** [comment]
ok to test

**Comment by sarab96** [comment]
Closing. Based on discussion not to allow changes in previous release

**Comment by jmouroux** [comment]
@sarab96   I thought we were halting such changes in 2020.2 onward.  No?

**Pull request closed without merging**
