### PR TITLE
CR-1054636 Hot Reset Robustness - Kernel panic during hot reset proce…

### PR DESCRIPTION
**Pull request by houlz0507**
…dure

### CODE REVIEW

**Comment by houlz0507** [comment]
retest this please

**Comment by houlz0507** [comment]
Looked at the error, it is due to xcosda113 runs into disk chk and power cycle loop.

**Comment by houlz0507** [comment]
retest this please

**Comment by houlz0507** [comment]
retest this please

**Comment by houlz0507** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Pull request merged**
